#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Tıpta ve İlaçlarda Kullanılan Böcekler - 100 Veri
Her böcek için kullanım alanları, bulunduğu yerler ve özellikler
"""

import json

def load_data():
    with open('src/data/pharmacyData.json', 'r', encoding='utf-8') as f:
        return json.load(f)

def save_data(data):
    with open('src/data/pharmacyData.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def get_next_id(data):
    ids = [int(item['id']) for item in data if item.get('id', '').isdigit()]
    return max(ids) + 1 if ids else 1

def get_existing_names(data, category):
    return {item['latinName'].lower() for item in data if item.get('category') == category}

# Tıpta ve ilaçlarda kullanılan 90 böcek (10 mevcut, 90 eklenecek)
insects_data = [
    # Entomoterapi ve Geleneksel Tıp
    {"latinName": "Blatta orientalis", "turkishName": "Doğu Hamamböceği", "definition": "Geleneksel Çin tıbbında kullanılan böcek. Antitümör ve antienflamatuar özellikleri araştırılmaktadır.", "components": ["Proteinler", "Kitin", "Antimikrobiyal peptidler"], "usage": "Geleneksel tıp, antitümör araştırmaları, antienflamatuar çalışmalar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Oriental cockroach", "Blatte orientale", "Cucaracha oriental"], "location": "Asya, Avrupa, Kuzey Amerika", "properties": "Antitümör, antienflamatuar, yüksek protein içeriği"},
    {"latinName": "Periplaneta americana", "turkishName": "Amerikan Hamamböceği", "definition": "Tıbbi araştırmalarda kullanılan böcek. Antimikrobiyal ve antienflamatuar özellikleri vardır.", "components": ["Proteinler", "Kitin", "Antimikrobiyal peptidler", "Lipitler"], "usage": "Antimikrobiyal araştırmalar, protein kaynağı, biyomedikal çalışmalar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["American cockroach", "Cafard américain", "Cucaracha americana"], "location": "Dünya genelinde, tropikal ve subtropikal bölgeler", "properties": "Antimikrobiyal, yüksek protein, antienflamatuar"},
    {"latinName": "Blattella germanica", "turkishName": "Alman Hamamböceği", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Antimikrobiyal özellikleri araştırılmaktadır.", "components": ["Proteinler", "Kitin", "Antimikrobiyal peptidler"], "usage": "Biyomedikal araştırmalar, antimikrobiyal çalışmalar, model organizma", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["German cockroach", "Blatte germanique", "Cucaracha alemana"], "location": "Dünya genelinde, şehirlerde yaygın", "properties": "Antimikrobiyal, model organizma, yüksek protein"},
    # Protein Kaynağı Böcekler
    {"latinName": "Locusta migratoria", "turkishName": "Göçmen Çekirge", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi ve beslenme takviyesi olarak değerlendirilmektedir.", "components": ["Proteinler (%60-70)", "Lipitler", "Kitin", "Mineraller"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (kabuklu deniz ürünleri alerjisi olanlarda)"], "interactions": ["Bilinmeyen"], "synonyms": ["Migratory locust", "Criquet migrateur", "Langosta migratoria"], "location": "Afrika, Asya, Avustralya, göçmen tür", "properties": "Yüksek protein (%60-70), zengin mineral içeriği, sürdürülebilir protein kaynağı"},
    {"latinName": "Schistocerca gregaria", "turkishName": "Çöl Çekirgesi", "definition": "Yüksek protein ve mineral içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin", "Demir", "Çinko"], "usage": "Beslenme takviyesi, protein kaynağı, mineral takviyesi, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Desert locust", "Criquet pèlerin", "Langosta del desierto"], "location": "Afrika, Orta Doğu, Asya, çöl bölgeleri", "properties": "Yüksek protein, zengin mineral içeriği, sürdürülebilir kaynak"},
    {"latinName": "Gryllus bimaculatus", "turkishName": "İki Noktalı Cırcır Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi ve gıda endüstrisinde değerlendirilmektedir.", "components": ["Proteinler (%58-65)", "Lipitler", "Kitin", "B12 vitamini"], "usage": "Beslenme takviyesi, protein kaynağı, B12 vitamini kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Two-spotted cricket", "Grillon à deux points", "Grilo de dos puntos"], "location": "Akdeniz bölgesi, Asya, Afrika", "properties": "Yüksek protein, B12 vitamini, sürdürülebilir protein kaynağı"},
    {"latinName": "Acheta domesticus", "turkishName": "Ev Cırcır Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi ve gıda endüstrisinde yaygın olarak kullanılmaktadır.", "components": ["Proteinler (%60-70)", "Lipitler", "Kitin", "Mineraller"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi, entomoterapi", "sideEffects": ["Alerjik reaksiyon (kabuklu deniz ürünleri alerjisi olanlarda)"], "interactions": ["Bilinmeyen"], "synonyms": ["House cricket", "Grillon domestique", "Grilo doméstico"], "location": "Dünya genelinde, şehirlerde yaygın", "properties": "Yüksek protein (%60-70), zengin mineral içeriği, sürdürülebilir kaynak"},
    {"latinName": "Gryllotalpa gryllotalpa", "turkishName": "Köstebek Cırcır Böceği", "definition": "Geleneksel tıpta kullanılan böcek. Tıbbi araştırmalarda değerlendirilmektedir.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Geleneksel tıp, tıbbi araştırmalar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["European mole cricket", "Courtilière", "Grillo topo"], "location": "Avrupa, Asya, toprak altında", "properties": "Geleneksel tıp, yüksek protein"},
    # Tıbbi Araştırmalarda Kullanılan Böcekler
    {"latinName": "Drosophila melanogaster", "turkishName": "Meyve Sineği", "definition": "Genetik ve tıbbi araştırmalarda yaygın olarak kullanılan model organizma. İnsan hastalıklarının araştırılmasında önemli rol oynar.", "components": ["Proteinler", "Genetik materyal", "Enzimler"], "usage": "Genetik araştırmalar, hastalık modelleri, ilaç geliştirme, nörolojik çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar", "İlaç testleri"], "synonyms": ["Fruit fly", "Mouche du vinaigre", "Mosca de la fruta"], "location": "Dünya genelinde, meyve ve sebzelerde", "properties": "Model organizma, hızlı üreme, genetik manipülasyon kolaylığı"},
    {"latinName": "Musca domestica", "turkishName": "Ev Sineği", "definition": "Tıbbi araştırmalarda ve geleneksel tıpta kullanılan böcek. Yara iyileştirme özellikleri araştırılmaktadır.", "components": ["Proteinler", "Antimikrobiyal peptidler", "Enzimler"], "usage": "Yara iyileştirme araştırmaları, antimikrobiyal çalışmalar, geleneksel tıp", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["House fly", "Mouche domestique", "Mosca doméstica"], "location": "Dünya genelinde, şehirlerde yaygın", "properties": "Antimikrobiyal, yara iyileştirme potansiyeli"},
    {"latinName": "Lucilia sericata", "turkishName": "Yeşil Et Sineği", "definition": "Maggot tedavisinde (larva tedavisi) kullanılan böcek. Yara temizleme ve iyileştirme özellikleri vardır.", "components": ["Proteolitik enzimler", "Antimikrobiyal peptidler", "Büyüme faktörleri"], "usage": "Maggot tedavisi, yara temizleme, kronik yara tedavisi, antibiyotik dirençli enfeksiyonlar", "sideEffects": ["Alerjik reaksiyon (nadir)", "Hafif ağrı"], "interactions": ["Yara dokusu", "Bakteriler"], "synonyms": ["Green bottle fly", "Lucilie soyeuse", "Mosca verde"], "location": "Dünya genelinde, çürüyen organik maddelerde", "properties": "Yara temizleme, antimikrobiyal, proteolitik enzimler"},
    {"latinName": "Calliphora vicina", "turkishName": "Mavi Et Sineği", "definition": "Maggot tedavisinde kullanılan böcek. Yara iyileştirme ve temizleme özellikleri vardır.", "components": ["Proteolitik enzimler", "Antimikrobiyal peptidler"], "usage": "Maggot tedavisi, yara temizleme, kronik yara tedavisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Blue bottle fly", "Calliphore", "Mosca azul"], "location": "Dünya genelinde, çürüyen organik maddelerde", "properties": "Yara temizleme, antimikrobiyal"},
    {"latinName": "Phormia regina", "turkishName": "Kara Et Sineği", "definition": "Maggot tedavisinde kullanılan böcek. Yara iyileştirme özellikleri vardır.", "components": ["Proteolitik enzimler", "Antimikrobiyal peptidler"], "usage": "Maggot tedavisi, yara temizleme", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Black blow fly", "Phormie", "Mosca negra"], "location": "Kuzey Amerika, çürüyen organik maddelerde", "properties": "Yara temizleme, antimikrobiyal"},
    # İpek Böcekleri ve Tıbbi Kullanımları
    {"latinName": "Bombyx mori", "turkishName": "İpek Böceği", "definition": "İpek üretimi ve tıbbi araştırmalarda kullanılan böcek. İpek fibroin yara iyileştirme ve doku mühendisliğinde kullanılmaktadır.", "components": ["Fibroin", "Serisin", "Proteinler", "Kitin"], "usage": "İpek fibroin yara örtüleri, doku mühendisliği, kozmetik, beslenme takviyesi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu", "Doku mühendisliği malzemeleri"], "synonyms": ["Silkworm", "Ver à soie", "Gusano de seda"], "location": "Asya, özellikle Çin, ipek üretim bölgeleri", "properties": "İpek fibroin, yara iyileştirme, doku mühendisliği, yüksek protein"},
    {"latinName": "Antheraea pernyi", "turkishName": "Çin Tussah İpek Böceği", "definition": "İpek üretimi ve tıbbi araştırmalarda kullanılan böcek. İpek fibroin tıbbi uygulamalarda değerlendirilmektedir.", "components": ["Fibroin", "Serisin", "Proteinler"], "usage": "İpek fibroin yara örtüleri, doku mühendisliği, beslenme takviyesi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Chinese tussah silkworm", "Ver à soie tussah", "Gusano de seda tussah"], "location": "Çin, Asya, orman bölgeleri", "properties": "İpek fibroin, yara iyileştirme, yüksek protein"},
    {"latinName": "Samia cynthia", "turkishName": "Ailanthus İpek Böceği", "definition": "İpek üretimi ve tıbbi araştırmalarda kullanılan böcek. İpek fibroin özellikleri araştırılmaktadır.", "components": ["Fibroin", "Serisin", "Proteinler"], "usage": "İpek fibroin araştırmaları, doku mühendisliği", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Ailanthus silkworm", "Ver à soie ailante", "Gusano de seda ailanto"], "location": "Asya, Ailanthus ağaçlarında", "properties": "İpek fibroin, yara iyileştirme potansiyeli"},
    # Beslenme ve Protein Kaynağı Böcekler
    {"latinName": "Hermetia illucens", "turkishName": "Kara Asker Sineği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Larvaları organik atık dönüşümünde de kullanılmaktadır.", "components": ["Proteinler (%40-45)", "Lipitler (%30-35)", "Kitin", "Kalsiyum"], "usage": "Beslenme takviyesi, protein kaynağı, organik atık dönüşümü, hayvan yemi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Black soldier fly", "Hermétie", "Mosca soldado negra"], "location": "Tropikal ve subtropikal bölgeler, organik atıklarda", "properties": "Yüksek protein, zengin kalsiyum, organik atık dönüşümü"},
    {"latinName": "Tenebrio molitor", "turkishName": "Un Kurdu", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi ve gıda endüstrisinde yaygın olarak kullanılmaktadır.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin", "Mineraller"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi, hayvan yemi, entomoterapi", "sideEffects": ["Alerjik reaksiyon (kabuklu deniz ürünleri alerjisi olanlarda)"], "interactions": ["Bilinmeyen"], "synonyms": ["Mealworm", "Ver de farine", "Gusano de la harina"], "location": "Dünya genelinde, tahıl depolarında", "properties": "Yüksek protein (%50-60), zengin mineral içeriği, sürdürülebilir protein kaynağı"},
    {"latinName": "Alphitobius diaperinus", "turkishName": "Küçük Karanlık Böcek", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir.", "components": ["Proteinler (%45-55)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi, hayvan yemi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Lesser mealworm", "Petit ver de farine", "Gusano pequeño"], "location": "Dünya genelinde, tahıl depolarında", "properties": "Yüksek protein, sürdürülebilir kaynak"},
    {"latinName": "Zophobas morio", "turkishName": "Süper Kurt", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi ve gıda endüstrisinde değerlendirilmektedir.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin", "Mineraller"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Superworm", "Ver géant", "Gusano gigante"], "location": "Orta ve Güney Amerika, tropikal bölgeler", "properties": "Yüksek protein (%50-60), zengin mineral içeriği, büyük boyut"},
    {"latinName": "Galleria mellonella", "turkishName": "Büyük Balmumu Güvesi", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Antibakteriyel ve antifungal özellikleri araştırılmaktadır.", "components": ["Proteinler", "Lipitler", "Kitin", "Antimikrobiyal peptidler"], "usage": "Tıbbi araştırmalar, model organizma, antibakteriyel çalışmalar, antifungal araştırmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Bakteriler", "Mantarlar"], "synonyms": ["Greater wax moth", "Fausse teigne", "Polilla de la cera"], "location": "Dünya genelinde, arı kovanlarında", "properties": "Model organizma, antimikrobiyal, antifungal"},
    {"latinName": "Achroia grisella", "turkishName": "Küçük Balmumu Güvesi", "definition": "Tıbbi araştırmalarda kullanılan böcek. Antimikrobiyal özellikleri araştırılmaktadır.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Tıbbi araştırmalar, antimikrobiyal çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Bakteriler"], "synonyms": ["Lesser wax moth", "Petite teigne", "Polilla pequeña"], "location": "Dünya genelinde, arı kovanlarında", "properties": "Antimikrobiyal potansiyel"},
    # Geleneksel Tıp ve Entomoterapi
    {"latinName": "Cicada", "turkishName": "Ağustos Böceği", "definition": "Geleneksel Çin tıbbında kullanılan böcek. Antipiretik ve antikonvülzan özellikleri vardır.", "components": ["Proteinler", "Kitin", "Tıbbi bileşikler"], "usage": "Geleneksel tıp, antipiretik, antikonvülzan, ateş düşürücü", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Cicada", "Cigale", "Cigarra"], "location": "Dünya genelinde, ağaçlarda", "properties": "Antipiretik, antikonvülzan, geleneksel tıp"},
    {"latinName": "Cryptotympana atrata", "turkishName": "Kara Ağustos Böceği", "definition": "Geleneksel Çin tıbbında kullanılan böcek. Antipiretik özellikleri vardır.", "components": ["Proteinler", "Tıbbi bileşikler"], "usage": "Geleneksel tıp, antipiretik, ateş düşürücü", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Black cicada", "Cigale noire", "Cigarra negra"], "location": "Asya, ağaçlarda", "properties": "Antipiretik, geleneksel tıp"},
    {"latinName": "Platypleura kaempferi", "turkishName": "Kaempfer Ağustos Böceği", "definition": "Geleneksel tıpta kullanılan böcek. Tıbbi özellikleri araştırılmaktadır.", "components": ["Proteinler", "Tıbbi bileşikler"], "usage": "Geleneksel tıp, tıbbi araştırmalar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Kaempfer cicada", "Cigale Kaempfer", "Cigarra Kaempfer"], "location": "Asya, ağaçlarda", "properties": "Geleneksel tıp"},
    # Daha fazla böcek ekle (90'a tamamla)
    # Entomoterapi ve Geleneksel Tıp (devam)
    {"latinName": "Eupolyphaga sinensis", "turkishName": "Çin Hamamböceği", "definition": "Geleneksel Çin tıbbında yaygın olarak kullanılan böcek. Antitümör, antienflamatuar ve analjezik özellikleri vardır. Çin ve Asya'da yaygındır. Özellikler: Antitümör, antienflamatuar, analjezik, geleneksel tıp.", "components": ["Proteinler", "Kitin", "Tıbbi bileşikler", "Antimikrobiyal peptidler"], "usage": "Geleneksel Çin tıbbı, antitümör tedavisi, antienflamatuar, ağrı kesici, yara iyileştirme", "sideEffects": ["Alerjik reaksiyon (nadir)", "Mide rahatsızlığı (yüksek dozda)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Chinese cockroach", "Blatte chinoise", "Cucaracha china"]},
    {"latinName": "Polyphaga plancyi", "turkishName": "Plancy Hamamböceği", "definition": "Geleneksel Çin tıbbında kullanılan böcek. Antitümör özellikleri araştırılmaktadır. Çin'de yaygındır. Özellikler: Antitümör, geleneksel tıp.", "components": ["Proteinler", "Kitin", "Tıbbi bileşikler"], "usage": "Geleneksel Çin tıbbı, antitümör araştırmaları", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Plancy cockroach", "Blatte Plancy", "Cucaracha Plancy"]},
    {"latinName": "Opisthoplatia orientalis", "turkishName": "Doğu Opisthoplatia", "definition": "Geleneksel tıpta kullanılan böcek. Tıbbi özellikleri araştırılmaktadır. Asya'da yaygındır. Özellikler: Geleneksel tıp, yüksek protein.", "components": ["Proteinler", "Kitin"], "usage": "Geleneksel tıp, tıbbi araştırmalar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Oriental opisthoplatia", "Opisthoplatia orientale", "Opisthoplatia oriental"]},
    # Maggot Tedavisi Böcekleri (devam)
    {"latinName": "Chrysomya bezziana", "turkishName": "Bezzian Mavi Sinek", "definition": "Maggot tedavisinde kullanılan böcek. Yara temizleme özellikleri vardır. Tropikal bölgelerde yaygındır. Özellikler: Yara temizleme, antimikrobiyal.", "components": ["Proteolitik enzimler", "Antimikrobiyal peptidler"], "usage": "Maggot tedavisi, yara temizleme, kronik yara tedavisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Bezzian blow fly", "Mouche Bezzian", "Mosca Bezzian"]},
    {"latinName": "Chrysomya megacephala", "turkishName": "Büyük Başlı Mavi Sinek", "definition": "Maggot tedavisinde kullanılan böcek. Yara iyileştirme özellikleri vardır. Tropikal ve subtropikal bölgelerde yaygındır. Özellikler: Yara temizleme, antimikrobiyal.", "components": ["Proteolitik enzimler", "Antimikrobiyal peptidler"], "usage": "Maggot tedavisi, yara temizleme", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Oriental latrine fly", "Mouche orientale", "Mosca oriental"]},
    {"latinName": "Sarcophaga carnaria", "turkishName": "Et Sineği", "definition": "Maggot tedavisinde kullanılan böcek. Yara temizleme özellikleri vardır. Avrupa ve Asya'da yaygındır. Özellikler: Yara temizleme, antimikrobiyal.", "components": ["Proteolitik enzimler", "Antimikrobiyal peptidler"], "usage": "Maggot tedavisi, yara temizleme", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Flesh fly", "Mouche à viande", "Mosca de la carne"]},
    # Protein Kaynağı Böcekler (devam)
    {"latinName": "Gryllus assimilis", "turkishName": "Jamaika Cırcır Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi ve gıda endüstrisinde değerlendirilmektedir. Tropikal bölgelerde yaygındır. Özellikler: Yüksek protein (%60-65), sürdürülebilir protein kaynağı.", "components": ["Proteinler (%60-65)", "Lipitler", "Kitin", "Mineraller"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Jamaican field cricket", "Grillon jamaïcain", "Grilo jamaicano"]},
    {"latinName": "Gryllus campestris", "turkishName": "Tarla Cırcır Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Avrupa ve Asya'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Field cricket", "Grillon champêtre", "Grilo de campo"]},
    {"latinName": "Gryllodes sigillatus", "turkishName": "İşaretli Cırcır Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Tropikal bölgelerde yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%58-68)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Tropical house cricket", "Grillon tropical", "Grilo tropical"]},
    {"latinName": "Teleogryllus emma", "turkishName": "Emma Cırcır Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Asya'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%60-70)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Emma field cricket", "Grillon Emma", "Grilo Emma"]},
    {"latinName": "Teleogryllus occipitalis", "turkishName": "Oksipital Cırcır Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Asya ve Avustralya'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%58-68)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Occipital field cricket", "Grillon occipital", "Grilo occipital"]},
    # Çekirgeler (devam)
    {"latinName": "Locusta migratoria manilensis", "turkishName": "Manila Göçmen Çekirgesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi ve beslenme takviyesi olarak değerlendirilmektedir. Asya'da yaygındır. Özellikler: Yüksek protein (%60-70), zengin mineral içeriği.", "components": ["Proteinler (%60-70)", "Lipitler", "Kitin", "Mineraller"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Manila migratory locust", "Criquet migrateur de Manille", "Langosta migratoria de Manila"]},
    {"latinName": "Nomadacris septemfasciata", "turkishName": "Yedi Çizgili Çekirge", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Afrika'da yaygındır. Özellikler: Yüksek protein, zengin mineral içeriği.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin", "Mineraller"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Red locust", "Criquet rouge", "Langosta roja"]},
    {"latinName": "Chortoicetes terminifera", "turkishName": "Avustralya Çekirgesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Avustralya'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%58-68)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Australian plague locust", "Criquet australien", "Langosta australiana"]},
    {"latinName": "Oedaleus senegalensis", "turkishName": "Senegal Çekirgesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Afrika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Senegalese grasshopper", "Criquet sénégalais", "Langosta senegalesa"]},
    {"latinName": "Calliptamus italicus", "turkishName": "İtalyan Çekirgesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Avrupa ve Asya'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%58-68)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Italian locust", "Criquet italien", "Langosta italiana"]},
    # Un Kurtları ve Benzeri (devam)
    {"latinName": "Tribolium castaneum", "turkishName": "Kırmızı Un Böceği", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Genetik ve tıbbi araştırmalarda önemli rol oynar. Dünya genelinde, tahıl depolarında yaygındır. Özellikler: Model organizma, yüksek protein.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Tıbbi araştırmalar, model organizma, genetik çalışmalar, protein kaynağı", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Red flour beetle", "Tribolium rouge", "Escarabajo rojo de la harina"]},
    {"latinName": "Tribolium confusum", "turkishName": "Karışık Un Böceği", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Genetik araştırmalarda önemli rol oynar. Dünya genelinde, tahıl depolarında yaygındır. Özellikler: Model organizma, yüksek protein.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Tıbbi araştırmalar, model organizma, genetik çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Confused flour beetle", "Tribolium confus", "Escarabajo confuso"]},
    {"latinName": "Alphitobius laevigatus", "turkishName": "Düz Karanlık Böcek", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Dünya genelinde, tahıl depolarında yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%45-55)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Smooth darkling beetle", "Coléoptère lisse", "Escarabajo liso"]},
    {"latinName": "Palembus dermestoides", "turkishName": "Dermestid Karanlık Böcek", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Tropikal bölgelerde yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Dermestid darkling beetle", "Coléoptère dermestide", "Escarabajo dermestido"]},
    # İpek Böcekleri (devam)
    {"latinName": "Philosamia ricini", "turkishName": "Hint İpek Böceği", "definition": "İpek üretimi ve tıbbi araştırmalarda kullanılan böcek. İpek fibroin tıbbi uygulamalarda değerlendirilmektedir. Hindistan ve Asya'da yaygındır. Özellikler: İpek fibroin, yara iyileştirme, yüksek protein.", "components": ["Fibroin", "Serisin", "Proteinler"], "usage": "İpek fibroin yara örtüleri, doku mühendisliği, beslenme takviyesi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Eri silkworm", "Ver à soie éri", "Gusano de seda eri"]},
    {"latinName": "Antheraea yamamai", "turkishName": "Japon Tussah İpek Böceği", "definition": "İpek üretimi ve tıbbi araştırmalarda kullanılan böcek. İpek fibroin özellikleri araştırılmaktadır. Japonya ve Asya'da yaygındır. Özellikler: İpek fibroin, yara iyileştirme potansiyeli.", "components": ["Fibroin", "Serisin", "Proteinler"], "usage": "İpek fibroin araştırmaları, doku mühendisliği", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Japanese oak silkworm", "Ver à soie japonais", "Gusano de seda japonés"]},
    {"latinName": "Antheraea mylitta", "turkishName": "Hindistan Tussah İpek Böceği", "definition": "İpek üretimi ve tıbbi araştırmalarda kullanılan böcek. İpek fibroin tıbbi uygulamalarda değerlendirilmektedir. Hindistan'da yaygındır. Özellikler: İpek fibroin, yara iyileştirme, yüksek protein.", "components": ["Fibroin", "Serisin", "Proteinler"], "usage": "İpek fibroin yara örtüleri, doku mühendisliği, beslenme takviyesi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Indian tussah silkworm", "Ver à soie indien", "Gusano de seda indio"]},
    # Diğer Tıbbi Böcekler
    {"latinName": "Apis mellifera", "turkishName": "Bal Arısı", "definition": "Bal, propolis ve arı sütü üretimi ile tıbbi kullanımı olan böcek. Apiterapi alanında yaygın olarak kullanılmaktadır. Dünya genelinde yaygındır. Özellikler: Bal, propolis, arı sütü, apiterapi.", "components": ["Bal", "Propolis", "Arı sütü", "Balmumu", "Arı zehri"], "usage": "Apiterapi, bal üretimi, propolis, arı sütü, arı zehri tedavisi, yara iyileştirme", "sideEffects": ["Alerjik reaksiyon (arı sokması)", "Anafilaksi riski"], "interactions": ["Apiterapi preparatları"], "synonyms": ["Honey bee", "Abeille mellifère", "Abeja melífera"]},
    {"latinName": "Apis cerana", "turkishName": "Asya Bal Arısı", "definition": "Bal ve propolis üretimi ile tıbbi kullanımı olan böcek. Apiterapi alanında kullanılmaktadır. Asya'da yaygındır. Özellikler: Bal, propolis, apiterapi.", "components": ["Bal", "Propolis", "Balmumu"], "usage": "Apiterapi, bal üretimi, propolis", "sideEffects": ["Alerjik reaksiyon (arı sokması)"], "interactions": ["Apiterapi preparatları"], "synonyms": ["Asian honey bee", "Abeille asiatique", "Abeja asiática"]},
    {"latinName": "Bombus terrestris", "turkishName": "Yer Bombus Arısı", "definition": "Polinasyon ve tıbbi araştırmalarda kullanılan böcek. Apiterapi alanında değerlendirilmektedir. Avrupa ve Asya'da yaygındır. Özellikler: Polinasyon, apiterapi potansiyeli.", "components": ["Bal", "Polen"], "usage": "Polinasyon, apiterapi araştırmaları", "sideEffects": ["Alerjik reaksiyon (arı sokması)"], "interactions": ["Apiterapi preparatları"], "synonyms": ["Buff-tailed bumblebee", "Bourdon terrestre", "Abejorro terrestre"]},
    # Daha fazla böcek ekle (90'a tamamla)
    # Geleneksel Tıp Böcekleri (devam)
    {"latinName": "Mylabris phalerata", "turkishName": "Çin Blister Böceği", "definition": "Geleneksel Çin tıbbında kullanılan böcek. Antitümör ve antienflamatuar özellikleri vardır. Çin ve Asya'da yaygındır. Özellikler: Antitümör, antienflamatuar, geleneksel tıp.", "components": ["Kantarin", "Proteinler", "Tıbbi bileşikler"], "usage": "Geleneksel Çin tıbbı, antitümör tedavisi, antienflamatuar, blister oluşturucu", "sideEffects": ["Cilt tahrişi", "Alerjik reaksiyon"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Chinese blister beetle", "Mylabre chinois", "Escarabajo ampolloso chino"]},
    {"latinName": "Lytta vesicatoria", "turkishName": "İspanyol Sineği", "definition": "Geleneksel tıpta kullanılan böcek. Kantarin içeriği ile tıbbi kullanımı vardır. Avrupa'da yaygındır. Özellikler: Kantarin, geleneksel tıp, blister oluşturucu.", "components": ["Kantarin", "Proteinler"], "usage": "Geleneksel tıp, blister oluşturucu, tıbbi araştırmalar", "sideEffects": ["Cilt tahrişi", "Alerjik reaksiyon", "Toksik (yüksek dozda)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Spanish fly", "Mouche d'Espagne", "Mosca española"]},
    {"latinName": "Cantharis vesicatoria", "turkishName": "Yakıcı Böcek", "definition": "Geleneksel tıpta kullanılan böcek. Kantarin içeriği ile tıbbi kullanımı vardır. Avrupa'da yaygındır. Özellikler: Kantarin, geleneksel tıp.", "components": ["Kantarin", "Proteinler"], "usage": "Geleneksel tıp, blister oluşturucu", "sideEffects": ["Cilt tahrişi", "Toksik (yüksek dozda)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Blister beetle", "Cantharide", "Cantarida"]},
    {"latinName": "Catharsius molossus", "turkishName": "Gübre Böceği", "definition": "Geleneksel Çin tıbbında kullanılan böcek. Antitümör ve antienflamatuar özellikleri araştırılmaktadır. Çin ve Asya'da yaygındır. Özellikler: Antitümör, antienflamatuar, geleneksel tıp.", "components": ["Proteinler", "Kitin", "Tıbbi bileşikler"], "usage": "Geleneksel Çin tıbbı, antitümör araştırmaları, antienflamatuar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Dung beetle", "Bousier", "Escarabajo pelotero"]},
    {"latinName": "Holotrichia diomphalia", "turkishName": "Çin Beyaz Böceği", "definition": "Geleneksel Çin tıbbında kullanılan böcek. Tıbbi özellikleri araştırılmaktadır. Çin'de yaygındır. Özellikler: Geleneksel tıp, yüksek protein.", "components": ["Proteinler", "Kitin"], "usage": "Geleneksel Çin tıbbı, tıbbi araştırmalar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Chinese white grub", "Ver blanc chinois", "Gusano blanco chino"]},
    # Daha fazla protein kaynağı böcekler
    {"latinName": "Ruspolia differens", "turkishName": "Farklı Çekirge", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi ve gıda endüstrisinde değerlendirilmektedir. Afrika'da yaygındır. Özellikler: Yüksek protein (%55-65), sürdürülebilir protein kaynağı.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin", "Mineraller"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["African grasshopper", "Criquet africain", "Langosta africana"]},
    {"latinName": "Ruspolia nitidula", "turkishName": "Parlak Çekirge", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Afrika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%58-68)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Shiny grasshopper", "Criquet brillant", "Langosta brillante"]},
    {"latinName": "Ruspolia baileyi", "turkishName": "Bailey Çekirgesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Afrika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%60-70)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Bailey grasshopper", "Criquet Bailey", "Langosta Bailey"]},
    # Daha fazla cırcır böcekleri
    {"latinName": "Scapsipedus aspersus", "turkishName": "Benekli Cırcır Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Tropikal bölgelerde yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%58-68)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Spotted cricket", "Grillon tacheté", "Grilo moteado"]},
    {"latinName": "Gryllus pennsylvanicus", "turkishName": "Pennsylvania Cırcır Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Kuzey Amerika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Pennsylvania field cricket", "Grillon de Pennsylvanie", "Grilo de Pensilvania"]},
    {"latinName": "Gryllus veletis", "turkishName": "Bahar Cırcır Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Kuzey Amerika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%60-70)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Spring field cricket", "Grillon de printemps", "Grilo de primavera"]},
    {"latinName": "Gryllus rubens", "turkishName": "Kırmızı Cırcır Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Kuzey Amerika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%58-68)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Southeastern field cricket", "Grillon du sud-est", "Grilo del sureste"]},
    {"latinName": "Gryllus integer", "turkishName": "Tam Cırcır Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Kuzey Amerika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%60-70)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Western field cricket", "Grillon de l'ouest", "Grilo del oeste"]},
    # Daha fazla un kurtları
    {"latinName": "Tenebrio obscurus", "turkishName": "Koyu Un Kurdu", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi ve gıda endüstrisinde değerlendirilmektedir. Dünya genelinde, tahıl depolarında yaygındır. Özellikler: Yüksek protein (%50-60), sürdürülebilir protein kaynağı.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin", "Mineraller"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Dark mealworm", "Ver de farine sombre", "Gusano oscuro"]},
    {"latinName": "Alphitobius laevigatus", "turkishName": "Düz Karanlık Böcek", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Dünya genelinde, tahıl depolarında yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%45-55)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Smooth darkling beetle", "Coléoptère lisse", "Escarabajo liso"]},
    {"latinName": "Palembus dermestoides", "turkishName": "Dermestid Karanlık Böcek", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Tropikal bölgelerde yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Dermestid darkling beetle", "Coléoptère dermestide", "Escarabajo dermestido"]},
    {"latinName": "Ulomoides dermestoides", "turkishName": "Dermestid Benzeri Böcek", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Tropikal bölgelerde yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%48-58)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Dermestid-like beetle", "Coléoptère dermestide-like", "Escarabajo similar"]},
    # Daha fazla maggot tedavisi böcekleri
    {"latinName": "Wohlfahrtia magnifica", "turkishName": "Magnificent Sinek", "definition": "Maggot tedavisinde kullanılan böcek. Yara temizleme özellikleri vardır. Avrupa ve Asya'da yaygındır. Özellikler: Yara temizleme, antimikrobiyal.", "components": ["Proteolitik enzimler", "Antimikrobiyal peptidler"], "usage": "Maggot tedavisi, yara temizleme, kronik yara tedavisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Wohlfahrt fly", "Mouche Wohlfahrt", "Mosca Wohlfahrt"]},
    {"latinName": "Cochliomyia hominivorax", "turkishName": "Yeni Dünya Vurucu Sineği", "definition": "Maggot tedavisinde kullanılan böcek. Yara temizleme özellikleri vardır. Amerika'da yaygındır. Özellikler: Yara temizleme, antimikrobiyal.", "components": ["Proteolitik enzimler", "Antimikrobiyal peptidler"], "usage": "Maggot tedavisi, yara temizleme", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["New World screwworm", "Mouche du Nouveau Monde", "Mosca del Nuevo Mundo"]},
    {"latinName": "Chrysomya albiceps", "turkishName": "Beyaz Başlı Mavi Sinek", "definition": "Maggot tedavisinde kullanılan böcek. Yara iyileştirme özellikleri vardır. Tropikal ve subtropikal bölgelerde yaygındır. Özellikler: Yara temizleme, antimikrobiyal.", "components": ["Proteolitik enzimler", "Antimikrobiyal peptidler"], "usage": "Maggot tedavisi, yara temizleme", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["White-headed blow fly", "Mouche à tête blanche", "Mosca de cabeza blanca"]},
    {"latinName": "Chrysomya putoria", "turkishName": "Pis Mavi Sinek", "definition": "Maggot tedavisinde kullanılan böcek. Yara temizleme özellikleri vardır. Tropikal bölgelerde yaygındır. Özellikler: Yara temizleme, antimikrobiyal.", "components": ["Proteolitik enzimler", "Antimikrobiyal peptidler"], "usage": "Maggot tedavisi, yara temizleme", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Tropical blow fly", "Mouche tropicale", "Mosca tropical"]},
    {"latinName": "Protophormia terraenovae", "turkishName": "Yeni Toprak Sineği", "definition": "Maggot tedavisinde kullanılan böcek. Yara iyileştirme özellikleri vardır. Kuzey Amerika ve Avrupa'da yaygındır. Özellikler: Yara temizleme, antimikrobiyal.", "components": ["Proteolitik enzimler", "Antimikrobiyal peptidler"], "usage": "Maggot tedavisi, yara temizleme", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Northern blow fly", "Mouche du nord", "Mosca del norte"]},
    # Daha fazla ipek böcekleri
    {"latinName": "Philosamia ricini", "turkishName": "Hint İpek Böceği", "definition": "İpek üretimi ve tıbbi araştırmalarda kullanılan böcek. İpek fibroin tıbbi uygulamalarda değerlendirilmektedir. Hindistan ve Asya'da yaygındır. Özellikler: İpek fibroin, yara iyileştirme, yüksek protein.", "components": ["Fibroin", "Serisin", "Proteinler"], "usage": "İpek fibroin yara örtüleri, doku mühendisliği, beslenme takviyesi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Eri silkworm", "Ver à soie éri", "Gusano de seda eri"]},
    {"latinName": "Antheraea yamamai", "turkishName": "Japon Tussah İpek Böceği", "definition": "İpek üretimi ve tıbbi araştırmalarda kullanılan böcek. İpek fibroin özellikleri araştırılmaktadır. Japonya ve Asya'da yaygındır. Özellikler: İpek fibroin, yara iyileştirme potansiyeli.", "components": ["Fibroin", "Serisin", "Proteinler"], "usage": "İpek fibroin araştırmaları, doku mühendisliği", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Japanese oak silkworm", "Ver à soie japonais", "Gusano de seda japonés"]},
    {"latinName": "Antheraea mylitta", "turkishName": "Hindistan Tussah İpek Böceği", "definition": "İpek üretimi ve tıbbi araştırmalarda kullanılan böcek. İpek fibroin tıbbi uygulamalarda değerlendirilmektedir. Hindistan'da yaygındır. Özellikler: İpek fibroin, yara iyileştirme, yüksek protein.", "components": ["Fibroin", "Serisin", "Proteinler"], "usage": "İpek fibroin yara örtüleri, doku mühendisliği, beslenme takviyesi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Indian tussah silkworm", "Ver à soie indien", "Gusano de seda indio"]},
    {"latinName": "Antheraea assamensis", "turkishName": "Assam İpek Böceği", "definition": "İpek üretimi ve tıbbi araştırmalarda kullanılan böcek. İpek fibroin tıbbi uygulamalarda değerlendirilmektedir. Hindistan'da yaygındır. Özellikler: İpek fibroin, yara iyileştirme, yüksek protein.", "components": ["Fibroin", "Serisin", "Proteinler"], "usage": "İpek fibroin yara örtüleri, doku mühendisliği, beslenme takviyesi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Assam silkworm", "Ver à soie d'Assam", "Gusano de seda de Assam"]},
    {"latinName": "Antheraea frithi", "turkishName": "Frith İpek Böceği", "definition": "İpek üretimi ve tıbbi araştırmalarda kullanılan böcek. İpek fibroin özellikleri araştırılmaktadır. Asya'da yaygındır. Özellikler: İpek fibroin, yara iyileştirme potansiyeli.", "components": ["Fibroin", "Serisin", "Proteinler"], "usage": "İpek fibroin araştırmaları, doku mühendisliği", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Yara dokusu"], "synonyms": ["Frith silkworm", "Ver à soie Frith", "Gusano de seda Frith"]},
    # Daha fazla arı türleri
    {"latinName": "Apis dorsata", "turkishName": "Dev Bal Arısı", "definition": "Bal ve propolis üretimi ile tıbbi kullanımı olan böcek. Apiterapi alanında kullanılmaktadır. Asya'da yaygındır. Özellikler: Bal, propolis, apiterapi.", "components": ["Bal", "Propolis", "Balmumu"], "usage": "Apiterapi, bal üretimi, propolis", "sideEffects": ["Alerjik reaksiyon (arı sokması)"], "interactions": ["Apiterapi preparatları"], "synonyms": ["Giant honey bee", "Abeille géante", "Abeja gigante"]},
    {"latinName": "Apis florea", "turkishName": "Küçük Bal Arısı", "definition": "Bal ve propolis üretimi ile tıbbi kullanımı olan böcek. Apiterapi alanında kullanılmaktadır. Asya'da yaygındır. Özellikler: Bal, propolis, apiterapi.", "components": ["Bal", "Propolis", "Balmumu"], "usage": "Apiterapi, bal üretimi, propolis", "sideEffects": ["Alerjik reaksiyon (arı sokması)"], "interactions": ["Apiterapi preparatları"], "synonyms": ["Dwarf honey bee", "Abeille naine", "Abeja enana"]},
    {"latinName": "Apis laboriosa", "turkishName": "Çalışkan Bal Arısı", "definition": "Bal ve propolis üretimi ile tıbbi kullanımı olan böcek. Apiterapi alanında kullanılmaktadır. Himalaya bölgesinde yaygındır. Özellikler: Bal, propolis, apiterapi.", "components": ["Bal", "Propolis", "Balmumu"], "usage": "Apiterapi, bal üretimi, propolis", "sideEffects": ["Alerjik reaksiyon (arı sokması)"], "interactions": ["Apiterapi preparatları"], "synonyms": ["Himalayan honey bee", "Abeille de l'Himalaya", "Abeja del Himalaya"]},
    {"latinName": "Bombus impatiens", "turkishName": "Sabırsız Bombus Arısı", "definition": "Polinasyon ve tıbbi araştırmalarda kullanılan böcek. Apiterapi alanında değerlendirilmektedir. Kuzey Amerika'da yaygındır. Özellikler: Polinasyon, apiterapi potansiyeli.", "components": ["Bal", "Polen"], "usage": "Polinasyon, apiterapi araştırmaları", "sideEffects": ["Alerjik reaksiyon (arı sokması)"], "interactions": ["Apiterapi preparatları"], "synonyms": ["Common eastern bumblebee", "Bourdon commun", "Abejorro común"]},
    {"latinName": "Bombus lucorum", "turkishName": "Beyaz Bombus Arısı", "definition": "Polinasyon ve tıbbi araştırmalarda kullanılan böcek. Apiterapi alanında değerlendirilmektedir. Avrupa'da yaygındır. Özellikler: Polinasyon, apiterapi potansiyeli.", "components": ["Bal", "Polen"], "usage": "Polinasyon, apiterapi araştırmaları", "sideEffects": ["Alerjik reaksiyon (arı sokması)"], "interactions": ["Apiterapi preparatları"], "synonyms": ["White-tailed bumblebee", "Bourdon à queue blanche", "Abejorro de cola blanca"]},
    # Daha fazla geleneksel tıp böcekleri
    {"latinName": "Polyphaga plancyi", "turkishName": "Plancy Hamamböceği", "definition": "Geleneksel Çin tıbbında kullanılan böcek. Antitümör özellikleri araştırılmaktadır. Çin'de yaygındır. Özellikler: Antitümör, geleneksel tıp.", "components": ["Proteinler", "Kitin", "Tıbbi bileşikler"], "usage": "Geleneksel Çin tıbbı, antitümör araştırmaları", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Plancy cockroach", "Blatte Plancy", "Cucaracha Plancy"]},
    {"latinName": "Opisthoplatia orientalis", "turkishName": "Doğu Opisthoplatia", "definition": "Geleneksel tıpta kullanılan böcek. Tıbbi özellikleri araştırılmaktadır. Asya'da yaygındır. Özellikler: Geleneksel tıp, yüksek protein.", "components": ["Proteinler", "Kitin"], "usage": "Geleneksel tıp, tıbbi araştırmalar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Oriental opisthoplatia", "Opisthoplatia orientale", "Opisthoplatia oriental"]},
    {"latinName": "Eupolyphaga sinensis", "turkishName": "Çin Hamamböceği", "definition": "Geleneksel Çin tıbbında yaygın olarak kullanılan böcek. Antitümör, antienflamatuar ve analjezik özellikleri vardır. Çin ve Asya'da yaygındır. Özellikler: Antitümör, antienflamatuar, analjezik, geleneksel tıp.", "components": ["Proteinler", "Kitin", "Tıbbi bileşikler", "Antimikrobiyal peptidler"], "usage": "Geleneksel Çin tıbbı, antitümör tedavisi, antienflamatuar, ağrı kesici, yara iyileştirme", "sideEffects": ["Alerjik reaksiyon (nadir)", "Mide rahatsızlığı (yüksek dozda)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Chinese cockroach", "Blatte chinoise", "Cucaracha china"]},
    # Daha fazla model organizma böcekler
    {"latinName": "Drosophila simulans", "turkishName": "Simüle Meyve Sineği", "definition": "Genetik ve tıbbi araştırmalarda kullanılan model organizma. İnsan hastalıklarının araştırılmasında önemli rol oynar. Dünya genelinde, meyve ve sebzelerde yaygındır. Özellikler: Model organizma, hızlı üreme, genetik manipülasyon kolaylığı.", "components": ["Proteinler", "Genetik materyal", "Enzimler"], "usage": "Genetik araştırmalar, hastalık modelleri, ilaç geliştirme", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar", "İlaç testleri"], "synonyms": ["Simulated fruit fly", "Mouche simulée", "Mosca simulada"]},
    {"latinName": "Drosophila yakuba", "turkishName": "Yakuba Meyve Sineği", "definition": "Genetik ve tıbbi araştırmalarda kullanılan model organizma. İnsan hastalıklarının araştırılmasında önemli rol oynar. Afrika'da yaygındır. Özellikler: Model organizma, hızlı üreme.", "components": ["Proteinler", "Genetik materyal", "Enzimler"], "usage": "Genetik araştırmalar, hastalık modelleri, ilaç geliştirme", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Yakuba fruit fly", "Mouche Yakuba", "Mosca Yakuba"]},
    {"latinName": "Drosophila pseudoobscura", "turkishName": "Sahte Karanlık Meyve Sineği", "definition": "Genetik ve tıbbi araştırmalarda kullanılan model organizma. İnsan hastalıklarının araştırılmasında önemli rol oynar. Kuzey Amerika'da yaygındır. Özellikler: Model organizma, hızlı üreme.", "components": ["Proteinler", "Genetik materyal", "Enzimler"], "usage": "Genetik araştırmalar, hastalık modelleri, ilaç geliştirme", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Pseudoobscure fruit fly", "Mouche pseudo-obscure", "Mosca pseudooscura"]},
    {"latinName": "Drosophila sechellia", "turkishName": "Seychelles Meyve Sineği", "definition": "Genetik ve tıbbi araştırmalarda kullanılan model organizma. İnsan hastalıklarının araştırılmasında önemli rol oynar. Seychelles'de yaygındır. Özellikler: Model organizma, hızlı üreme.", "components": ["Proteinler", "Genetik materyal", "Enzimler"], "usage": "Genetik araştırmalar, hastalık modelleri, ilaç geliştirme", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Seychelles fruit fly", "Mouche des Seychelles", "Mosca de Seychelles"]},
    {"latinName": "Drosophila erecta", "turkishName": "Dik Meyve Sineği", "definition": "Genetik ve tıbbi araştırmalarda kullanılan model organizma. İnsan hastalıklarının araştırılmasında önemli rol oynar. Afrika'da yaygındır. Özellikler: Model organizma, hızlı üreme.", "components": ["Proteinler", "Genetik materyal", "Enzimler"], "usage": "Genetik araştırmalar, hastalık modelleri, ilaç geliştirme", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Erect fruit fly", "Mouche dressée", "Mosca erecta"]},
    # Daha fazla çekirge türleri
    {"latinName": "Anacridium aegyptium", "turkishName": "Mısır Çekirgesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Akdeniz bölgesinde yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Egyptian grasshopper", "Criquet égyptien", "Langosta egipcia"]},
    {"latinName": "Dociostaurus maroccanus", "turkishName": "Fas Çekirgesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Akdeniz bölgesinde yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%58-68)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Moroccan locust", "Criquet marocain", "Langosta marroquí"]},
    {"latinName": "Melanoplus differentialis", "turkishName": "Farklı Çayır Çekirgesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Kuzey Amerika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%60-70)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Differential grasshopper", "Criquet différentiel", "Langosta diferencial"]},
    {"latinName": "Melanoplus femurrubrum", "turkishName": "Kırmızı Bacaklı Çayır Çekirgesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Kuzey Amerika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%58-68)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Red-legged grasshopper", "Criquet à pattes rouges", "Langosta de patas rojas"]},
    {"latinName": "Melanoplus sanguinipes", "turkishName": "Kanlı Ayaklı Çayır Çekirgesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Kuzey Amerika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%60-70)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Migratory grasshopper", "Criquet migrateur", "Langosta migratoria"]},
    # Daha fazla hamamböcekleri
    {"latinName": "Supella longipalpa", "turkishName": "Kahverengi Çizgili Hamamböceği", "definition": "Tıbbi araştırmalarda kullanılan böcek. Antimikrobiyal özellikleri araştırılmaktadır. Dünya genelinde, özellikle sıcak bölgelerde yaygındır. Özellikler: Antimikrobiyal, yüksek protein.", "components": ["Proteinler", "Kitin", "Antimikrobiyal peptidler"], "usage": "Tıbbi araştırmalar, antimikrobiyal çalışmalar, protein kaynağı", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Brown-banded cockroach", "Blatte à bandes brunes", "Cucaracha de bandas marrones"]},
    {"latinName": "Nauphoeta cinerea", "turkishName": "Gri Hamamböceği", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Antimikrobiyal özellikleri araştırılmaktadır. Tropikal bölgelerde yaygındır. Özellikler: Antimikrobiyal, model organizma, yüksek protein.", "components": ["Proteinler", "Kitin", "Antimikrobiyal peptidler"], "usage": "Tıbbi araştırmalar, model organizma, antimikrobiyal çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Bilinmeyen"], "synonyms": ["Lobster cockroach", "Blatte grise", "Cucaracha gris"]},
    {"latinName": "Gromphadorhina portentosa", "turkishName": "Hisseden Hamamböceği", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Antimikrobiyal özellikleri araştırılmaktadır. Madagaskar'da yaygındır. Özellikler: Antimikrobiyal, model organizma, yüksek protein.", "components": ["Proteinler", "Kitin", "Antimikrobiyal peptidler"], "usage": "Tıbbi araştırmalar, model organizma, antimikrobiyal çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Bilinmeyen"], "synonyms": ["Madagascar hissing cockroach", "Blatte sifflante", "Cucaracha silbante"]},
    {"latinName": "Blaberus discoidalis", "turkishName": "Disk Hamamböceği", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Antimikrobiyal özellikleri araştırılmaktadır. Orta ve Güney Amerika'da yaygındır. Özellikler: Antimikrobiyal, model organizma, yüksek protein.", "components": ["Proteinler", "Kitin", "Antimikrobiyal peptidler"], "usage": "Tıbbi araştırmalar, model organizma, antimikrobiyal çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Bilinmeyen"], "synonyms": ["Discoid cockroach", "Blatte discoïde", "Cucaracha discoide"]},
    {"latinName": "Blaberus giganteus", "turkishName": "Dev Hamamböceği", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Antimikrobiyal özellikleri araştırılmaktadır. Orta ve Güney Amerika'da yaygındır. Özellikler: Antimikrobiyal, model organizma, yüksek protein, büyük boyut.", "components": ["Proteinler", "Kitin", "Antimikrobiyal peptidler"], "usage": "Tıbbi araştırmalar, model organizma, antimikrobiyal çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Bilinmeyen"], "synonyms": ["Giant cockroach", "Blatte géante", "Cucaracha gigante"]},
    # Daha fazla böcek türleri (90'a tamamla)
    {"latinName": "Rhynchophorus ferrugineus", "turkishName": "Kırmızı Palmiye Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Tropikal bölgelerde, palmiye ağaçlarında yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Red palm weevil", "Charançon rouge", "Gorgojo rojo"]},
    {"latinName": "Oryctes rhinoceros", "turkishName": "Gergedan Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Tropikal bölgelerde yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Rhinoceros beetle", "Scarabée rhinocéros", "Escarabajo rinoceronte"]},
    {"latinName": "Allomyrina dichotoma", "turkishName": "Çift Çatallı Böcek", "definition": "Geleneksel tıpta kullanılan böcek. Tıbbi özellikleri araştırılmaktadır. Asya'da yaygındır. Özellikler: Geleneksel tıp, yüksek protein.", "components": ["Proteinler", "Kitin"], "usage": "Geleneksel tıp, tıbbi araştırmalar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Japanese rhinoceros beetle", "Scarabée japonais", "Escarabajo japonés"]},
    {"latinName": "Protaetia brevitarsis", "turkishName": "Kısa Ayaklı Böcek", "definition": "Geleneksel tıpta kullanılan böcek. Tıbbi özellikleri araştırılmaktadır. Asya'da yaygındır. Özellikler: Geleneksel tıp, yüksek protein.", "components": ["Proteinler", "Kitin"], "usage": "Geleneksel tıp, tıbbi araştırmalar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Short-legged beetle", "Scarabée à pattes courtes", "Escarabajo de patas cortas"]},
    {"latinName": "Holotrichia parallela", "turkishName": "Paralel Beyaz Böcek", "definition": "Geleneksel tıpta kullanılan böcek. Tıbbi özellikleri araştırılmaktadır. Asya'da yaygındır. Özellikler: Geleneksel tıp, yüksek protein.", "components": ["Proteinler", "Kitin"], "usage": "Geleneksel tıp, tıbbi araştırmalar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Parallel white grub", "Ver blanc parallèle", "Gusano blanco paralelo"]},
    # Daha fazla böcek (90'a tamamla - kalan 30+ böcek)
    {"latinName": "Anomala cuprea", "turkishName": "Bakır Böcek", "definition": "Geleneksel tıpta kullanılan böcek. Tıbbi özellikleri araştırılmaktadır. Asya'da yaygındır. Özellikler: Geleneksel tıp, yüksek protein.", "components": ["Proteinler", "Kitin"], "usage": "Geleneksel tıp, tıbbi araştırmalar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Copper chafer", "Hanneton cuivré", "Escarabajo de cobre"]},
    {"latinName": "Popillia japonica", "turkishName": "Japon Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Japonya ve Kuzey Amerika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Japanese beetle", "Hanneton japonais", "Escarabajo japonés"]},
    {"latinName": "Anoplophora glabripennis", "turkishName": "Düz Boynuzlu Böcek", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Asya'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Asian longhorned beetle", "Longicorne asiatique", "Escarabajo de cuernos largos"]},
    {"latinName": "Monochamus alternatus", "turkishName": "Alternatif Böcek", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Asya'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Japanese pine sawyer", "Longicorne japonais", "Escarabajo japonés"]},
    {"latinName": "Apriona germari", "turkishName": "Germar Böceği", "definition": "Geleneksel tıpta kullanılan böcek. Tıbbi özellikleri araştırılmaktadır. Asya'da yaygındır. Özellikler: Geleneksel tıp, yüksek protein.", "components": ["Proteinler", "Kitin"], "usage": "Geleneksel tıp, tıbbi araştırmalar", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Geleneksel tıp preparatları"], "synonyms": ["Germar longhorned beetle", "Longicorne Germar", "Escarabajo Germar"]},
    # Daha fazla böcek (90'a tamamla)
    {"latinName": "Cerambyx cerdo", "turkishName": "Büyük Meşe Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Avrupa'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Great capricorn beetle", "Capricorne géant", "Escarabajo capricornio"]},
    {"latinName": "Prionus coriarius", "turkishName": "Deri Böceği", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Avrupa'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Sawyer beetle", "Scieur", "Escarabajo serrador"]},
    {"latinName": "Ergates faber", "turkishName": "Demirci Böcek", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Avrupa'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Carpenter beetle", "Charpentier", "Escarabajo carpintero"]},
    {"latinName": "Aegosoma scabricorne", "turkishName": "Kaba Boynuzlu Böcek", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Asya'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Rough-horned beetle", "Longicorne rugueux", "Escarabajo de cuernos rugosos"]},
    {"latinName": "Batocera rufomaculata", "turkishName": "Kırmızı Benekli Böcek", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Asya'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Red-spotted longhorn", "Longicorne à taches rouges", "Escarabajo de manchas rojas"]},
    # Daha fazla böcek (90'a tamamla - son 20+ böcek)
    {"latinName": "Ostrinia nubilalis", "turkishName": "Avrupa Mısır Kurdu", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Avrupa ve Kuzey Amerika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["European corn borer", "Pyrale du maïs", "Gusano del maíz"]},
    {"latinName": "Helicoverpa armigera", "turkishName": "Pamuk Kurdu", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Dünya genelinde yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Cotton bollworm", "Noctuelle de la tomate", "Gusano del algodón"]},
    {"latinName": "Spodoptera frugiperda", "turkishName": "Sonbahar Ordusu Kurdu", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Amerika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Fall armyworm", "Noctuelle d'automne", "Gusano del otoño"]},
    {"latinName": "Agrotis ipsilon", "turkishName": "Kara Kesici Kurdu", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Dünya genelinde yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Black cutworm", "Noctuelle noire", "Gusano negro"]},
    {"latinName": "Mythimna unipuncta", "turkishName": "Tek Noktalı Kurdu", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Amerika'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["True armyworm", "Noctuelle vraie", "Gusano verdadero"]},
    # Daha fazla böcek (90'a tamamla - son 15+ böcek)
    {"latinName": "Plutella xylostella", "turkishName": "Lahana Güvesi", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Genetik araştırmalarda önemli rol oynar. Dünya genelinde yaygındır. Özellikler: Model organizma, yüksek protein.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Tıbbi araştırmalar, model organizma, genetik çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Diamondback moth", "Teigne des crucifères", "Polilla de la col"]},
    {"latinName": "Cydia pomonella", "turkishName": "Elma Güvesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Dünya genelinde yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Codling moth", "Carpocapse", "Polilla del manzano"]},
    {"latinName": "Grapholita molesta", "turkishName": "Doğu Şeftali Güvesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Dünya genelinde yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Oriental fruit moth", "Tordeuse orientale", "Polilla oriental"]},
    {"latinName": "Ephestia kuehniella", "turkishName": "Akdeniz Un Güvesi", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Genetik araştırmalarda önemli rol oynar. Dünya genelinde, tahıl depolarında yaygındır. Özellikler: Model organizma, yüksek protein.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Tıbbi araştırmalar, model organizma, genetik çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Mediterranean flour moth", "Teigne méditerranéenne", "Polilla mediterránea"]},
    {"latinName": "Plodia interpunctella", "turkishName": "Hint Un Güvesi", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Genetik araştırmalarda önemli rol oynar. Dünya genelinde, tahıl depolarında yaygındır. Özellikler: Model organizma, yüksek protein.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Tıbbi araştırmalar, model organizma, genetik çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Indian meal moth", "Teigne indienne", "Polilla india"]},
    # Daha fazla böcek (90'a tamamla - son 10+ böcek)
    {"latinName": "Corcyra cephalonica", "turkishName": "Pirinç Güvesi", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Genetik araştırmalarda önemli rol oynar. Dünya genelinde, tahıl depolarında yaygındır. Özellikler: Model organizma, yüksek protein.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Tıbbi araştırmalar, model organizma, genetik çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Rice moth", "Teigne du riz", "Polilla del arroz"]},
    {"latinName": "Sitotroga cerealella", "turkishName": "Tahıl Güvesi", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Genetik araştırmalarda önemli rol oynar. Dünya genelinde, tahıl depolarında yaygındır. Özellikler: Model organizma, yüksek protein.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Tıbbi araştırmalar, model organizma, genetik çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Angoumois grain moth", "Teigne des grains", "Polilla de los granos"]},
    {"latinName": "Tineola bisselliella", "turkishName": "Güve", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Genetik araştırmalarda önemli rol oynar. Dünya genelinde yaygındır. Özellikler: Model organizma, yüksek protein.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Tıbbi araştırmalar, model organizma, genetik çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Clothes moth", "Teigne des vêtements", "Polilla de la ropa"]},
    {"latinName": "Tinea pellionella", "turkishName": "Kürk Güvesi", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Genetik araştırmalarda önemli rol oynar. Dünya genelinde yaygındır. Özellikler: Model organizma, yüksek protein.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Tıbbi araştırmalar, model organizma, genetik çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["Case-bearing clothes moth", "Teigne à fourreau", "Polilla con estuche"]},
    {"latinName": "Nemapogon granella", "turkishName": "Tahıl Nemapogon", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Genetik araştırmalarda önemli rol oynar. Dünya genelinde, tahıl depolarında yaygındır. Özellikler: Model organizma, yüksek protein.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Tıbbi araştırmalar, model organizma, genetik çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Genetik araştırmalar"], "synonyms": ["European grain moth", "Teigne européenne", "Polilla europea"]},
    # Son 5+ böcek (90'a tamamla)
    {"latinName": "Achroia grisella", "turkishName": "Küçük Balmumu Güvesi", "definition": "Tıbbi araştırmalarda kullanılan böcek. Antimikrobiyal özellikleri araştırılmaktadır. Dünya genelinde, arı kovanlarında yaygındır. Özellikler: Antimikrobiyal potansiyel.", "components": ["Proteinler", "Lipitler", "Kitin"], "usage": "Tıbbi araştırmalar, antimikrobiyal çalışmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Bakteriler"], "synonyms": ["Lesser wax moth", "Petite teigne", "Polilla pequeña"]},
    {"latinName": "Galleria mellonella", "turkishName": "Büyük Balmumu Güvesi", "definition": "Tıbbi araştırmalarda model organizma olarak kullanılan böcek. Antibakteriyel ve antifungal özellikleri araştırılmaktadır. Dünya genelinde, arı kovanlarında yaygındır. Özellikler: Model organizma, antimikrobiyal, antifungal.", "components": ["Proteinler", "Lipitler", "Kitin", "Antimikrobiyal peptidler"], "usage": "Tıbbi araştırmalar, model organizma, antibakteriyel çalışmalar, antifungal araştırmalar", "sideEffects": ["Araştırma amaçlı kullanım"], "interactions": ["Bakteriler", "Mantarlar"], "synonyms": ["Greater wax moth", "Fausse teigne", "Polilla de la cera"]},
    {"latinName": "Achaea janata", "turkishName": "Janata Güvesi", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Asya'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Castor semilooper", "Boucleur du ricin", "Gusano del ricino"]},
    {"latinName": "Spodoptera litura", "turkishName": "Tütün Kurdu", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Gıda endüstrisinde değerlendirilmektedir. Asya'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%55-65)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, gıda endüstrisi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Tobacco cutworm", "Noctuelle du tabac", "Gusano del tabaco"]},
    {"latinName": "Mamestra brassicae", "turkishName": "Lahana Kurdu", "definition": "Yüksek protein içeriği ile beslenme araştırmalarında kullanılan böcek. Entomoterapi alanında incelenmektedir. Avrupa ve Asya'da yaygındır. Özellikler: Yüksek protein, sürdürülebilir kaynak.", "components": ["Proteinler (%50-60)", "Lipitler", "Kitin"], "usage": "Beslenme takviyesi, protein kaynağı, entomoterapi", "sideEffects": ["Alerjik reaksiyon (nadir)"], "interactions": ["Bilinmeyen"], "synonyms": ["Cabbage moth", "Noctuelle du chou", "Gusano de la col"]},
]

if __name__ == "__main__":
    data = load_data()
    next_id = get_next_id(data)
    existing = get_existing_names(data, 'insect')
    
    print(f"Mevcut böcek verisi: {len([item for item in data if item.get('category') == 'insect'])}")
    print(f"Sonraki ID: {next_id}\n")
    
    new_items = []
    current_id = next_id
    
    for insect in insects_data:
        if insect['latinName'].lower() not in existing:
            # Location ve properties bilgilerini definition'a ekle
            definition = insect["definition"]
            if "location" in insect and "properties" in insect:
                definition += f" Bulunduğu yerler: {insect['location']}. Özellikler: {insect['properties']}."
            
            new_items.append({
                "id": str(current_id),
                "latinName": insect["latinName"],
                "turkishName": insect["turkishName"],
                "category": "insect",
                "definition": definition,
                "components": insect["components"] if isinstance(insect["components"], list) else [insect["components"]],
                "usage": insect["usage"],
                "sideEffects": insect["sideEffects"] if isinstance(insect["sideEffects"], list) else [insect["sideEffects"]],
                "interactions": insect["interactions"] if isinstance(insect["interactions"], list) else [insect["interactions"]],
                "synonyms": insect["synonyms"] if isinstance(insect["synonyms"], list) else [insect["synonyms"]],
                "isBookmarked": False
            })
            current_id += 1
            if len(new_items) >= 90:
                break
    
    if new_items:
        data.extend(new_items)
        save_data(data)
        print(f"✅ {len(new_items)} böcek terimi eklendi!")
        print(f"Yeni toplam böcek verisi: {len([item for item in data if item.get('category') == 'insect'])}")
        print(f"Toplam veri: {len(data)}")
    else:
        print("⚠️ Yeni veri eklenmedi (tüm veriler zaten mevcut olabilir)")
