// Massive terim üretme scripti - 10,000 terime ulaşmak için
const { initializeApp } = require("firebase/app");
const {
  getFirestore,
  collection,
  getDocs,
  writeBatch,
  doc,
} = require("firebase/firestore");

const firebaseConfig = {
  apiKey: "AIzaSyCETgJvY3XPdHF0gVQhdsEVd9UIEwYyWbw",
  authDomain: "pharmadict-66629.firebaseapp.com",
  projectId: "pharmadict-66629",
  storageBucket: "pharmadict-66629.firebasestorage.app",
  messagingSenderId: "55210435202",
  appId: "1:55210435202:web:cffc317dfdd7dbbcac8a9b",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const TermCategory = {
  DRUG: "İlaçlar",
  PLANT: "Bitkiler",
  VITAMIN: "Vitaminler",
  MINERAL: "Mineraller",
  DISEASE: "Hastalıklar",
  INSECT: "Böcekler",
  COMPONENT: "Bileşenler",
  ANATOMY: "Anatomi",
};

const createTerm = (latin, turkish, category, def) => ({
  latinName: latin,
  turkishName: turkish,
  category,
  definition: def,
  components: [],
  relatedTerms: [],
  etymology: "",
  usage: "",
  sideEffects: [],
  dosage: "",
  contraindications: [],
  interactions: [],
  synonyms: [],
});
// İLAÇLAR - Kapsamlı liste
const generateDrugs = () => {
  const drugList = [
    // Antibiyotikler
    ["Azlocillin", "Azlosilin", "Antipsödomonal penisilin"],
    ["Mezlocillin", "Mezlosilin", "Antipsödomonal penisilin"],
    ["Carbenicillin", "Karbenisillin", "Antipsödomonal penisilin"],
    ["Cefoperazone", "Sefoperazon", "3. kuşak sefalosporin"],
    ["Cefpirome", "Sefpirom", "4. kuşak sefalosporin"],
    ["Cefozopran", "Sefozopran", "4. kuşak sefalosporin"],
    ["Cefiderocol", "Sefiderokol", "Siderofor sefalosporin"],
    ["Biapenem", "Biapenem", "Karbapenem"],
    ["Panipenem", "Panipenem", "Karbapenem"],
    ["Faropenem", "Faropenem", "Penem"],
    ["Spectinomycin", "Spektinomisin", "Aminosiklitol"],
    ["Sisomicin", "Sisomisin", "Aminoglikozid"],
    ["Netilmicin", "Netilmisin", "Aminoglikozid"],
    ["Isepamicin", "İsepamisin", "Aminoglikozid"],
    ["Arbekacin", "Arbekasin", "Aminoglikozid"],
    ["Dirithromycin", "Diritromisin", "Makrolid"],
    ["Roxithromycin", "Roksitromisin", "Makrolid"],
    ["Spiramycin", "Spiramisin", "Makrolid"],
    ["Josamycin", "Josamisin", "Makrolid"],
    ["Midecamycin", "Midekamisin", "Makrolid"],
    ["Telithromycin", "Telitromisin", "Ketolid"],
    ["Solithromycin", "Solitromisin", "Floroketolid"],
    ["Sarecycline", "Saresiklin", "Tetrasiklin"],
    ["Lymecycline", "Limesiklin", "Tetrasiklin"],
    ["Meclocycline", "Meklosiklin", "Tetrasiklin"],
    ["Nadifloxacin", "Nadifloksasin", "Topikal florokinolon"],
    ["Balofloxacin", "Balofloksasin", "Florokinolon"],
    ["Prulifloxacin", "Prulifloksasin", "Florokinolon"],
    ["Sitafloxacin", "Sitafloksasin", "Florokinolon"],
    ["Garenoxacin", "Garenoksasin", "Florokinolon"],
    ["Ramoplanin", "Ramoplanin", "Lipoglikodepsipeptid"],
    ["Surotomycin", "Surotomisin", "Lipopeptid"],
    ["Cadazolid", "Kadazolid", "Oksazolidinon-kinolonon hibrit"],
    ["Radezolid", "Radezolid", "Oksazolidinon"],
    ["Contezolid", "Kontezolid", "Oksazolidinon"],
    ["Iclaprim", "İklaprim", "DHFR inhibitörü"],
    ["Gepotidacin", "Gepotidacin", "Triazaacenaftilen"],
    ["Zoliflodacin", "Zoliflodacin", "Spiropirimidintrion"],
    // Antiviral ilaçlar
    ["Adefovir", "Adefovir", "HBV nükleotid analoğu"],
    ["Clevudine", "Klevudin", "HBV nükleozid analoğu"],
    ["Telbivudine", "Telbivudin", "HBV nükleozid analoğu"],
    ["Besifovir", "Besifovir", "HBV nükleotid analoğu"],
    ["Beclabuvir", "Beklabuvir", "HCV NS5B inhibitörü"],
    ["Dasabuvir", "Dasabuvir", "HCV NS5B inhibitörü"],
    ["Ombitasvir", "Ombitasvir", "HCV NS5A inhibitörü"],
    ["Paritaprevir", "Paritaprevir", "HCV NS3/4A inhibitörü"],
    ["Asunaprevir", "Asunaprevir", "HCV NS3 inhibitörü"],
    ["Simeprevir", "Simeprevir", "HCV NS3/4A inhibitörü"],
    ["Vaniprevir", "Vaniprevir", "HCV NS3/4A inhibitörü"],
    ["Voxilaprevir", "Voksilaprevir", "HCV NS3/4A inhibitörü"],
    ["Ravidasvir", "Ravidasvir", "HCV NS5A inhibitörü"],
    ["Odalasvir", "Odalasvir", "HCV NS5A inhibitörü"],
    ["Ruzasvir", "Ruzasvir", "HCV NS5A inhibitörü"],
    ["Uprifosbuvir", "Uprifosbuvir", "HCV NS5B inhibitörü"],
    ["Amenamevir", "Amenamevir", "Helikaz-primaz inhibitörü"],
    ["Pritelivir", "Pritelivir", "Helikaz-primaz inhibitörü"],
    ["Brincidofovir", "Brinsidofovir", "Geniş spektrum antiviral"],
    ["Filociclovir", "Filosiklovir", "CMV antiviral"],
    ["Cyclopropavir", "Siklopropavir", "CMV antiviral"],
    ["Tomeglovir", "Tomeglovir", "CMV terminaz inhibitörü"],
    ["Favipiravir", "Favipiravir", "RNA polimeraz inhibitörü"],
    ["Molnupiravir", "Molnupiravir", "RNA mutajen"],
    ["Nirmatrelvir", "Nirmatrelvir", "SARS-CoV-2 proteaz inhibitörü"],
    ["Ensitrelvir", "Ensitrelvir", "SARS-CoV-2 proteaz inhibitörü"],
    ["Remdesivir", "Remdesivir", "RNA polimeraz inhibitörü"],
    // Antifungal ilaçlar
    ["Ravuconazole", "Ravukonazol", "Triazol antifungal"],
    ["Albaconazole", "Albakonazol", "Triazol antifungal"],
    ["Fosravuconazole", "Fosravukonazol", "Triazol ön ilacı"],
    ["Oteseconazole", "Otesekonazol", "Tetrazol antifungal"],
    ["Ibrexafungerp", "İbreksafungerp", "Triterpenoid antifungal"],
    ["Fosmanogepix", "Fosmanogepiks", "Gwt1 inhibitörü"],
    ["Olorofim", "Olorofim", "DHODH inhibitörü"],
    ["Opelconazole", "Opelkonazol", "İnhale triazol"],
    // Antiparaziter ilaçlar
    ["Halofantrine", "Halofantrin", "Antimalaryal"],
    ["Amodiaquine", "Amodiakin", "Antimalaryal"],
    ["Pyronaridine", "Pironaridine", "Antimalaryal"],
    ["Ferroquine", "Ferrokin", "Antimalaryal"],
    ["Arterolane", "Arterolan", "Sentetik endoperoksit"],
    ["Cipargamin", "Sipargamin", "Spiroindolon antimalaryal"],
    ["Ganaplacide", "Ganaplasid", "İmidazolopiperazin antimalaryal"],
    ["Artefenomel", "Artefenomel", "Ozonid antimalaryal"],
    ["Fexinidazole", "Feksinidazol", "Trypanosomiasis"],
    ["Acoziborole", "Akoziborol", "Trypanosomiasis"],
    ["Moxidectin", "Moksidektin", "Antihelmintik"],
    ["Emodepside", "Emodepsid", "Antihelmintik"],
    ["Tribendimidine", "Tribendimidine", "Antihelmintik"],
    ["Oxantel", "Oksantel", "Antihelmintik"],
    // Onkoloji ilaçları
    ["Venetoclax", "Venetoklaks", "BCL-2 inhibitörü"],
    ["Navitoclax", "Navitoklaks", "BCL-2/BCL-xL inhibitörü"],
    ["Obatoclax", "Obatoklaks", "Pan-BCL-2 inhibitörü"],
    ["Idelalisib", "İdelalisib", "PI3K delta inhibitörü"],
    ["Copanlisib", "Kopanlisib", "PI3K alfa/delta inhibitörü"],
    ["Duvelisib", "Duvelisib", "PI3K delta/gama inhibitörü"],
    ["Umbralisib", "Umbralisib", "PI3K delta/CK1 inhibitörü"],
    ["Alpelisib", "Alpelisib", "PI3K alfa inhibitörü"],
    ["Ibrutinib", "İbrutinib", "BTK inhibitörü"],
    ["Acalabrutinib", "Akalabrutinib", "BTK inhibitörü"],
    ["Zanubrutinib", "Zanubrutinib", "BTK inhibitörü"],
    ["Pirtobrutinib", "Pirtobrutinib", "Non-kovalent BTK inhibitörü"],
    ["Orelabrutinib", "Orelabrutinib", "BTK inhibitörü"],
    ["Tirabrutinib", "Tirabrutinib", "BTK inhibitörü"],
    ["Selinexor", "Selineksor", "XPO1 inhibitörü"],
    ["Eltanexor", "Eltaneksor", "XPO1 inhibitörü"],
    ["Panobinostat", "Panobinostat", "HDAC inhibitörü"],
    ["Vorinostat", "Vorinostat", "HDAC inhibitörü"],
    ["Romidepsin", "Romidepsin", "HDAC inhibitörü"],
    ["Belinostat", "Belinostat", "HDAC inhibitörü"],
    ["Tucidinostat", "Tusidinostat", "HDAC inhibitörü"],
    ["Enasidenib", "Enasidenib", "IDH2 inhibitörü"],
    ["Ivosidenib", "İvosidenib", "IDH1 inhibitörü"],
    ["Olutasidenib", "Olutasidenib", "IDH1 inhibitörü"],
    ["Vorasidenib", "Vorasidenib", "IDH1/2 inhibitörü"],
    ["Glasdegib", "Glasdegib", "Hedgehog inhibitörü"],
    ["Sonidegib", "Sonidegib", "Hedgehog inhibitörü"],
    ["Vismodegib", "Vismodegib", "Hedgehog inhibitörü"],
    ["Taladegib", "Taladegib", "Hedgehog inhibitörü"],
    ["Gilteritinib", "Gilteritinib", "FLT3 inhibitörü"],
    ["Midostaurin", "Midostaurin", "FLT3/KIT inhibitörü"],
    ["Quizartinib", "Kizartinib", "FLT3 inhibitörü"],
    ["Crenolanib", "Krenolanib", "FLT3 inhibitörü"],
    ["Avapritinib", "Avapritinib", "KIT/PDGFRA inhibitörü"],
    ["Ripretinib", "Ripretinib", "KIT/PDGFRA inhibitörü"],
    ["Pexidartinib", "Peksidartinib", "CSF1R inhibitörü"],
    ["Vimseltinib", "Vimseltinib", "CSF1R inhibitörü"],
    ["Erdafitinib", "Erdafitinib", "FGFR inhibitörü"],
    ["Pemigatinib", "Pemigatinib", "FGFR inhibitörü"],
    ["Infigratinib", "İnfigratinib", "FGFR inhibitörü"],
    ["Futibatinib", "Futibatinib", "FGFR inhibitörü"],
    ["Derazantinib", "Derazantinib", "FGFR inhibitörü"],
    ["Entrectinib", "Entrektinib", "TRK/ROS1/ALK inhibitörü"],
    ["Larotrectinib", "Larotrektinib", "TRK inhibitörü"],
    ["Selitrectinib", "Selitrektinib", "TRK inhibitörü"],
    ["Repotrectinib", "Repotrektinib", "TRK/ROS1/ALK inhibitörü"],
    ["Selpercatinib", "Selperkitinib", "RET inhibitörü"],
    ["Pralsetinib", "Pralsetinib", "RET inhibitörü"],
    ["Tepotinib", "Tepotinib", "MET inhibitörü"],
    ["Capmatinib", "Kapmatinib", "MET inhibitörü"],
    ["Savolitinib", "Savolitinib", "MET inhibitörü"],
    // Nöroloji ilaçları
    ["Cenobamate", "Senobamat", "Antiepileptik"],
    ["Fenfluramine", "Fenfluramin", "Dravet sendromu"],
    ["Stiripentol", "Stiripentol", "Dravet sendromu"],
    ["Cannabidiol", "Kannabidiol", "Epilepsi, CBD"],
    ["Ganaxolone", "Ganaksolon", "CDKL5 eksikliği"],
    ["Vigabatrin", "Vigabatrin", "İnfantil spazm"],
    ["Rufinamide", "Rufinamid", "Lennox-Gastaut"],
    ["Felbamate", "Felbamat", "Lennox-Gastaut"],
    ["Eslicarbazepine", "Eslikarbazepin", "Antiepileptik"],
    ["Retigabine", "Retigabin", "Potasyum kanal açıcı"],
    ["Perampanel", "Perampanel", "AMPA antagonisti"],
    ["Brivaracetam", "Brivarasetam", "SV2A ligandı"],
    ["Lacosamide", "Lakozamid", "Sodyum kanal modülatörü"],
    ["Safinamide", "Safinamid", "MAO-B inhibitörü, Parkinson"],
    ["Opicapone", "Opikapon", "COMT inhibitörü"],
    ["Istradefylline", "İstradefyllin", "Adenozin A2A antagonisti"],
    ["Pimavanserin", "Pimavanserin", "5-HT2A antagonisti"],
    ["Droxidopa", "Droksidopa", "Nörojenik hipotansiyon"],
    ["Edaravone", "Edaravon", "ALS, antioksidan"],
    ["Riluzole", "Riluzol", "ALS, glutamat modülatörü"],
    ["Tofersen", "Tofersen", "SOD1 ALS, antisense"],
    ["Nusinersen", "Nusinersen", "SMA, antisense"],
    ["Risdiplam", "Risdiplam", "SMA, SMN2 splicing modülatörü"],
    ["Eteplirsen", "Eteplirsen", "DMD, ekson atlama"],
    ["Golodirsen", "Golodirsen", "DMD, ekson atlama"],
    ["Viltolarsen", "Viltolarsen", "DMD, ekson atlama"],
    ["Casimersen", "Kasimersen", "DMD, ekson atlama"],
    ["Deflazacort", "Deflazakort", "DMD, kortikosteroid"],
    ["Siponimod", "Siponimod", "S1P modülatörü, MS"],
    ["Ozanimod", "Ozanimod", "S1P modülatörü, MS"],
    ["Ponesimod", "Ponesimod", "S1P modülatörü, MS"],
    ["Fingolimod", "Fingolimod", "S1P modülatörü, MS"],
    ["Dimethyl fumarate", "Dimetil Fumarat", "MS, Nrf2 aktivatörü"],
    ["Diroximel fumarate", "Diroksimelfumarat", "MS, fumarat"],
    ["Monomethyl fumarate", "Monometil Fumarat", "MS, fumarat"],
    ["Cladribine", "Kladribin", "MS, pürin analoğu"],
    ["Alemtuzumab", "Alemtuzumab", "MS, anti-CD52"],
    ["Ofatumumab", "Ofatumumab", "MS, anti-CD20"],
    ["Ublituximab", "Ublituksimab", "MS, anti-CD20"],
    ["Natalizumab", "Natalizumab", "MS, anti-integrin"],
    // Psikiyatri ilaçları
    ["Esketamine", "Esketamin", "Dirençli depresyon"],
    ["Brexanolone", "Breksanolon", "Postpartum depresyon"],
    ["Zuranolone", "Zuranolon", "Postpartum depresyon"],
    ["Cariprazine", "Kariprazin", "Şizofreni, bipolar"],
    ["Lumateperone", "Lumateperon", "Şizofreni, bipolar"],
    ["Valbenazine", "Valbenazin", "Tardif diskinezi"],
    ["Deutetrabenazine", "Dötetrabenazin", "Tardif diskinezi, Huntington"],
    ["Tetrabenazine", "Tetrabenazin", "Huntington kore"],
    ["Pitolisant", "Pitolisant", "Narkolepsi, H3 antagonist"],
    ["Solriamfetol", "Solriamfetol", "Narkolepsi, uyku apnesi"],
    ["Modafinil", "Modafinil", "Narkolepsi, uyanıklık"],
    ["Armodafinil", "Armodafinil", "Narkolepsi, uyanıklık"],
    // Kardiyovasküler ilaçlar
    ["Amiodarone", "Amiodaron", "Sınıf III antiaritmik"],
    ["Dronedarone", "Dronedaron", "Sınıf III antiaritmik"],
    ["Sotalol", "Sotalol", "Sınıf III antiaritmik"],
    ["Dofetilide", "Dofetilid", "Sınıf III antiaritmik"],
    ["Ibutilide", "İbutilid", "Sınıf III antiaritmik"],
    ["Flecainide", "Flekainid", "Sınıf IC antiaritmik"],
    ["Propafenone", "Propafenon", "Sınıf IC antiaritmik"],
    ["Quinidine", "Kinidin", "Sınıf IA antiaritmik"],
    ["Procainamide", "Prokainamid", "Sınıf IA antiaritmik"],
    ["Disopyramide", "Dizopiramid", "Sınıf IA antiaritmik"],
    ["Mexiletine", "Meksiletine", "Sınıf IB antiaritmik"],
    ["Adenosine", "Adenozin", "SVT tedavisi"],
    ["Digoxin", "Digoksin", "Kardiyak glikozid"],
    ["Ivabradine", "İvabradin", "If kanal inhibitörü"],
    ["Nitroglycerin", "Nitrogliserin", "Nitrat, anjina"],
    ["Isosorbide dinitrate", "İzosorbid Dinitrat", "Nitrat, anjina"],
    ["Isosorbide mononitrate", "İzosorbid Mononitrat", "Nitrat, anjina"],
    ["Hydralazine", "Hidralazin", "Direkt vazodilatör"],
    ["Minoxidil", "Minoksidil", "Direkt vazodilatör, saç"],
    ["Sodium nitroprusside", "Sodyum Nitroprusid", "IV vazodilatör"],
    ["Nesiritide", "Nesiritid", "BNP, kalp yetmezliği"],
    ["Alprostadil", "Alprostadil", "PGE1, ED, PDA"],
    ["Epoprostenol", "Epoprostenol", "Prostasiklin, PAH"],
    ["Iloprost", "İloprost", "Prostasiklin analoğu"],
    ["Treprostinil", "Treprostinil", "Prostasiklin analoğu"],
    ["Selexipag", "Seleksipag", "Prostasiklin reseptör agonisti"],
    ["Dobutamine", "Dobutamin", "Beta-1 agonist, inotrop"],
    ["Dopamine", "Dopamin", "Katekolamin, inotrop"],
    ["Milrinone", "Milrinon", "PDE3 inhibitörü, inotrop"],
    ["Levosimendan", "Levosimendan", "Kalsiyum duyarlaştırıcı"],
    ["Norepinephrine", "Norepinefrin", "Alfa agonist, vazopresör"],
    ["Epinephrine", "Epinefrin", "Katekolamin, anafilaksi"],
    ["Phenylephrine", "Fenilefrin", "Alfa-1 agonist"],
    ["Vasopressin", "Vazopressin", "ADH, vazopresör"],
    ["Angiotensin II", "Anjiyotensin II", "Vazopresör"],
    ["Midodrine", "Midodrin", "Oral alfa agonist"],
    ["Ranolazine", "Ranolazin", "Geç sodyum akımı inhibitörü"],
    ["Trimetazidine", "Trimetazidin", "Metabolik modülatör"],
    ["Nicorandil", "Nikorandil", "Potasyum kanal açıcı"],
    ["Sacubitril-valsartan", "Sakubitril-Valsartan", "ARNI"],
    ["Vericiguat", "Verisiguat", "sGC stimülatörü"],
    ["Omecamtiv mecarbil", "Omekamtiv Mekarbil", "Miyozin aktivatörü"],
    ["Bosentan", "Bosentan", "Endotelin antagonisti"],
    ["Ambrisentan", "Ambrisentan", "Endotelin antagonisti"],
    ["Macitentan", "Masitentan", "Endotelin antagonisti"],
    ["Riociguat", "Riosiguat", "sGC stimülatörü"],
    // Dermatolojik ilaçlar
    ["Tretinoin", "Tretinoin", "Retinoid, akne, yaşlanma"],
    ["Adapalene", "Adapalen", "Retinoid, akne"],
    ["Tazarotene", "Tazaroten", "Retinoid, psoriazis, akne"],
    ["Isotretinoin", "İzotretinoin", "Oral retinoid, şiddetli akne"],
    ["Acitretin", "Asitretin", "Oral retinoid, psoriazis"],
    ["Alitretinoin", "Alitretinoin", "Retinoid, el egzaması"],
    ["Benzoyl peroxide", "Benzoil Peroksit", "Akne, antibakteriyel"],
    ["Salicylic acid", "Salisilik Asit", "Keratolitik, akne"],
    ["Azelaic acid", "Azelaik Asit", "Akne, rozasea"],
    ["Calcipotriene", "Kalsipotriol", "D vitamini analoğu, psoriazis"],
    [
      "Tacrolimus topical",
      "Topikal Takrolimus",
      "Kalsinörin inhibitörü, egzama",
    ],
    ["Pimecrolimus", "Pimekrolimus", "Kalsinörin inhibitörü, egzama"],
    ["Crisaborole", "Krisaborol", "PDE4 inhibitörü, egzama"],
    ["Ruxolitinib topical", "Topikal Ruksolitinib", "JAK inhibitörü, egzama"],
    ["Clobetasol", "Klobetazol", "Süper potens kortikosteroid"],
    ["Halobetasol", "Halobetazol", "Süper potens kortikosteroid"],
    ["Fluocinonide", "Fluosinonid", "Yüksek potens kortikosteroid"],
    ["Desoximetasone", "Dezoksimetazon", "Yüksek potens kortikosteroid"],
    ["Desonide", "Dezonid", "Düşük potens kortikosteroid"],
    ["Alclometasone", "Alklometazon", "Düşük potens kortikosteroid"],
    ["Coal tar", "Kömür Katranı", "Psoriazis, seboreik dermatit"],
    ["Anthralin", "Antralin", "Psoriazis"],
    ["Psoralen", "Psoralen", "PUVA tedavisi"],
    ["Imiquimod", "İmikimod", "İmmün modülatör, siğil, AK"],
    ["Fluorouracil topical", "Topikal Fluorourasil", "AK, BCC"],
    ["Ingenol mebutate", "İngenol Mebutat", "Aktinik keratoz"],
    ["Tirbanibulin", "Tirbanibulin", "Aktinik keratoz"],
    ["Eflornithine", "Eflornithin", "Hirsutizm"],
    ["Permethrin", "Permetrin", "Uyuz, bit"],
    ["Lindane", "Lindan", "Uyuz, bit"],
    ["Malathion", "Malatyon", "Bit"],
    ["Spinosad", "Spinosad", "Bit"],
    // İmmünosupresanlar
    ["Cyclosporine", "Siklosporin", "Kalsinörin inhibitörü"],
    ["Tacrolimus", "Takrolimus", "Kalsinörin inhibitörü"],
    ["Sirolimus", "Sirolimus", "mTOR inhibitörü"],
    ["Everolimus", "Everolimus", "mTOR inhibitörü"],
    ["Mycophenolate mofetil", "Mikofenolat Mofetil", "IMPDH inhibitörü"],
    ["Mycophenolic acid", "Mikofenolik Asit", "IMPDH inhibitörü"],
    ["Azathioprine", "Azatioprin", "Pürin analoğu"],
    ["Methotrexate", "Metotreksat", "Antifolat, RA, psoriazis"],
    ["Leflunomide", "Leflunomid", "Pirimidin sentez inhibitörü"],
    ["Teriflunomide", "Teriflunomid", "MS tedavisi"],
    ["Hydroxychloroquine", "Hidroksiklorokin", "DMARD, SLE, RA"],
    ["Sulfasalazine", "Sülfasalazin", "DMARD, RA, IBD"],
    ["Penicillamine", "Penisillamin", "DMARD, Wilson"],
    // Biyolojik ajanlar
    ["Infliximab", "İnfliksimab", "Anti-TNF, RA, IBD, psoriazis"],
    ["Adalimumab", "Adalimumab", "Anti-TNF, RA, IBD, psoriazis"],
    ["Etanercept", "Etanersept", "TNF reseptör füzyon proteini"],
    ["Golimumab", "Golimumab", "Anti-TNF"],
    ["Certolizumab pegol", "Sertolizumab Pegol", "Pegillenmiş anti-TNF"],
    ["Anakinra", "Anakinra", "IL-1 reseptör antagonisti"],
    ["Canakinumab", "Kanakinumab", "Anti-IL-1β"],
    ["Rilonacept", "Rilonasept", "IL-1 tuzağı"],
    ["Tocilizumab", "Tosilizumab", "Anti-IL-6R"],
    ["Sarilumab", "Sarilumab", "Anti-IL-6R"],
    ["Siltuximab", "Siltuksimab", "Anti-IL-6"],
    ["Secukinumab", "Sekukinumab", "Anti-IL-17A"],
    ["Ixekizumab", "İksekizumab", "Anti-IL-17A"],
    ["Brodalumab", "Brodalumab", "Anti-IL-17R"],
    ["Ustekinumab", "Ustekinumab", "Anti-IL-12/23"],
    ["Guselkumab", "Guselkumab", "Anti-IL-23"],
    ["Tildrakizumab", "Tildrakizumab", "Anti-IL-23"],
    ["Risankizumab", "Risankizumab", "Anti-IL-23"],
    ["Dupilumab", "Dupilumab", "Anti-IL-4/IL-13"],
    ["Tralokinumab", "Tralokinumab", "Anti-IL-13"],
    ["Lebrikizumab", "Lebrikizumab", "Anti-IL-13"],
    // JAK inhibitörleri
    ["Tofacitinib", "Tofasitinib", "JAK inhibitörü"],
    ["Baricitinib", "Barisitinib", "JAK inhibitörü"],
    ["Upadacitinib", "Upadacitinib", "JAK inhibitörü"],
    ["Filgotinib", "Filgotinib", "JAK inhibitörü"],
    ["Ruxolitinib", "Ruksolitinib", "JAK inhibitörü"],
    ["Fedratinib", "Fedratinib", "JAK2 inhibitörü"],
    ["Pacritinib", "Pakritinib", "JAK2 inhibitörü"],
    ["Abrocitinib", "Abrocitinib", "JAK1 inhibitörü"],
    ["Abatacept", "Abatasept", "CTLA-4 Ig, T hücre kostimülasyon blokajı"],
    ["Belimumab", "Belimumab", "Anti-BLyS, SLE"],
    ["Anifrolumab", "Anifrolumab", "Anti-IFNAR1, SLE"],
    ["Rituximab", "Rituksimab", "Anti-CD20, RA, lenfoma"],
    ["Ocrelizumab", "Okrelizumab", "Anti-CD20, MS"],
    // Gastrointestinal ilaçlar
    ["Esomeprazole", "Esomeprazol", "Proton pompa inhibitörü"],
    ["Pantoprazole", "Pantoprazol", "Proton pompa inhibitörü"],
    ["Rabeprazole", "Rabeprazol", "Proton pompa inhibitörü"],
    ["Dexlansoprazole", "Dekslansoprazol", "Proton pompa inhibitörü"],
    ["Vonoprazan", "Vonoprazan", "Potasyum-kompetitif asit blokeri"],
    ["Famotidine", "Famotidin", "H2 reseptör antagonisti"],
    ["Nizatidine", "Nizatidin", "H2 reseptör antagonisti"],
    ["Sucralfate", "Sukralfat", "Mukoza koruyucu"],
    ["Misoprostol", "Mizoprostol", "PGE1 analoğu"],
    ["Bismuth subsalicylate", "Bizmut Subsalisilat", "Antidiyareik, antiülser"],
    ["Loperamide", "Loperamid", "Antidiyareik"],
    ["Diphenoxylate", "Difenoksilat", "Antidiyareik"],
    ["Eluxadoline", "Eluksadolin", "IBS-D tedavisi"],
    ["Alosetron", "Alosetron", "5-HT3 antagonisti, IBS-D"],
    ["Ondansetron", "Ondansetron", "5-HT3 antagonisti, antiemetik"],
    ["Granisetron", "Granisetron", "5-HT3 antagonisti, antiemetik"],
    ["Palonosetron", "Palonosetron", "5-HT3 antagonisti, antiemetik"],
    ["Aprepitant", "Aprepitant", "NK1 antagonisti, antiemetik"],
    ["Fosaprepitant", "Fosaprepitant", "NK1 antagonisti, antiemetik"],
    ["Netupitant", "Netupitant", "NK1 antagonisti, antiemetik"],
    ["Rolapitant", "Rolapitant", "NK1 antagonisti, antiemetik"],
    ["Dronabinol", "Dronabinol", "Kannabinoid, antiemetik"],
    ["Nabilone", "Nabilon", "Sentetik kannabinoid, antiemetik"],
    ["Metoclopramide", "Metoklopramid", "Prokinetik, antiemetik"],
    ["Domperidone", "Domperidon", "Prokinetik"],
    ["Prucalopride", "Prukalopirid", "5-HT4 agonisti, kabızlık"],
    ["Tegaserod", "Tegaserod", "5-HT4 agonisti, IBS-C"],
    ["Linaclotide", "Linakloitid", "GC-C agonisti, IBS-C"],
    ["Plecanatide", "Plekanatid", "GC-C agonisti, IBS-C"],
    ["Lubiprostone", "Lubiproston", "ClC-2 aktivatörü, kabızlık"],
    ["Tenapanor", "Tenapanor", "NHE3 inhibitörü, IBS-C"],
    ["Rifaximin", "Rifaksimin", "Bağırsak antibiyotiği, IBS-D"],
    ["Vedolizumab", "Vedolizumab", "Anti-integrin, IBD"],
    ["Ustekinumab IBD", "Ustekinumab IBD", "Anti-IL-12/23, Crohn"],
    ["Ozanimod IBD", "Ozanimod IBD", "S1P modülatörü, ülseratif kolit"],
    ["Tofacitinib UC", "Tofasitinib ÜK", "JAK inhibitörü, ülseratif kolit"],
    ["Upadacitinib UC", "Upadacitinib ÜK", "JAK inhibitörü, ülseratif kolit"],
    // Endokrin ilaçlar
    ["Levothyroxine", "Levotiroksin", "T4, hipotiroidizm"],
    ["Liothyronine", "Liyotironin", "T3, hipotiroidizm"],
    ["Methimazole", "Metimazol", "Antitiroid"],
    ["Propylthiouracil", "Propiltiyourasil", "Antitiroid"],
    ["Potassium iodide", "Potasyum İyodür", "Tiroid koruma"],
    ["Desmopressin", "Desmopressin", "ADH analoğu"],
    ["Tolvaptan", "Tolvaptan", "V2 antagonisti"],
    ["Conivaptan", "Konivaptan", "V1A/V2 antagonisti"],
    ["Somatropin", "Somatropin", "Büyüme hormonu"],
    ["Pegvisomant", "Pegvisomant", "GH reseptör antagonisti"],
    ["Octreotide", "Oktreotid", "Somatostatin analoğu"],
    ["Lanreotide", "Lanreotid", "Somatostatin analoğu"],
    ["Pasireotide", "Pasireotid", "Somatostatin analoğu"],
    ["Cabergoline", "Kabergolin", "Dopamin agonisti"],
    ["Bromocriptine", "Bromokriptin", "Dopamin agonisti"],
    ["Cinacalcet", "Sinakalset", "Kalsimimetik"],
    ["Etelcalcetide", "Etelkalsetid", "Kalsimimetik"],
    ["Teriparatide", "Teriparatid", "PTH analoğu"],
    ["Abaloparatide", "Abaloparatid", "PTHrP analoğu"],
    ["Romosozumab", "Romosozumab", "Anti-sklerostin"],
    ["Denosumab", "Denosumab", "Anti-RANKL"],
    ["Alendronate", "Alendronat", "Bifosfonat"],
    ["Risedronate", "Risedronat", "Bifosfonat"],
    ["Ibandronate", "İbandronat", "Bifosfonat"],
    ["Zoledronic acid", "Zoledronik Asit", "Bifosfonat"],
    ["Raloxifene", "Raloksifen", "SERM"],
    ["Bazedoxifene", "Bazedoksifen", "SERM"],
    // Diyabet ilaçları
    ["Metformin", "Metformin", "Biguanid"],
    ["Glipizide", "Glipizid", "Sülfonilüre"],
    ["Glyburide", "Glibürid", "Sülfonilüre"],
    ["Glimepiride", "Glimepirid", "Sülfonilüre"],
    ["Repaglinide", "Repaglinid", "Meglitinid"],
    ["Nateglinide", "Nateglinid", "Meglitinid"],
    ["Pioglitazone", "Pioglitazon", "Tiyazolidindion"],
    ["Rosiglitazone", "Rosiglitazon", "Tiyazolidindion"],
    ["Acarbose", "Akarboz", "Alfa-glukozidaz inhibitörü"],
    ["Miglitol", "Miglitol", "Alfa-glukozidaz inhibitörü"],
    ["Sitagliptin", "Sitagliptin", "DPP-4 inhibitörü"],
    ["Saxagliptin", "Saksagliptin", "DPP-4 inhibitörü"],
    ["Linagliptin", "Linagliptin", "DPP-4 inhibitörü"],
    ["Alogliptin", "Alogliptin", "DPP-4 inhibitörü"],
    ["Empagliflozin", "Empagliflozin", "SGLT2 inhibitörü"],
    ["Canagliflozin", "Kanagliflozin", "SGLT2 inhibitörü"],
    ["Dapagliflozin", "Dapagliflozin", "SGLT2 inhibitörü"],
    ["Ertugliflozin", "Ertugliflozin", "SGLT2 inhibitörü"],
    ["Sotagliflozin", "Sotagliflozin", "SGLT1/2 inhibitörü"],
    ["Liraglutide", "Liraglutid", "GLP-1 agonisti"],
    ["Semaglutide", "Semaglutid", "GLP-1 agonisti"],
    ["Dulaglutide", "Dulaglutid", "GLP-1 agonisti"],
    ["Exenatide", "Eksenatid", "GLP-1 agonisti"],
    ["Lixisenatide", "Liksisenatid", "GLP-1 agonisti"],
    ["Tirzepatide", "Tirzepatid", "GIP/GLP-1 agonisti"],
    ["Pramlintide", "Pramlintid", "Amilin analoğu"],
    // Solunum sistemi ilaçları
    ["Albuterol", "Albuterol", "Kısa etkili beta-2 agonist"],
    ["Levalbuterol", "Levalbuterol", "R-albuterol"],
    ["Terbutaline", "Terbutalin", "Beta-2 agonist"],
    ["Formoterol", "Formoterol", "Uzun etkili beta-2 agonist"],
    ["Salmeterol", "Salmeterol", "Uzun etkili beta-2 agonist"],
    ["Indacaterol", "İndakaterol", "Ultra uzun etkili beta-2 agonist"],
    ["Olodaterol", "Olodaterol", "Ultra uzun etkili beta-2 agonist"],
    ["Vilanterol", "Vilanterol", "Ultra uzun etkili beta-2 agonist"],
    ["Ipratropium", "İpratropium", "Kısa etkili antikolinerjik"],
    ["Tiotropium", "Tiyotropium", "Uzun etkili antikolinerjik"],
    ["Umeclidinium", "Umeklidinium", "Uzun etkili antikolinerjik"],
    ["Glycopyrrolate", "Glikopirrolat", "Uzun etkili antikolinerjik"],
    ["Aclidinium", "Aklidinium", "Uzun etkili antikolinerjik"],
    ["Revefenacin", "Revefenasin", "Uzun etkili antikolinerjik"],
    ["Beclomethasone", "Beklometazon", "İnhale kortikosteroid"],
    ["Budesonide", "Budesonid", "İnhale kortikosteroid"],
    ["Fluticasone", "Flutikason", "İnhale kortikosteroid"],
    ["Mometasone", "Mometazon", "İnhale kortikosteroid"],
    ["Ciclesonide", "Siklesonid", "İnhale kortikosteroid"],
    ["Flunisolide", "Flunisolid", "İnhale kortikosteroid"],
    ["Montelukast", "Montelukast", "Lökotrien antagonisti"],
    ["Zafirlukast", "Zafirlukast", "Lökotrien antagonisti"],
    ["Zileuton", "Zileuton", "5-lipoksijenaz inhibitörü"],
    ["Theophylline", "Teofilin", "Metilksantin"],
    ["Roflumilast", "Roflumilast", "PDE4 inhibitörü"],
    ["Omalizumab", "Omalizumab", "Anti-IgE"],
    ["Mepolizumab", "Mepolizumab", "Anti-IL-5"],
    ["Reslizumab", "Reslizumab", "Anti-IL-5"],
    ["Benralizumab", "Benralizumab", "Anti-IL-5R"],
    ["Dupilumab asthma", "Dupilumab Astım", "Anti-IL-4/IL-13"],
    ["Tezepelumab", "Tezepelumab", "Anti-TSLP"],
    ["Pirfenidone", "Pirfenidon", "Antifibrotik, IPF"],
    ["Nintedanib", "Nintedanib", "Tirozin kinaz inhibitörü, IPF"],
  ];
  return drugList.map(([latin, turkish, def]) =>
    createTerm(latin, turkish, TermCategory.DRUG, def)
  );
};
// HASTALIKLAR - Kapsamlı liste
const generateDiseases = () => {
  const diseaseList = [
    // Nadir hastalıklar
    ["Fabry disease", "Fabry Hastalığı", "Alfa-galaktosidaz eksikliği"],
    ["Gaucher disease", "Gaucher Hastalığı", "Glukoserebrosidaz eksikliği"],
    ["Pompe disease", "Pompe Hastalığı", "Asit maltaz eksikliği"],
    [
      "Niemann-Pick disease",
      "Niemann-Pick Hastalığı",
      "Sfingomyelinaz eksikliği",
    ],
    ["Tay-Sachs disease", "Tay-Sachs Hastalığı", "Heksozaminidaz A eksikliği"],
    [
      "Sandhoff disease",
      "Sandhoff Hastalığı",
      "Heksozaminidaz A ve B eksikliği",
    ],
    ["Krabbe disease", "Krabbe Hastalığı", "Galaktoserebrosidaz eksikliği"],
    [
      "Metachromatic leukodystrophy",
      "Metakromatik Lökodistrofi",
      "Arilsülfataz A eksikliği",
    ],
    [
      "Adrenoleukodystrophy",
      "Adrenolökodistrofi",
      "X-bağlı peroksizomal hastalık",
    ],
    [
      "Zellweger syndrome",
      "Zellweger Sendromu",
      "Peroksizomal biyogenez bozukluğu",
    ],
    ["Refsum disease", "Refsum Hastalığı", "Fitanik asit birikimi"],
    ["Canavan disease", "Canavan Hastalığı", "Aspartoasilaz eksikliği"],
    ["Alexander disease", "Alexander Hastalığı", "GFAP mutasyonu"],
    [
      "Pelizaeus-Merzbacher disease",
      "Pelizaeus-Merzbacher Hastalığı",
      "PLP1 mutasyonu",
    ],
    [
      "Vanishing white matter disease",
      "Kaybolan Beyaz Madde Hastalığı",
      "eIF2B mutasyonu",
    ],
    ["Leigh syndrome", "Leigh Sendromu", "Mitokondriyal ensefalopati"],
    ["MELAS syndrome", "MELAS Sendromu", "Mitokondriyal miyopati"],
    ["MERRF syndrome", "MERRF Sendromu", "Miyoklonik epilepsi"],
    [
      "Kearns-Sayre syndrome",
      "Kearns-Sayre Sendromu",
      "Mitokondriyal delesyon",
    ],
    [
      "NARP syndrome",
      "NARP Sendromu",
      "Nöropati, ataksi, retinitis pigmentoza",
    ],
    ["Friedreich ataxia", "Friedreich Ataksisi", "Frataksin eksikliği"],
    ["Spinocerebellar ataxia", "Spinoserebellar Ataksi", "SCA, genetik ataksi"],
    ["Ataxia telangiectasia", "Ataksi Telanjiektazi", "ATM mutasyonu"],
    [
      "Charcot-Marie-Tooth disease",
      "Charcot-Marie-Tooth Hastalığı",
      "Herediter nöropati",
    ],
    ["Hereditary sensory neuropathy", "Herediter Duyusal Nöropati", "HSN"],
    [
      "Familial amyloid polyneuropathy",
      "Ailesel Amiloid Polinöropati",
      "TTR amiloidoz",
    ],
    ["Hereditary spastic paraplegia", "Herediter Spastik Parapleji", "HSP"],
    ["Kennedy disease", "Kennedy Hastalığı", "Spinal bulbar müsküler atrofi"],
    ["Myotonic dystrophy type 1", "Miyotonik Distrofi Tip 1", "DM1, Steinert"],
    ["Myotonic dystrophy type 2", "Miyotonik Distrofi Tip 2", "DM2, PROMM"],
    ["Facioscapulohumeral dystrophy", "Fasiyoskapulohumeral Distrofi", "FSHD"],
    [
      "Limb-girdle muscular dystrophy",
      "Ekstremite Kuşağı Müsküler Distrofi",
      "LGMD",
    ],
    [
      "Emery-Dreifuss muscular dystrophy",
      "Emery-Dreifuss Müsküler Distrofi",
      "EDMD",
    ],
    ["Congenital muscular dystrophy", "Konjenital Müsküler Distrofi", "CMD"],
    ["Bethlem myopathy", "Bethlem Miyopatisi", "Kollajen VI miyopati"],
    [
      "Ullrich congenital muscular dystrophy",
      "Ullrich Konjenital Müsküler Distrofi",
      "Kollajen VI",
    ],
    ["Central core disease", "Santral Kor Hastalığı", "RYR1 miyopati"],
    ["Nemaline myopathy", "Nemalin Miyopati", "Konjenital miyopati"],
    ["Centronuclear myopathy", "Sentronükleer Miyopati", "Konjenital miyopati"],
    ["Myotubular myopathy", "Miyotübüler Miyopati", "X-bağlı miyopati"],
    [
      "Congenital fiber type disproportion",
      "Konjenital Fiber Tip Oransızlığı",
      "CFTD",
    ],
    ["Malignant hyperthermia", "Malign Hipertermi", "Anestezi komplikasyonu"],
    ["Periodic paralysis", "Periyodik Paralizi", "İyon kanalı hastalığı"],
    [
      "Hypokalemic periodic paralysis",
      "Hipokalemik Periyodik Paralizi",
      "HypoPP",
    ],
    [
      "Hyperkalemic periodic paralysis",
      "Hiperkalemik Periyodik Paralizi",
      "HyperPP",
    ],
    [
      "Paramyotonia congenita",
      "Paramiyotoni Konjenita",
      "Soğukla tetiklenen miyotoni",
    ],
    ["Myotonia congenita", "Miyotoni Konjenita", "Thomsen/Becker"],
    [
      "Andersen-Tawil syndrome",
      "Andersen-Tawil Sendromu",
      "Periyodik paralizi, aritmi",
    ],
    ["Brody disease", "Brody Hastalığı", "ATP2A1 miyopati"],
    [
      "Rippling muscle disease",
      "Dalgalanan Kas Hastalığı",
      "Caveolin-3 miyopati",
    ],
    // Otoimmün hastalıklar
    ["Autoimmune hepatitis", "Otoimmün Hepatit", "AIH"],
    ["Primary biliary cholangitis", "Primer Biliyer Kolanjit", "PBC"],
    ["Primary sclerosing cholangitis", "Primer Sklerozan Kolanjit", "PSC"],
    ["Autoimmune pancreatitis", "Otoimmün Pankreatit", "AIP"],
    ["Autoimmune gastritis", "Otoimmün Gastrit", "Pernisiyöz anemi"],
    ["Celiac disease", "Çölyak Hastalığı", "Gluten enteropatisi"],
    ["Autoimmune enteropathy", "Otoimmün Enteropati", "Bağırsak otoimmünitesi"],
    ["Autoimmune thyroiditis", "Otoimmün Tiroidit", "Hashimoto"],
    ["Graves disease", "Graves Hastalığı", "Otoimmün hipertiroidizm"],
    ["Type 1 diabetes", "Tip 1 Diyabet", "Otoimmün diyabet"],
    ["Addison disease", "Addison Hastalığı", "Otoimmün adrenal yetmezlik"],
    ["Autoimmune hypophysitis", "Otoimmün Hipofizit", "Hipofiz iltihabı"],
    ["Pemphigus vulgaris", "Pemfigus Vulgaris", "Deri otoimmün hastalığı"],
    ["Pemphigus foliaceus", "Pemfigus Foliaseus", "Deri otoimmün hastalığı"],
    ["Bullous pemphigoid", "Büllöz Pemfigoid", "Deri otoimmün hastalığı"],
    ["Cicatricial pemphigoid", "Sikatrisyel Pemfigoid", "Mukozal pemfigoid"],
    [
      "Dermatitis herpetiformis",
      "Dermatitis Herpetiformis",
      "Çölyak deri belirtisi",
    ],
    ["Linear IgA disease", "Lineer IgA Hastalığı", "Deri otoimmün hastalığı"],
    ["Epidermolysis bullosa acquisita", "Edinsel Epidermolizis Bülloza", "EBA"],
    ["Vitiligo", "Vitiligo", "Pigment kaybı"],
    ["Alopecia areata", "Alopesi Areata", "Saç dökülmesi"],
    ["Lichen planus", "Liken Planus", "Deri ve mukoza hastalığı"],
    ["Morphea", "Morfea", "Lokalize skleroderma"],
    ["Systemic sclerosis", "Sistemik Skleroz", "Skleroderma"],
    ["Mixed connective tissue disease", "Mikst Bağ Dokusu Hastalığı", "MCTD"],
    [
      "Undifferentiated connective tissue disease",
      "Farklılaşmamış Bağ Dokusu Hastalığı",
      "UCTD",
    ],
    ["Overlap syndrome", "Overlap Sendromu", "Çakışma sendromu"],
    ["Antisynthetase syndrome", "Antisintetaz Sendromu", "Miyozit alt tipi"],
    ["Stiff person syndrome", "Katı İnsan Sendromu", "Nörolojik otoimmün"],
    ["Neuromyelitis optica", "Nöromiyelitis Optika", "Devic hastalığı"],
    ["Autoimmune encephalitis", "Otoimmün Ensefalit", "Beyin iltihabı"],
    [
      "Anti-NMDA receptor encephalitis",
      "Anti-NMDA Reseptör Ensefaliti",
      "Otoimmün ensefalit",
    ],
    ["Limbic encephalitis", "Limbik Ensefalit", "Limbik sistem iltihabı"],
    ["Hashimoto encephalopathy", "Hashimoto Ensefalopatisi", "SREAT"],
    [
      "Autoimmune autonomic ganglionopathy",
      "Otoimmün Otonom Gangliyonopati",
      "AAG",
    ],
    [
      "Chronic inflammatory demyelinating polyneuropathy",
      "CIDP",
      "Kronik demiyelinizan polinöropati",
    ],
    ["Multifocal motor neuropathy", "Multifokal Motor Nöropati", "MMN"],
    ["Myasthenia gravis", "Miyastenia Gravis", "Nöromüsküler kavşak hastalığı"],
    ["Lambert-Eaton syndrome", "Lambert-Eaton Sendromu", "LEMS"],
    ["Acquired neuromyotonia", "Edinsel Nöromiyotoni", "Isaacs sendromu"],
    ["Autoimmune hemolytic anemia", "Otoimmün Hemolitik Anemi", "AIHA"],
    ["Immune thrombocytopenia", "İmmün Trombositopeni", "ITP"],
    ["Evans syndrome", "Evans Sendromu", "AIHA + ITP"],
    [
      "Thrombotic thrombocytopenic purpura",
      "Trombotik Trombositopenik Purpura",
      "TTP",
    ],
    ["Autoimmune neutropenia", "Otoimmün Nötropeni", "AIN"],
    ["Pure red cell aplasia", "Saf Kırmızı Hücre Aplazisi", "PRCA"],
    ["Aplastic anemia", "Aplastik Anemi", "Kemik iliği yetmezliği"],
    [
      "Autoimmune lymphoproliferative syndrome",
      "Otoimmün Lenfoproliferatif Sendrom",
      "ALPS",
    ],
    // Kanserler
    ["Acute myeloid leukemia", "Akut Miyeloid Lösemi", "AML"],
    ["Acute lymphoblastic leukemia", "Akut Lenfoblastik Lösemi", "ALL"],
    ["Chronic myeloid leukemia", "Kronik Miyeloid Lösemi", "KML"],
    ["Chronic lymphocytic leukemia", "Kronik Lenfositik Lösemi", "KLL"],
    ["Hairy cell leukemia", "Tüylü Hücreli Lösemi", "HCL"],
    ["Prolymphocytic leukemia", "Prolenfositik Lösemi", "PLL"],
    ["Adult T-cell leukemia", "Erişkin T Hücreli Lösemi", "ATL"],
    [
      "Large granular lymphocytic leukemia",
      "Büyük Granüler Lenfositik Lösemi",
      "LGL",
    ],
    ["Hodgkin lymphoma", "Hodgkin Lenfoma", "HL"],
    ["Classical Hodgkin lymphoma", "Klasik Hodgkin Lenfoma", "cHL"],
    [
      "Nodular lymphocyte predominant Hodgkin lymphoma",
      "Nodüler Lenfosit Predominant HL",
      "NLPHL",
    ],
    [
      "Diffuse large B-cell lymphoma",
      "Diffüz Büyük B Hücreli Lenfoma",
      "DLBCL",
    ],
    ["Follicular lymphoma", "Foliküler Lenfoma", "FL"],
    ["Mantle cell lymphoma", "Mantle Hücreli Lenfoma", "MCL"],
    ["Marginal zone lymphoma", "Marjinal Zon Lenfoma", "MZL"],
    ["MALT lymphoma", "MALT Lenfoma", "Mukoza ilişkili lenfoid doku lenfoma"],
    ["Burkitt lymphoma", "Burkitt Lenfoma", "Agresif B hücreli lenfoma"],
    ["Lymphoplasmacytic lymphoma", "Lenfoplazmositik Lenfoma", "LPL"],
    [
      "Primary mediastinal B-cell lymphoma",
      "Primer Mediastinal B Hücreli Lenfoma",
      "PMBCL",
    ],
    ["Primary CNS lymphoma", "Primer SSS Lenfoma", "PCNSL"],
    ["Peripheral T-cell lymphoma", "Periferik T Hücreli Lenfoma", "PTCL"],
    [
      "Anaplastic large cell lymphoma",
      "Anaplastik Büyük Hücreli Lenfoma",
      "ALCL",
    ],
    [
      "Angioimmunoblastic T-cell lymphoma",
      "Anjiyoimmünoblastik T Hücreli Lenfoma",
      "AITL",
    ],
    ["Mycosis fungoides", "Mikozis Fungoides", "Kutanöz T hücreli lenfoma"],
    ["Sezary syndrome", "Sézary Sendromu", "Lösemik CTCL"],
    ["Multiple myeloma", "Multipl Miyelom", "MM"],
    ["Smoldering myeloma", "Smoldering Miyelom", "Asemptomatik miyelom"],
    ["Plasma cell leukemia", "Plazma Hücreli Lösemi", "PCL"],
    ["Waldenstrom macroglobulinemia", "Waldenström Makroglobulinemisi", "WM"],
    ["AL amyloidosis", "AL Amiloidoz", "Primer amiloidoz"],
    ["POEMS syndrome", "POEMS Sendromu", "Polinöropati, organomegali"],
    ["Myelodysplastic syndrome", "Miyelodisplastik Sendrom", "MDS"],
    ["Myeloproliferative neoplasm", "Miyeloproliferatif Neoplazm", "MPN"],
    ["Polycythemia vera", "Polisitemia Vera", "PV"],
    ["Essential thrombocythemia", "Esansiyel Trombositemi", "ET"],
    ["Primary myelofibrosis", "Primer Miyelofibrozis", "PMF"],
    [
      "Chronic myelomonocytic leukemia",
      "Kronik Miyelomonositik Lösemi",
      "KMML",
    ],
    ["Mastocytosis", "Mastositoz", "Mast hücre hastalığı"],
    ["Systemic mastocytosis", "Sistemik Mastositoz", "SM"],
    ["Mast cell leukemia", "Mast Hücreli Lösemi", "MCL"],
    ["Langerhans cell histiocytosis", "Langerhans Hücreli Histiyositoz", "LCH"],
    ["Erdheim-Chester disease", "Erdheim-Chester Hastalığı", "ECD"],
    ["Rosai-Dorfman disease", "Rosai-Dorfman Hastalığı", "RDD"],
    [
      "Hemophagocytic lymphohistiocytosis",
      "Hemofagositik Lenfohistiyositoz",
      "HLH",
    ],
    ["Castleman disease", "Castleman Hastalığı", "CD"],
    [
      "Post-transplant lymphoproliferative disorder",
      "Transplant Sonrası Lenfoproliferatif Bozukluk",
      "PTLD",
    ],
    ["Kaposi sarcoma", "Kaposi Sarkomu", "HHV-8 ilişkili"],
    ["Primary effusion lymphoma", "Primer Efüzyon Lenfoma", "PEL"],
    ["Plasmablastic lymphoma", "Plazmablastik Lenfoma", "PBL"],
    [
      "Blastic plasmacytoid dendritic cell neoplasm",
      "Blastik Plazmositoid Dendritik Hücre Neoplazm",
      "BPDCN",
    ],
    // Enfeksiyon hastalıkları
    ["Tuberculosis", "Tüberküloz", "Mycobacterium tuberculosis"],
    ["Leprosy", "Cüzzam", "Mycobacterium leprae"],
    [
      "Nontuberculous mycobacterial infection",
      "Tüberküloz Dışı Mikobakteri Enfeksiyonu",
      "NTM",
    ],
    ["Lyme disease", "Lyme Hastalığı", "Borrelia burgdorferi"],
    ["Syphilis", "Sifiliz", "Treponema pallidum"],
    ["Leptospirosis", "Leptospiroz", "Leptospira"],
    ["Brucellosis", "Bruselloz", "Brucella"],
    ["Tularemia", "Tularemi", "Francisella tularensis"],
    ["Plague", "Veba", "Yersinia pestis"],
    ["Anthrax", "Şarbon", "Bacillus anthracis"],
    ["Listeriosis", "Listerioz", "Listeria monocytogenes"],
    ["Nocardiosis", "Nokardioz", "Nocardia"],
    ["Actinomycosis", "Aktinomikoz", "Actinomyces"],
    ["Whipple disease", "Whipple Hastalığı", "Tropheryma whipplei"],
    ["Cat scratch disease", "Kedi Tırmığı Hastalığı", "Bartonella henselae"],
    ["Q fever", "Q Ateşi", "Coxiella burnetii"],
    [
      "Rocky Mountain spotted fever",
      "Rocky Mountain Benekli Ateşi",
      "Rickettsia rickettsii",
    ],
    ["Typhus", "Tifüs", "Rickettsia prowazekii"],
    ["Ehrlichiosis", "Erlikiyoz", "Ehrlichia"],
    ["Anaplasmosis", "Anaplazmoz", "Anaplasma phagocytophilum"],
    ["Babesiosis", "Babesioz", "Babesia"],
    ["Malaria", "Sıtma", "Plasmodium"],
    ["Toxoplasmosis", "Toksoplazmoz", "Toxoplasma gondii"],
    ["Leishmaniasis", "Leishmaniasis", "Leishmania"],
    ["Trypanosomiasis", "Tripanozomiasis", "Trypanosoma"],
    ["Chagas disease", "Chagas Hastalığı", "Trypanosoma cruzi"],
    ["Amebiasis", "Amipli Dizanteri", "Entamoeba histolytica"],
    ["Giardiasis", "Giardiasis", "Giardia lamblia"],
    ["Cryptosporidiosis", "Kriptosporidioz", "Cryptosporidium"],
    ["Cyclosporiasis", "Siklosporiyaz", "Cyclospora cayetanensis"],
    ["Microsporidiosis", "Mikrosporidioz", "Microsporidia"],
    ["Strongyloidiasis", "Strongiloidiyaz", "Strongyloides stercoralis"],
    ["Ascariasis", "Askariasis", "Ascaris lumbricoides"],
    ["Hookworm infection", "Kancalı Kurt Enfeksiyonu", "Ancylostoma, Necator"],
    ["Trichuriasis", "Triküriasis", "Trichuris trichiura"],
    ["Enterobiasis", "Enterobiyaz", "Enterobius vermicularis"],
    ["Filariasis", "Filariasis", "Wuchereria, Brugia"],
    ["Onchocerciasis", "Onkoserkiyaz", "Onchocerca volvulus"],
    ["Loiasis", "Loiasis", "Loa loa"],
    ["Dracunculiasis", "Drakunkuliyaz", "Dracunculus medinensis"],
    ["Schistosomiasis", "Şistosomiyaz", "Schistosoma"],
    ["Fascioliasis", "Fasiyoliyaz", "Fasciola hepatica"],
    ["Clonorchiasis", "Klonorkiyaz", "Clonorchis sinensis"],
    ["Opisthorchiasis", "Opistorkiyaz", "Opisthorchis"],
    ["Paragonimiasis", "Paragonimiyaz", "Paragonimus westermani"],
    ["Taeniasis", "Tenyaz", "Taenia"],
    ["Cysticercosis", "Sistiserkoz", "Taenia solium"],
    ["Echinococcosis", "Ekinokokoz", "Echinococcus"],
    ["Diphyllobothriasis", "Difillobotriaz", "Diphyllobothrium latum"],
  ];
  return diseaseList.map(([latin, turkish, def]) =>
    createTerm(latin, turkish, TermCategory.DISEASE, def)
  );
};
// ANATOMİ - Kapsamlı liste
const generateAnatomy = () => {
  const anatomyList = [
    // Beyin yapıları
    ["Caudate nucleus", "Kaudat Nükleus", "Bazal ganglion"],
    ["Putamen", "Putamen", "Bazal ganglion"],
    ["Globus pallidus", "Globus Pallidus", "Bazal ganglion"],
    ["Substantia nigra", "Substansiya Nigra", "Dopamin üretimi"],
    ["Subthalamic nucleus", "Subtalamik Nükleus", "Hareket kontrolü"],
    ["Red nucleus", "Kırmızı Nükleus", "Motor koordinasyon"],
    ["Inferior olive", "İnferior Oliv", "Serebellum bağlantısı"],
    ["Dentate nucleus", "Dentat Nükleus", "Serebellar nükleus"],
    ["Fastigial nucleus", "Fastigial Nükleus", "Serebellar nükleus"],
    ["Interposed nuclei", "İnterpozit Nükleuslar", "Serebellar nükleus"],
    ["Locus coeruleus", "Lokus Seruleus", "Norepinefrin üretimi"],
    ["Raphe nuclei", "Rafe Nükleusları", "Serotonin üretimi"],
    ["Periaqueductal gray", "Periakuaduktal Gri", "Ağrı modülasyonu"],
    ["Superior colliculus", "Süperior Kollikulus", "Görsel refleksler"],
    ["Inferior colliculus", "İnferior Kollikulus", "İşitsel işleme"],
    [
      "Lateral geniculate nucleus",
      "Lateral Genikulat Nükleus",
      "Görsel aktarım",
    ],
    [
      "Medial geniculate nucleus",
      "Medial Genikulat Nükleus",
      "İşitsel aktarım",
    ],
    ["Pulvinar", "Pulvinar", "Talamus çekirdeği"],
    [
      "Anterior thalamic nuclei",
      "Anterior Talamik Nükleuslar",
      "Limbik bağlantı",
    ],
    [
      "Ventral posterolateral nucleus",
      "Ventral Posterolateral Nükleus",
      "Somatosensoriyel",
    ],
    [
      "Ventral posteromedial nucleus",
      "Ventral Posteromedial Nükleus",
      "Yüz duyusu",
    ],
    ["Mammillary bodies", "Mamiller Cisimler", "Hafıza"],
    ["Habenula", "Habenula", "Ödül işleme"],
    ["Pineal gland", "Pineal Bez", "Melatonin üretimi"],
    ["Fornix", "Forniks", "Limbik bağlantı"],
    ["Cingulate gyrus", "Singulat Girus", "Duygu, dikkat"],
    ["Parahippocampal gyrus", "Parahipokampal Girus", "Hafıza"],
    ["Entorhinal cortex", "Entorinal Korteks", "Hafıza, navigasyon"],
    ["Insular cortex", "İnsular Korteks", "İntrosepsiyon"],
    ["Orbitofrontal cortex", "Orbitofrontal Korteks", "Karar verme"],
    ["Prefrontal cortex", "Prefrontal Korteks", "Yürütücü işlevler"],
    ["Primary motor cortex", "Primer Motor Korteks", "Hareket başlatma"],
    ["Premotor cortex", "Premotor Korteks", "Hareket planlama"],
    [
      "Supplementary motor area",
      "Tamamlayıcı Motor Alan",
      "Hareket sıralaması",
    ],
    [
      "Primary somatosensory cortex",
      "Primer Somatosensoriyel Korteks",
      "Dokunma duyusu",
    ],
    ["Primary visual cortex", "Primer Görsel Korteks", "V1, görme"],
    ["Primary auditory cortex", "Primer İşitsel Korteks", "A1, işitme"],
    ["Wernicke area", "Wernicke Alanı", "Dil anlama"],
    ["Broca area", "Broca Alanı", "Dil üretimi"],
    ["Angular gyrus", "Angüler Girus", "Okuma, hesaplama"],
    ["Supramarginal gyrus", "Supramarginal Girus", "Dil, dikkat"],
    // Göz anatomisi
    ["Cornea", "Kornea", "Saydam tabaka"],
    ["Sclera", "Sklera", "Beyaz tabaka"],
    ["Iris", "İris", "Renkli halka"],
    ["Pupil", "Pupil", "Göz bebeği"],
    ["Lens", "Lens", "Göz merceği"],
    ["Ciliary body", "Silyer Cisim", "Akomodasyon"],
    ["Choroid", "Koroid", "Damar tabakası"],
    ["Retina", "Retina", "Ağ tabaka"],
    ["Macula", "Makula", "Sarı nokta"],
    ["Fovea", "Fovea", "Keskin görme merkezi"],
    ["Optic disc", "Optik Disk", "Kör nokta"],
    ["Vitreous humor", "Vitreus Humor", "Camsı sıvı"],
    ["Aqueous humor", "Aköz Humor", "Ön kamara sıvısı"],
    ["Trabecular meshwork", "Trabeküler Ağ", "Aköz drenajı"],
    ["Schlemm canal", "Schlemm Kanalı", "Aköz drenajı"],
    ["Conjunctiva", "Konjonktiva", "Göz zarı"],
    ["Lacrimal gland", "Lakrimal Bez", "Gözyaşı bezi"],
    ["Lacrimal duct", "Lakrimal Kanal", "Gözyaşı kanalı"],
    ["Extraocular muscles", "Ekstraoküler Kaslar", "Göz kasları"],
    ["Optic nerve", "Optik Sinir", "Görme siniri"],
    // Endokrin sistem
    ["Pituitary gland", "Hipofiz Bezi", "Ana endokrin bez"],
    ["Anterior pituitary", "Ön Hipofiz", "Adenohipofiz"],
    ["Posterior pituitary", "Arka Hipofiz", "Nörohipofiz"],
    ["Thyroid gland", "Tiroid Bezi", "Tiroid hormonu üretimi"],
    ["Parathyroid glands", "Paratiroid Bezleri", "PTH üretimi"],
    ["Adrenal glands", "Adrenal Bezler", "Böbrek üstü bezleri"],
    ["Adrenal cortex", "Adrenal Korteks", "Steroid hormon üretimi"],
    ["Zona glomerulosa", "Zona Glomeruloza", "Aldosteron üretimi"],
    ["Zona fasciculata", "Zona Fasikulata", "Kortizol üretimi"],
    ["Zona reticularis", "Zona Retikularis", "Androjen üretimi"],
    ["Adrenal medulla", "Adrenal Medulla", "Katekolamin üretimi"],
    ["Pancreatic islets", "Pankreas Adacıkları", "Langerhans adacıkları"],
    ["Alpha cells", "Alfa Hücreleri", "Glukagon üretimi"],
    ["Beta cells", "Beta Hücreleri", "İnsülin üretimi"],
    ["Delta cells", "Delta Hücreleri", "Somatostatin üretimi"],
    ["PP cells", "PP Hücreleri", "Pankreatik polipeptid"],
    // Lenfatik sistem
    ["Lymph nodes", "Lenf Düğümleri", "Lenfatik filtre"],
    ["Cervical lymph nodes", "Servikal Lenf Düğümleri", "Boyun lenf düğümleri"],
    [
      "Axillary lymph nodes",
      "Aksiller Lenf Düğümleri",
      "Koltuk altı lenf düğümleri",
    ],
    ["Inguinal lymph nodes", "İnguinal Lenf Düğümleri", "Kasık lenf düğümleri"],
    [
      "Mediastinal lymph nodes",
      "Mediastinal Lenf Düğümleri",
      "Göğüs lenf düğümleri",
    ],
    [
      "Mesenteric lymph nodes",
      "Mezenterik Lenf Düğümleri",
      "Bağırsak lenf düğümleri",
    ],
    ["Spleen", "Dalak", "Lenfoid organ, kan filtresi"],
    ["Red pulp", "Kırmızı Pulpa", "Eritrosit filtrasyonu"],
    ["White pulp", "Beyaz Pulpa", "Lenfoid doku"],
    ["Thymus", "Timus", "T hücre olgunlaşması"],
    ["Tonsils", "Bademcikler", "Lenfoid doku"],
    ["Palatine tonsils", "Palatin Tonsiller", "Damak bademcikleri"],
    ["Pharyngeal tonsil", "Faringeal Tonsil", "Adenoid"],
    ["Lingual tonsils", "Lingual Tonsiller", "Dil bademcikleri"],
    ["Peyer patches", "Peyer Plakları", "Bağırsak lenfoid dokusu"],
    ["Appendix", "Apendiks", "Lenfoid doku içerir"],
    ["Bone marrow", "Kemik İliği", "Hematopoez merkezi"],
    ["Red bone marrow", "Kırmızı Kemik İliği", "Aktif hematopoez"],
    ["Yellow bone marrow", "Sarı Kemik İliği", "Yağ dokusu"],
    // Deri ve ekleri
    ["Epidermis", "Epidermis", "Deri üst tabakası"],
    ["Stratum corneum", "Stratum Korneum", "Boynuzsu tabaka"],
    ["Stratum lucidum", "Stratum Lusidum", "Saydam tabaka"],
    ["Stratum granulosum", "Stratum Granulozum", "Granüler tabaka"],
    ["Stratum spinosum", "Stratum Spinozum", "Dikensi tabaka"],
    ["Stratum basale", "Stratum Bazale", "Bazal tabaka"],
    ["Dermis", "Dermis", "Deri orta tabakası"],
    ["Papillary dermis", "Papiller Dermis", "Üst dermis"],
    ["Reticular dermis", "Retiküler Dermis", "Alt dermis"],
    ["Hypodermis", "Hipodermis", "Deri altı yağ dokusu"],
    ["Hair follicle", "Kıl Folikülü", "Kıl kökü"],
    ["Sebaceous gland", "Sebase Bez", "Yağ bezi"],
    ["Sweat gland", "Ter Bezi", "Ekrin ve apokrin"],
    ["Nail", "Tırnak", "Keratin yapı"],
    // Kas sistemi
    ["Skeletal muscle", "İskelet Kası", "İstemli kas"],
    ["Cardiac muscle", "Kalp Kası", "Miyokard"],
    ["Smooth muscle", "Düz Kas", "İstemsiz kas"],
    ["Sarcomere", "Sarkomer", "Kas kontraktil birimi"],
    ["Myofibril", "Miyofibril", "Kas lifi"],
    ["Actin", "Aktin", "İnce filament"],
    ["Myosin", "Miyozin", "Kalın filament"],
    ["Troponin", "Troponin", "Düzenleyici protein"],
    ["Tropomyosin", "Tropomiyozin", "Düzenleyici protein"],
    ["Sarcoplasmic reticulum", "Sarkoplazmik Retikulum", "Kalsiyum deposu"],
    ["T-tubule", "T-Tübül", "Transvers tübül"],
    ["Neuromuscular junction", "Nöromüsküler Kavşak", "Sinir-kas bağlantısı"],
    ["Motor end plate", "Motor Son Plak", "Kas sinir bağlantısı"],
    ["Tendon", "Tendon", "Kas-kemik bağlantısı"],
    ["Ligament", "Ligament", "Kemik-kemik bağlantısı"],
    ["Fascia", "Fasya", "Bağ dokusu örtüsü"],
    ["Aponeurosis", "Aponevroz", "Düz tendon"],
    // Sinir sistemi
    ["Neuron", "Nöron", "Sinir hücresi"],
    ["Axon", "Akson", "Sinir lifi"],
    ["Dendrite", "Dendrit", "Sinir dalı"],
    ["Synapse", "Sinaps", "Sinir bağlantısı"],
    ["Myelin sheath", "Miyelin Kılıfı", "Sinir yalıtımı"],
    ["Node of Ranvier", "Ranvier Düğümü", "Miyelin boşluğu"],
    ["Schwann cell", "Schwann Hücresi", "Periferik miyelin"],
    ["Oligodendrocyte", "Oligodendrosit", "Santral miyelin"],
    ["Astrocyte", "Astrosit", "Destek hücresi"],
    ["Microglia", "Mikroglia", "Beyin makrofajı"],
    ["Ependymal cell", "Ependimal Hücre", "BOS üretimi"],
    ["Blood-brain barrier", "Kan-Beyin Bariyeri", "BBB"],
    ["Choroid plexus", "Koroid Pleksus", "BOS üretimi"],
    ["Meninges", "Meninksler", "Beyin zarları"],
    ["Dura mater", "Dura Mater", "Sert zar"],
    ["Arachnoid mater", "Araknoid Mater", "Örümceksi zar"],
    ["Pia mater", "Pia Mater", "Yumuşak zar"],
    ["Subarachnoid space", "Subaraknoid Boşluk", "BOS boşluğu"],
    ["Cerebral ventricles", "Serebral Ventriküller", "Beyin boşlukları"],
    ["Lateral ventricle", "Lateral Ventrikül", "Yan ventrikül"],
    ["Third ventricle", "Üçüncü Ventrikül", "Diensefalon"],
    ["Fourth ventricle", "Dördüncü Ventrikül", "Beyin sapı"],
  ];
  return anatomyList.map(([latin, turkish, def]) =>
    createTerm(latin, turkish, TermCategory.ANATOMY, def)
  );
};
// BİTKİLER - Kapsamlı liste
const generatePlants = () => {
  const plantList = [
    ["Aconitum carmichaelii", "Fu Zi", "Çin tıbbı, kardiyotonik"],
    ["Acorus calamus", "Eğir", "Sindirim, hafıza"],
    ["Adhatoda vasica", "Adhatoda", "Ekspektoran, bronkodilatör"],
    ["Aegle marmelos", "Bael", "Sindirim, antidiyareik"],
    ["Agathosma betulina", "Buchu", "Diüretik, antiseptik"],
    ["Akebia quinata", "Mu Tong", "Diüretik, laktasyon"],
    ["Albizia julibrissin", "He Huan Pi", "Anksiyolitik, sedatif"],
    ["Alisma plantago-aquatica", "Ze Xie", "Diüretik"],
    ["Alpinia galanga", "Galangal", "Sindirim, antiinflamatuar"],
    ["Alpinia officinarum", "Gao Liang Jiang", "Karminatif, antiemetik"],
    ["Amomum villosum", "Sha Ren", "Karminatif, sindirim"],
    ["Andrographis paniculata", "Chuan Xin Lian", "İmmünostimülan, antiviral"],
    ["Anemarrhena asphodeloides", "Zhi Mu", "Ateş düşürücü, antiinflamatuar"],
    ["Aquilaria sinensis", "Chen Xiang", "Karminatif, sedatif"],
    ["Aralia elata", "Ci Wu Jia", "Adaptojenik"],
    ["Arctostaphylos uva-ursi", "Ayı Üzümü", "Üriner antiseptik"],
    ["Areca catechu", "Betel Cevizi", "Antihelmintik"],
    ["Artemisia capillaris", "Yin Chen Hao", "Hepatoprotektif, koleretik"],
    ["Asparagus cochinchinensis", "Tian Men Dong", "Yin tonik, ekspektoran"],
    ["Asparagus racemosus", "Shatavari", "Kadın tonik, adaptojenik"],
    ["Atractylodes lancea", "Cang Zhu", "Sindirim, antiinflamatuar"],
    ["Azadirachta indica", "Neem", "Antimikrobiyal, antiparaziter"],
    ["Bacopa monnieri", "Brahmi", "Nootropik, hafıza"],
    [
      "Berberis aristata",
      "Hint Kadın Tuzluğu",
      "Antimikrobiyal, hepatoprotektif",
    ],
    ["Boerhavia diffusa", "Punarnava", "Diüretik, hepatoprotektif"],
    ["Boswellia serrata", "Akgünlük", "Antiinflamatuar"],
    ["Bupleurum chinense", "Chai Hu", "Karaciğer, ateş düşürücü"],
    ["Camellia sinensis", "Çay", "Antioksidan, stimülan"],
    ["Carthamus tinctorius", "Hong Hua", "Kan dolaşımı, emmenagog"],
    [
      "Catharanthus roseus",
      "Madagaskar Cezayir Menekşesi",
      "Antitümör alkaloidler",
    ],
    ["Centella asiatica", "Gotu Kola", "Yara iyileştirici, nootropik"],
    ["Chrysanthemum morifolium", "Ju Hua", "Göz sağlığı, ateş düşürücü"],
    ["Cinchona officinalis", "Kinin Ağacı", "Antimalaryal, acı tonik"],
    ["Cinnamomum cassia", "Rou Gui", "Isıtıcı, kan dolaşımı"],
    ["Cistanche deserticola", "Rou Cong Rong", "Yang tonik, laksatif"],
    ["Citrus aurantium", "Zhi Shi", "Sindirim, sinefrin kaynağı"],
    ["Cnidium monnieri", "She Chuang Zi", "Cilt, libido"],
    ["Codonopsis pilosula", "Dang Shen", "Qi tonik"],
    ["Coix lacryma-jobi", "Yi Yi Ren", "Diüretik, antiinflamatuar"],
    ["Colchicum autumnale", "Güz Çiğdemi", "Gut, kolşisin kaynağı"],
    ["Commiphora mukul", "Guggul", "Hipolipidemik"],
    ["Convallaria majalis", "Müge Çiçeği", "Kardiyotonik glikozidler"],
    ["Coptis chinensis", "Huang Lian", "Antimikrobiyal, antiinflamatuar"],
    ["Coriandrum sativum", "Kişniş", "Karminatif, sindirim"],
    ["Cornus officinalis", "Shan Zhu Yu", "Böbrek tonik"],
    ["Corydalis yanhusuo", "Yan Hu Suo", "Analjezik"],
    ["Crataegus pinnatifida", "Shan Zha", "Kardiyotonik, sindirim"],
    ["Curcuma longa", "Zerdeçal", "Antiinflamatuar, antioksidan"],
    ["Curcuma zedoaria", "E Zhu", "Kan dolaşımı, antitümör"],
    ["Cyperus rotundus", "Xiang Fu", "Qi düzenleyici, analjezik"],
    ["Dendrobium nobile", "Shi Hu", "Yin tonik"],
    ["Dioscorea opposita", "Shan Yao", "Qi ve Yin tonik"],
    ["Eclipta prostrata", "Han Lian Cao", "Karaciğer ve böbrek tonik"],
    ["Elettaria cardamomum", "Kakule", "Karminatif, sindirim"],
    ["Emblica officinalis", "Amla", "Antioksidan, C vitamini"],
    ["Ephedra sinica", "Ma Huang", "Bronkodilatör, dekonjestan"],
    ["Epimedium brevicornu", "Yin Yang Huo", "Yang tonik, afrodizyak"],
    ["Eriobotrya japonica", "Pi Pa Ye", "Ekspektoran, antiemetik"],
    ["Eucommia ulmoides", "Du Zhong", "Kemik ve tendon güçlendirici"],
    ["Evodia rutaecarpa", "Wu Zhu Yu", "Isıtıcı, analjezik"],
    ["Ferula assa-foetida", "Şeytan Tersi", "Karminatif, antispazmodik"],
    ["Forsythia suspensa", "Lian Qiao", "Ateş düşürücü, antimikrobiyal"],
    ["Fritillaria cirrhosa", "Chuan Bei Mu", "Ekspektoran, antitusif"],
    ["Gardenia jasminoides", "Zhi Zi", "Ateş düşürücü, koleretik"],
    ["Gastrodia elata", "Tian Ma", "Antikonvülzan, baş ağrısı"],
    ["Gentiana scabra", "Long Dan Cao", "Acı tonik, hepatoprotektif"],
    ["Ginkgo biloba", "Ginkgo", "Serebral dolaşım, antioksidan"],
    ["Glycyrrhiza uralensis", "Gan Cao", "Harmonize edici, antiinflamatuar"],
    ["Gymnema sylvestre", "Gymnema", "Antidiyabetik"],
    ["Gynostemma pentaphyllum", "Jiaogulan", "Adaptojenik, antioksidan"],
    ["Hedyotis diffusa", "Bai Hua She She Cao", "Antitümör, antimikrobiyal"],
    ["Houttuynia cordata", "Yu Xing Cao", "Antimikrobiyal, antiinflamatuar"],
    [
      "Hypericum perforatum",
      "Sarı Kantaron",
      "Antidepresan, yara iyileştirici",
    ],
    ["Ilex paraguariensis", "Mate", "Stimülan, antioksidan"],
    ["Illicium verum", "Yıldız Anason", "Karminatif, antimikrobiyal"],
    ["Inula helenium", "Andız Otu", "Ekspektoran, antimikrobiyal"],
    ["Isatis tinctoria", "Ban Lan Gen", "Antiviral, antimikrobiyal"],
    ["Leonurus cardiaca", "Aslan Kuyruğu", "Kardiyotonik, sedatif"],
    ["Ligusticum wallichii", "Chuan Xiong", "Kan dolaşımı"],
    ["Ligustrum lucidum", "Nu Zhen Zi", "Yin tonik, hepatoprotektif"],
    ["Lilium brownii", "Bai He", "Akciğer tonik, sedatif"],
    ["Linum usitatissimum", "Keten", "Laksatif, omega-3"],
    ["Lobelia inflata", "Hint Tütünü", "Ekspektoran, antispazmodik"],
    ["Lonicera japonica", "Jin Yin Hua", "Ateş düşürücü, antimikrobiyal"],
    ["Lycium barbarum", "Goji", "Göz sağlığı, antioksidan"],
    ["Magnolia officinalis", "Hou Po", "Qi düzenleyici, antispazmodik"],
    ["Matricaria chamomilla", "Papatya", "Antiinflamatuar, sedatif"],
    ["Melaleuca alternifolia", "Çay Ağacı", "Antimikrobiyal, antifungal"],
    ["Melissa officinalis", "Melisa", "Sedatif, antiviral"],
    ["Mentha piperita", "Nane", "Karminatif, analjezik"],
    ["Momordica charantia", "Kudret Narı", "Antidiyabetik"],
    ["Morinda officinalis", "Ba Ji Tian", "Yang tonik"],
    ["Morus alba", "Dut", "Antidiyabetik, ekspektoran"],
    ["Mucuna pruriens", "Kadife Fasulye", "Dopamin öncüsü"],
    ["Myristica fragrans", "Muskat", "Karminatif, narkotik"],
    ["Nelumbo nucifera", "Lotus", "Astrenjan, sedatif"],
    ["Nigella sativa", "Çörek Otu", "İmmünomodülatör, antiinflamatuar"],
    ["Ocimum sanctum", "Kutsal Fesleğen", "Adaptojenik"],
    ["Ophiopogon japonicus", "Mai Men Dong", "Yin tonik, ekspektoran"],
    ["Origanum vulgare", "Kekik", "Antimikrobiyal, ekspektoran"],
    ["Paeonia lactiflora", "Bai Shao", "Antiinflamatuar, analjezik"],
    ["Paeonia suffruticosa", "Mu Dan Pi", "Kan soğutucu, antiinflamatuar"],
    ["Panax ginseng", "Kore Ginsengi", "Adaptojenik, tonik"],
    ["Panax notoginseng", "San Qi", "Hemostatik, kan dolaşımı"],
    ["Passiflora incarnata", "Çarkıfelek", "Sedatif, anksiyolitik"],
    ["Perilla frutescens", "Zi Su Ye", "Antiallerjik, antimikrobiyal"],
    ["Petasites hybridus", "Kabalak", "Migren, antiallerjik"],
    ["Phellodendron amurense", "Huang Bai", "Antimikrobiyal, antiinflamatuar"],
    ["Phyllanthus niruri", "Chanca Piedra", "Hepatoprotektif, böbrek taşı"],
    ["Picrorhiza kurroa", "Kutki", "Hepatoprotektif, immünomodülatör"],
    ["Pinellia ternata", "Ban Xia", "Antiemetik, ekspektoran"],
    ["Piper longum", "Uzun Biber", "Biyoyararlanım artırıcı"],
    ["Piper nigrum", "Karabiber", "Biyoyararlanım artırıcı, sindirim"],
    ["Plantago asiatica", "Che Qian Zi", "Diüretik, ekspektoran"],
    ["Platycodon grandiflorus", "Jie Geng", "Ekspektoran, antiinflamatuar"],
    ["Pogostemon cablin", "Paçuli", "Aromatik, antimikrobiyal"],
    ["Polygala tenuifolia", "Yuan Zhi", "Nootropik, ekspektoran"],
    ["Polygonatum sibiricum", "Huang Jing", "Qi ve Yin tonik"],
    ["Polygonum cuspidatum", "Hu Zhang", "Antiinflamatuar, resveratrol"],
    ["Polygonum multiflorum", "He Shou Wu", "Tonik, saç"],
    ["Poria cocos", "Fu Ling", "Diüretik, sedatif"],
    ["Prunella vulgaris", "Xia Ku Cao", "Ateş düşürücü, hepatoprotektif"],
    ["Prunus armeniaca", "Xing Ren", "Antitusif, laksatif"],
    ["Psoralea corylifolia", "Bu Gu Zhi", "Yang tonik, vitiligo"],
    ["Pueraria lobata", "Ge Gen", "Kas gevşetici, ateş düşürücü"],
    ["Punica granatum", "Nar", "Antioksidan, antihelmintik"],
    ["Rauvolfia serpentina", "Hint Yılan Kökü", "Antihipertansif, sedatif"],
    ["Rehmannia glutinosa", "Di Huang", "Kan tonik"],
    ["Rhamnus purshiana", "Cascara", "Laksatif"],
    ["Rheum palmatum", "Da Huang", "Laksatif, antiinflamatuar"],
    ["Rhodiola rosea", "Altın Kök", "Adaptojenik, antidepresan"],
    ["Rosmarinus officinalis", "Biberiye", "Antioksidan, hafıza"],
    ["Rubia cordifolia", "Qian Cao", "Kan dolaşımı, hemostatik"],
    ["Salix alba", "Beyaz Söğüt", "Analjezik, antiinflamatuar"],
    ["Salvia miltiorrhiza", "Dan Shen", "Kardiyovasküler"],
    ["Salvia officinalis", "Adaçayı", "Antimikrobiyal, hafıza"],
    ["Sambucus nigra", "Mürver", "Antiviral, diaforetik"],
    ["Sanguinaria canadensis", "Kan Kökü", "Ekspektoran, antimikrobiyal"],
    ["Santalum album", "Sandal Ağacı", "Antiseptik, sedatif"],
    ["Schisandra chinensis", "Wu Wei Zi", "Adaptojenik, hepatoprotektif"],
    ["Scutellaria baicalensis", "Huang Qin", "Antiinflamatuar, antioksidan"],
    ["Serenoa repens", "Saw Palmetto", "BPH, antiandrojenik"],
    ["Silybum marianum", "Deve Dikeni", "Hepatoprotektif"],
    ["Smilax glabra", "Tu Fu Ling", "Detoksifiye edici, antiinflamatuar"],
    ["Sophora flavescens", "Ku Shen", "Antimikrobiyal, antiparaziter"],
    ["Syzygium aromaticum", "Karanfil", "Analjezik, antimikrobiyal"],
    ["Tanacetum parthenium", "Gümüş Düğme", "Migren profilaksisi"],
    ["Taraxacum officinale", "Karahindiba", "Diüretik, hepatoprotektif"],
    ["Terminalia arjuna", "Arjuna", "Kardiyotonik"],
    ["Terminalia bellirica", "Bibhitaki", "Ekspektoran, laksatif"],
    ["Terminalia chebula", "Haritaki", "Laksatif, antioksidan"],
    ["Thuja occidentalis", "Batı Mazısı", "Antiviral, immünostimülan"],
    ["Thymus vulgaris", "Kekik", "Antimikrobiyal, ekspektoran"],
    ["Tilia cordata", "Ihlamur", "Sedatif, diaforetik"],
    ["Tinospora cordifolia", "Guduchi", "İmmünomodülatör"],
    ["Tribulus terrestris", "Demir Dikeni", "Libido, performans"],
    ["Trichosanthes kirilowii", "Tian Hua Fen", "Ekspektoran, antiinflamatuar"],
    ["Trifolium pratense", "Kırmızı Yonca", "Fitoöstrojen, menopoz"],
    ["Trigonella foenum-graecum", "Çemen", "Antidiyabetik, galaktagog"],
    [
      "Tripterygium wilfordii",
      "Lei Gong Teng",
      "İmmünosupresif, antiinflamatuar",
    ],
    ["Tussilago farfara", "Öksürük Otu", "Ekspektoran, yatıştırıcı"],
    ["Uncaria rhynchophylla", "Gou Teng", "Antihipertansif, antikonvülzan"],
    ["Urtica dioica", "Isırgan", "Antiinflamatuar, BPH"],
    ["Vaccinium macrocarpon", "Turna Yemişi", "Üriner enfeksiyon"],
    ["Vaccinium myrtillus", "Yaban Mersini", "Antioksidan, göz sağlığı"],
    ["Valeriana officinalis", "Kediotu", "Sedatif, anksiyolitik"],
    ["Verbascum thapsus", "Sığır Kuyruğu", "Ekspektoran, yatıştırıcı"],
    ["Verbena officinalis", "Mine Çiçeği", "Sedatif, sindirim"],
    ["Viburnum opulus", "Gilaburu", "Antispazmodik, kadın sağlığı"],
    ["Viburnum prunifolium", "Siyah Haw", "Uterus gevşetici"],
    ["Vinca minor", "Küçük Cezayir Menekşesi", "Serebral dolaşım"],
    ["Viola tricolor", "Hercai Menekşe", "Cilt, ekspektoran"],
    ["Viscum album", "Ökse Otu", "Antihipertansif, antitümör"],
    ["Vitex agnus-castus", "Hayıt", "PMS, menstrüel düzensizlik"],
    ["Vitis vinifera", "Asma", "Antioksidan, venöz yetmezlik"],
    ["Withania somnifera", "Ashwagandha", "Adaptojenik, anksiyolitik"],
    ["Xanthium sibiricum", "Cang Er Zi", "Sinüzit, rinit"],
    ["Zanthoxylum bungeanum", "Hua Jiao", "Karminatif, analjezik"],
    ["Zingiber officinale", "Zencefil", "Antiemetik, antiinflamatuar"],
    ["Ziziphus jujuba", "Hünnap", "Sedatif, sindirim"],
  ];
  return plantList.map(([latin, turkish, def]) =>
    createTerm(latin, turkish, TermCategory.PLANT, def)
  );
};
// BİLEŞENLER - Kapsamlı liste
const generateComponents = () => {
  const componentList = [
    // Vitaminler ve kofaktörler
    ["Thiamine pyrophosphate", "Tiamin Pirofosfat", "TPP, B1 aktif formu"],
    [
      "Flavin adenine dinucleotide",
      "Flavin Adenin Dinükleotid",
      "FAD, B2 kofaktörü",
    ],
    ["Flavin mononucleotide", "Flavin Mononükleotid", "FMN, B2 kofaktörü"],
    [
      "Nicotinamide adenine dinucleotide",
      "Nikotinamid Adenin Dinükleotid",
      "NAD+, B3 kofaktörü",
    ],
    ["Coenzyme A", "Koenzim A", "CoA, B5 türevi"],
    ["Pyridoxal phosphate", "Piridoksal Fosfat", "PLP, B6 aktif formu"],
    ["Tetrahydrofolate", "Tetrahidrofolat", "THF, B9 aktif formu"],
    ["Methylcobalamin", "Metilkobalamin", "B12 aktif formu"],
    ["Adenosylcobalamin", "Adenozilkobalamin", "B12 aktif formu"],
    ["Biotin", "Biyotin", "B7, karboksilaz kofaktörü"],
    ["Lipoic acid", "Lipoik Asit", "Mitokondriyal kofaktör"],
    ["Ubiquinone", "Ubikinon", "Koenzim Q10"],
    ["Ubiquinol", "Ubikinol", "Redükte CoQ10"],
    ["Pyrroloquinoline quinone", "Pirolokinolin Kinon", "PQQ, antioksidan"],
    // Mineraller ve eser elementler
    ["Heme iron", "Hem Demiri", "Hemoglobin demiri"],
    ["Non-heme iron", "Hem Olmayan Demir", "Bitkisel demir"],
    ["Ferritin", "Ferritin", "Demir depo proteini"],
    ["Transferrin", "Transferrin", "Demir taşıyıcı protein"],
    ["Ceruloplasmin", "Seruloplazmin", "Bakır taşıyıcı protein"],
    ["Metallothionein", "Metalotiyonein", "Metal bağlayıcı protein"],
    ["Selenoprotein", "Selenoprotein", "Selenyum içeren protein"],
    ["Zinc finger protein", "Çinko Parmak Proteini", "DNA bağlayıcı protein"],
    // Lipidler
    ["Phosphatidylcholine", "Fosfatidilkolin", "Lesitin, membran lipidi"],
    ["Phosphatidylethanolamine", "Fosfatidiletanolamin", "Membran lipidi"],
    ["Phosphatidylserine", "Fosfatidilserin", "Membran lipidi, beyin"],
    ["Phosphatidylinositol", "Fosfatidilinositol", "Sinyal lipidi"],
    ["Sphingomyelin", "Sfingomiyelin", "Miyelin lipidi"],
    ["Ceramide", "Seramid", "Sfingolipid"],
    ["Ganglioside", "Gangliozid", "Sinir dokusu lipidi"],
    ["Cholesterol", "Kolesterol", "Membran lipidi, steroid öncüsü"],
    ["Bile acids", "Safra Asitleri", "Kolesterol türevleri"],
    ["Cholic acid", "Kolik Asit", "Primer safra asidi"],
    ["Chenodeoxycholic acid", "Kenodeoksikolik Asit", "Primer safra asidi"],
    ["Deoxycholic acid", "Deoksikolik Asit", "Sekonder safra asidi"],
    ["Lithocholic acid", "Litokolik Asit", "Sekonder safra asidi"],
    // Karbonhidratlar
    ["Glucose", "Glukoz", "Kan şekeri"],
    ["Fructose", "Fruktoz", "Meyve şekeri"],
    ["Galactose", "Galaktoz", "Süt şekeri bileşeni"],
    ["Mannose", "Mannoz", "Glikoprotein bileşeni"],
    ["Ribose", "Riboz", "RNA şekeri"],
    ["Deoxyribose", "Deoksiriboz", "DNA şekeri"],
    ["Sucrose", "Sukroz", "Sofra şekeri"],
    ["Lactose", "Laktoz", "Süt şekeri"],
    ["Maltose", "Maltoz", "Malt şekeri"],
    ["Glycogen", "Glikojen", "Hayvansal nişasta"],
    ["Starch", "Nişasta", "Bitkisel polisakkarit"],
    ["Cellulose", "Selüloz", "Bitkisel lif"],
    ["Chitin", "Kitin", "Böcek ve mantar polisakkariti"],
    ["Hyaluronic acid", "Hiyaluronik Asit", "Eklem sıvısı, cilt"],
    ["Chondroitin sulfate", "Kondroitin Sülfat", "Kıkırdak bileşeni"],
    ["Glucosamine", "Glukozamin", "Kıkırdak öncüsü"],
    // Amino asitler ve türevleri
    ["Glutathione", "Glutatyon", "Antioksidan tripeptid"],
    ["Carnitine", "Karnitin", "Yağ asidi taşıyıcı"],
    ["Creatine", "Kreatin", "Enerji deposu"],
    ["Taurine", "Taurin", "Safra asidi konjugasyonu"],
    ["Carnosine", "Karnozin", "Antioksidan dipeptid"],
    ["Anserine", "Anserin", "Antioksidan dipeptid"],
    ["Citrulline", "Sitrulin", "Üre döngüsü ara ürünü"],
    ["Ornithine", "Ornitin", "Üre döngüsü ara ürünü"],
    ["Homocysteine", "Homosistein", "Metiyonin metaboliti"],
    ["S-adenosylmethionine", "S-Adenozilmetiyonin", "SAMe, metil donörü"],
    [
      "Gamma-aminobutyric acid",
      "Gama-Aminobütirik Asit",
      "GABA, inhibitör nörotransmitter",
    ],
    ["Dopamine", "Dopamin", "Katekolamin nörotransmitter"],
    ["Norepinephrine", "Norepinefrin", "Katekolamin nörotransmitter"],
    ["Epinephrine", "Epinefrin", "Adrenalin"],
    ["Serotonin", "Serotonin", "5-HT, nörotransmitter"],
    ["Melatonin", "Melatonin", "Uyku hormonu"],
    ["Histamine", "Histamin", "Biyojenik amin"],
    ["Acetylcholine", "Asetilkolin", "Kolinerjik nörotransmitter"],
    // Nükleotidler ve türevleri
    ["Adenosine triphosphate", "Adenozin Trifosfat", "ATP, enerji para birimi"],
    ["Adenosine diphosphate", "Adenozin Difosfat", "ADP"],
    ["Adenosine monophosphate", "Adenozin Monofosfat", "AMP"],
    ["Cyclic AMP", "Siklik AMP", "cAMP, ikincil haberci"],
    ["Cyclic GMP", "Siklik GMP", "cGMP, ikincil haberci"],
    ["Guanosine triphosphate", "Guanozin Trifosfat", "GTP"],
    ["Nicotinamide adenine dinucleotide phosphate", "NADP", "NADPH öncüsü"],
    // Hormonlar ve sinyal molekülleri
    ["Insulin", "İnsülin", "Kan şekeri düzenleyici"],
    ["Glucagon", "Glukagon", "Kan şekeri yükseltici"],
    ["Cortisol", "Kortizol", "Stres hormonu"],
    ["Aldosterone", "Aldosteron", "Mineralokortikoid"],
    ["Testosterone", "Testosteron", "Androjen"],
    ["Estradiol", "Estradiol", "Östrojen"],
    ["Progesterone", "Progesteron", "Gebelik hormonu"],
    ["Thyroxine", "Tiroksin", "T4, tiroid hormonu"],
    ["Triiodothyronine", "Triiyodotironin", "T3, aktif tiroid hormonu"],
    ["Growth hormone", "Büyüme Hormonu", "Somatotropin"],
    ["Prolactin", "Prolaktin", "Süt üretimi"],
    ["Oxytocin", "Oksitosin", "Bağlanma hormonu"],
    ["Vasopressin", "Vazopressin", "ADH, antidiüretik hormon"],
    ["Parathyroid hormone", "Paratiroid Hormonu", "PTH, kalsiyum düzenleyici"],
    ["Calcitonin", "Kalsitonin", "Kalsiyum düşürücü"],
    ["Erythropoietin", "Eritropoietin", "EPO, kırmızı kan hücresi üretimi"],
    ["Thrombopoietin", "Trombopoietin", "Trombosit üretimi"],
    // Prostaglandinler ve eikosanoidler
    ["Prostaglandin E2", "Prostaglandin E2", "PGE2, inflamasyon"],
    [
      "Prostaglandin F2alpha",
      "Prostaglandin F2alfa",
      "PGF2α, uterus kasılması",
    ],
    ["Prostacyclin", "Prostasiklin", "PGI2, vazodilatör"],
    ["Thromboxane A2", "Tromboksan A2", "TXA2, trombosit agregasyonu"],
    ["Leukotriene B4", "Lökotrien B4", "LTB4, kemotaksis"],
    ["Leukotriene C4", "Lökotrien C4", "LTC4, bronkokonstrüksiyon"],
  ];
  return componentList.map(([latin, turkish, def]) =>
    createTerm(latin, turkish, TermCategory.COMPONENT, def)
  );
};
// VİTAMİNLER - Kapsamlı liste
const generateVitamins = () => {
  const vitaminList = [
    ["Retinol", "Retinol", "A vitamini aktif formu"],
    ["Retinal", "Retinal", "A vitamini aldehit formu"],
    ["Retinoic acid", "Retinoik Asit", "A vitamini asit formu"],
    ["Beta-carotene", "Beta-Karoten", "Provitamin A"],
    ["Alpha-carotene", "Alfa-Karoten", "Provitamin A"],
    ["Cryptoxanthin", "Kriptoksantin", "Provitamin A"],
    ["Thiamine", "Tiamin", "B1 vitamini"],
    ["Riboflavin", "Riboflavin", "B2 vitamini"],
    ["Niacin", "Niasin", "B3 vitamini"],
    ["Nicotinamide", "Nikotinamid", "B3 vitamini amid formu"],
    ["Pantothenic acid", "Pantotenik Asit", "B5 vitamini"],
    ["Pyridoxine", "Piridoksin", "B6 vitamini"],
    ["Pyridoxal", "Piridoksal", "B6 vitamini aldehit formu"],
    ["Pyridoxamine", "Piridoksamin", "B6 vitamini amin formu"],
    ["Biotin", "Biyotin", "B7 vitamini"],
    ["Folic acid", "Folik Asit", "B9 vitamini"],
    ["Folate", "Folat", "B9 vitamini doğal formu"],
    ["Methylfolate", "Metilfolat", "B9 vitamini aktif formu"],
    ["Cyanocobalamin", "Siyanokobalamin", "B12 vitamini"],
    ["Hydroxocobalamin", "Hidroksokobalamin", "B12 vitamini"],
    ["Ascorbic acid", "Askorbik Asit", "C vitamini"],
    ["Dehydroascorbic acid", "Dehidroaskorbik Asit", "C vitamini okside formu"],
    ["Cholecalciferol", "Kolekalsiferol", "D3 vitamini"],
    ["Ergocalciferol", "Ergokalsiferol", "D2 vitamini"],
    ["Calcidiol", "Kalsidiol", "25-OH D vitamini"],
    ["Calcitriol", "Kalsitriol", "1,25-OH D vitamini aktif formu"],
    ["Alpha-tocopherol", "Alfa-Tokoferol", "E vitamini"],
    ["Beta-tocopherol", "Beta-Tokoferol", "E vitamini"],
    ["Gamma-tocopherol", "Gama-Tokoferol", "E vitamini"],
    ["Delta-tocopherol", "Delta-Tokoferol", "E vitamini"],
    ["Alpha-tocotrienol", "Alfa-Tokotrienol", "E vitamini"],
    ["Phylloquinone", "Fillokinon", "K1 vitamini"],
    ["Menaquinone", "Menakinon", "K2 vitamini"],
    ["Menadione", "Menadion", "K3 vitamini"],
    ["Choline", "Kolin", "B vitamini benzeri"],
    ["Inositol", "İnositol", "B vitamini benzeri"],
    ["Para-aminobenzoic acid", "Para-Aminobenzoik Asit", "PABA"],
    ["Lipoic acid", "Lipoik Asit", "Alfa-lipoik asit"],
    ["Coenzyme Q10", "Koenzim Q10", "Ubikinon"],
    ["Pyrroloquinoline quinone", "Pirolokinolin Kinon", "PQQ"],
  ];
  return vitaminList.map(([latin, turkish, def]) =>
    createTerm(latin, turkish, TermCategory.VITAMIN, def)
  );
};

// MİNERALLER - Kapsamlı liste
const generateMinerals = () => {
  const mineralList = [
    ["Calcium carbonate", "Kalsiyum Karbonat", "Kalsiyum kaynağı"],
    ["Calcium citrate", "Kalsiyum Sitrat", "Kalsiyum kaynağı"],
    ["Calcium phosphate", "Kalsiyum Fosfat", "Kemik minerali"],
    ["Calcium gluconate", "Kalsiyum Glukonat", "IV kalsiyum"],
    ["Magnesium oxide", "Magnezyum Oksit", "Magnezyum kaynağı"],
    ["Magnesium citrate", "Magnezyum Sitrat", "Magnezyum kaynağı"],
    ["Magnesium sulfate", "Magnezyum Sülfat", "Epsom tuzu"],
    ["Magnesium chloride", "Magnezyum Klorür", "Magnezyum kaynağı"],
    ["Magnesium glycinate", "Magnezyum Glisinat", "Magnezyum kaynağı"],
    ["Potassium chloride", "Potasyum Klorür", "Potasyum kaynağı"],
    ["Potassium citrate", "Potasyum Sitrat", "Potasyum kaynağı"],
    ["Potassium gluconate", "Potasyum Glukonat", "Potasyum kaynağı"],
    ["Sodium chloride", "Sodyum Klorür", "Sofra tuzu"],
    ["Sodium bicarbonate", "Sodyum Bikarbonat", "Kabartma tozu"],
    ["Ferrous sulfate", "Demir Sülfat", "Demir kaynağı"],
    ["Ferrous gluconate", "Demir Glukonat", "Demir kaynağı"],
    ["Ferrous fumarate", "Demir Fumarat", "Demir kaynağı"],
    ["Ferric citrate", "Demir Sitrat", "Demir kaynağı"],
    ["Iron dextran", "Demir Dekstran", "IV demir"],
    ["Iron sucrose", "Demir Sukroz", "IV demir"],
    ["Ferric carboxymaltose", "Demir Karboksimaltoz", "IV demir"],
    ["Zinc sulfate", "Çinko Sülfat", "Çinko kaynağı"],
    ["Zinc gluconate", "Çinko Glukonat", "Çinko kaynağı"],
    ["Zinc picolinate", "Çinko Pikolinat", "Çinko kaynağı"],
    ["Zinc acetate", "Çinko Asetat", "Çinko kaynağı"],
    ["Copper sulfate", "Bakır Sülfat", "Bakır kaynağı"],
    ["Copper gluconate", "Bakır Glukonat", "Bakır kaynağı"],
    ["Manganese sulfate", "Manganez Sülfat", "Manganez kaynağı"],
    ["Manganese gluconate", "Manganez Glukonat", "Manganez kaynağı"],
    ["Selenium selenite", "Selenyum Selenit", "Selenyum kaynağı"],
    ["Selenium selenate", "Selenyum Selenat", "Selenyum kaynağı"],
    ["Selenomethionine", "Selenometiyonin", "Organik selenyum"],
    ["Chromium picolinate", "Krom Pikolinat", "Krom kaynağı"],
    ["Chromium chloride", "Krom Klorür", "Krom kaynağı"],
    ["Molybdenum", "Molibden", "Eser element"],
    ["Iodine", "İyot", "Tiroid için gerekli"],
    ["Potassium iodide", "Potasyum İyodür", "İyot kaynağı"],
    ["Boron", "Bor", "Eser element"],
    ["Silicon", "Silikon", "Eser element"],
    ["Vanadium", "Vanadyum", "Eser element"],
  ];
  return mineralList.map(([latin, turkish, def]) =>
    createTerm(latin, turkish, TermCategory.MINERAL, def)
  );
};
// BÖCEKLER - Kapsamlı liste
const generateInsects = () => {
  const insectList = [
    ["Apis mellifera", "Bal Arısı", "Polinatör, bal üretimi"],
    ["Bombus terrestris", "Toprak Yaban Arısı", "Polinatör"],
    ["Vespa crabro", "Eşek Arısı", "Yırtıcı böcek"],
    ["Vespula germanica", "Alman Eşek Arısı", "Zararlı böcek"],
    ["Formica rufa", "Kırmızı Orman Karıncası", "Orman ekosistemi"],
    ["Camponotus herculeanus", "Dev Marangoz Karıncası", "Ahşap zararlısı"],
    ["Solenopsis invicta", "Ateş Karıncası", "İstilacı tür"],
    ["Musca domestica", "Ev Sineği", "Hastalık vektörü"],
    ["Drosophila melanogaster", "Meyve Sineği", "Model organizma"],
    ["Glossina morsitans", "Çeçe Sineği", "Uyku hastalığı vektörü"],
    ["Aedes aegypti", "Sarı Humma Sivrisineği", "Dang, Zika vektörü"],
    ["Aedes albopictus", "Asya Kaplan Sivrisineği", "Hastalık vektörü"],
    ["Anopheles gambiae", "Afrika Sıtma Sivrisineği", "Sıtma vektörü"],
    ["Culex pipiens", "Ev Sivrisineği", "Batı Nil vektörü"],
    ["Phlebotomus papatasi", "Kum Sineği", "Leishmaniasis vektörü"],
    ["Simulium damnosum", "Kara Sinek", "Onkoserkiyaz vektörü"],
    ["Cimex lectularius", "Yatak Böceği", "Kan emici parazit"],
    ["Pediculus humanus capitis", "Baş Biti", "Ektoparazit"],
    ["Pediculus humanus corporis", "Vücut Biti", "Tifüs vektörü"],
    ["Phthirus pubis", "Kasık Biti", "Ektoparazit"],
    ["Pulex irritans", "İnsan Piresi", "Ektoparazit"],
    ["Ctenocephalides felis", "Kedi Piresi", "Ektoparazit"],
    ["Ctenocephalides canis", "Köpek Piresi", "Ektoparazit"],
    ["Xenopsylla cheopis", "Doğu Sıçan Piresi", "Veba vektörü"],
    ["Sarcoptes scabiei", "Uyuz Akarı", "Uyuz etkeni"],
    ["Demodex folliculorum", "Kıl Folikülü Akarı", "Deri paraziti"],
    ["Dermatophagoides pteronyssinus", "Ev Tozu Akarı", "Alerjen"],
    ["Ixodes scapularis", "Geyik Kenesi", "Lyme hastalığı vektörü"],
    ["Ixodes ricinus", "Koyun Kenesi", "Lyme hastalığı vektörü"],
    ["Dermacentor variabilis", "Amerikan Köpek Kenesi", "RMSF vektörü"],
    ["Amblyomma americanum", "Yalnız Yıldız Kenesi", "Ehrlichiosis vektörü"],
    [
      "Rhipicephalus sanguineus",
      "Kahverengi Köpek Kenesi",
      "Babesiosis vektörü",
    ],
    ["Blattella germanica", "Alman Hamamböceği", "Ev zararlısı"],
    ["Periplaneta americana", "Amerikan Hamamböceği", "Ev zararlısı"],
    ["Blatta orientalis", "Doğu Hamamböceği", "Ev zararlısı"],
    ["Tribolium castaneum", "Kırmızı Un Böceği", "Depo zararlısı"],
    ["Sitophilus granarius", "Buğday Biti", "Tahıl zararlısı"],
    ["Tenebrio molitor", "Un Kurdu", "Depo zararlısı"],
    ["Dermestes lardarius", "Larder Böceği", "Depo zararlısı"],
    ["Anthrenus verbasci", "Halı Böceği", "Tekstil zararlısı"],
    ["Leptinotarsa decemlineata", "Patates Böceği", "Tarım zararlısı"],
    ["Diabrotica virgifera", "Mısır Kök Kurdu", "Tarım zararlısı"],
    ["Ostrinia nubilalis", "Avrupa Mısır Kurdu", "Tarım zararlısı"],
    ["Helicoverpa armigera", "Pamuk Kurdu", "Tarım zararlısı"],
    ["Spodoptera frugiperda", "Güz Tırtılı", "Tarım zararlısı"],
    ["Plutella xylostella", "Lahana Güvesi", "Tarım zararlısı"],
    ["Tineola bisselliella", "Elbise Güvesi", "Tekstil zararlısı"],
    ["Ephestia kuehniella", "Akdeniz Un Güvesi", "Depo zararlısı"],
    ["Plodia interpunctella", "Hint Un Güvesi", "Depo zararlısı"],
    ["Locusta migratoria", "Göçmen Çekirge", "Tarım zararlısı"],
  ];
  return insectList.map(([latin, turkish, def]) =>
    createTerm(latin, turkish, TermCategory.INSECT, def)
  );
};
// Ana fonksiyon
async function main() {
  console.log("🚀 Massive Terim Yükleme Başlıyor...\n");
  console.log("═".repeat(50));

  console.log("📝 Terimler oluşturuluyor...");

  const drugs = generateDrugs();
  const diseases = generateDiseases();
  const anatomy = generateAnatomy();
  const plants = generatePlants();
  const components = generateComponents();
  const vitamins = generateVitamins();
  const minerals = generateMinerals();
  const insects = generateInsects();

  const allTerms = [
    ...drugs,
    ...diseases,
    ...anatomy,
    ...plants,
    ...components,
    ...vitamins,
    ...minerals,
    ...insects,
  ];

  console.log(`\n📊 Oluşturulan terim sayıları:`);
  console.log(`   İlaçlar: ${drugs.length}`);
  console.log(`   Hastalıklar: ${diseases.length}`);
  console.log(`   Anatomi: ${anatomy.length}`);
  console.log(`   Bitkiler: ${plants.length}`);
  console.log(`   Bileşenler: ${components.length}`);
  console.log(`   Vitaminler: ${vitamins.length}`);
  console.log(`   Mineraller: ${minerals.length}`);
  console.log(`   Böcekler: ${insects.length}`);
  console.log(`   ─────────────────────`);
  console.log(`   TOPLAM: ${allTerms.length} terim\n`);

  console.log("🔍 Mevcut terimler kontrol ediliyor...");
  const termsRef = collection(db, "terms");
  const existingSnapshot = await getDocs(termsRef);
  const existingTerms = new Set();

  existingSnapshot.docs.forEach((doc) => {
    const data = doc.data();
    existingTerms.add(data.latinName?.toLowerCase());
    existingTerms.add(data.turkishName?.toLowerCase());
  });

  console.log(`   Mevcut terim sayısı: ${existingSnapshot.size}`);

  const newTerms = allTerms.filter((term) => {
    const latinLower = term.latinName?.toLowerCase();
    const turkishLower = term.turkishName?.toLowerCase();
    return !existingTerms.has(latinLower) && !existingTerms.has(turkishLower);
  });

  console.log(`   Yeni eklenecek terim sayısı: ${newTerms.length}\n`);

  if (newTerms.length === 0) {
    console.log("✅ Tüm terimler zaten mevcut.");
    process.exit(0);
  }

  const BATCH_SIZE = 400;
  let uploadedCount = 0;
  let batchNumber = 1;

  console.log("📤 Firebase'e yükleme başlıyor...\n");

  for (let i = 0; i < newTerms.length; i += BATCH_SIZE) {
    const batch = writeBatch(db);
    const batchTerms = newTerms.slice(i, i + BATCH_SIZE);

    for (const term of batchTerms) {
      const docRef = doc(collection(db, "terms"));
      batch.set(docRef, {
        ...term,
        createdAt: new Date(),
        updatedAt: new Date(),
        isBookmarked: false,
      });
    }

    try {
      await batch.commit();
      uploadedCount += batchTerms.length;
      console.log(
        `   ✅ Batch ${batchNumber}: ${batchTerms.length} terim yüklendi (Toplam: ${uploadedCount}/${newTerms.length})`
      );
      batchNumber++;
      await new Promise((resolve) => setTimeout(resolve, 500));
    } catch (error) {
      console.error(`   ❌ Batch ${batchNumber} hatası:`, error.message);
    }
  }

  console.log("\n" + "═".repeat(50));
  console.log("📊 YÜKLEME TAMAMLANDI");
  console.log("═".repeat(50));
  console.log(`   Önceki terim sayısı: ${existingSnapshot.size}`);
  console.log(`   Yeni eklenen: ${uploadedCount}`);
  console.log(
    `   Toplam terim sayısı: ${existingSnapshot.size + uploadedCount}`
  );
  console.log("═".repeat(50) + "\n");

  process.exit(0);
}

main().catch((error) => {
  console.error("❌ Hata:", error);
  process.exit(1);
});
