#!/usr/bin/env python3
"""
Pharmacy Data Generator
Her kategoriye 100'er gerçekçi ve doğru veri ekler
"""

import json
import random
from datetime import datetime, timedelta

def generate_drugs():
    """İlaçlar kategorisi için 100 veri"""
    drugs = [
        {"latinName": "Aspirin", "turkishName": "Aspirin", "definition": "Nonsteroidal anti-inflamatuar ilaç (NSAID). Ağrı, ateş ve inflamasyon tedavisinde kullanılır. Kardiyovasküler koruma için düşük dozda kullanılır.", "components": ["Asetilsalisilik asit"], "usage": "Günde 1-4 kez, yemeklerden sonra alınmalıdır. Kardiyovasküler koruma için 75-100 mg, ağrı için 300-600 mg.", "sideEffects": ["Mide kanaması", "Mide ülseri", "Alerjik reaksiyonlar", "Astım atağı"], "interactions": ["Warfarin ile kanama riski", "Metotreksat toksisitesi", "ACE inhibitörleri ile birlikte dikkatli"], "synonyms": ["ASA", "Acetylsalicylic acid", "Asetilsalisilik asit"]},
        {"latinName": "Lisinopril", "turkishName": "Lisinopril", "definition": "ACE inhibitörü. Yüksek tansiyon, kalp yetmezliği ve böbrek koruması için kullanılır.", "components": ["Lisinopril dihidrat"], "usage": "Günde 1 kez, sabah veya akşam alınabilir. Dozaj 5-40 mg arasında değişir.", "sideEffects": ["Öksürük", "Baş dönmesi", "Yorgunluk", "Hiperkalemi"], "interactions": ["Potasyum tutucu diüretikler ile hiperkalemi riski", "Lityum toksisitesi"], "synonyms": ["Prinivil", "Zestril", "Lisinopril"]},
        {"latinName": "Simvastatin", "turkishName": "Simvastatin", "definition": "HMG-CoA redüktaz inhibitörü (statin). Kolesterol düşürücü ve kardiyovasküler koruma sağlar.", "components": ["Simvastatin"], "usage": "Günde 1 kez, akşam yemeğinden sonra alınmalıdır. Dozaj 10-80 mg arasında değişir.", "sideEffects": ["Kas ağrıları", "Karaciğer enzim yükselmesi", "Rabdomiyoliz (nadir)", "Baş ağrısı"], "interactions": ["Greyfurt suyu ile ciddi etkileşim", "Eritromisin ile kas hasarı riski", "Verapamil ile dikkatli"], "synonyms": ["Zocor", "Simva", "Simvastatin"]},
        {"latinName": "Metoprolol", "turkishName": "Metoprolol", "definition": "Beta bloker. Yüksek tansiyon, kalp ritim bozuklukları ve kalp yetmezliği tedavisinde kullanılır.", "components": ["Metoprolol tartarat", "Metoprolol süksinat"], "usage": "Günde 1-2 kez, yemeklerle birlikte alınabilir. Dozaj 25-200 mg arasında değişir.", "sideEffects": ["Yorgunluk", "Soğuk el ve ayaklar", "Nabız düşüklüğü", "Baş dönmesi"], "interactions": ["Kalsiyum kanal blokerleri ile birlikte dikkatli", "İnsülin ile hipoglisemi maskeleyebilir"], "synonyms": ["Lopressor", "Toprol", "Metoprolol"]},
        {"latinName": "Atenolol", "turkishName": "Atenolol", "definition": "Seçici beta-1 bloker. Yüksek tansiyon ve kalp ritim bozuklukları tedavisinde kullanılır.", "components": ["Atenolol"], "usage": "Günde 1-2 kez, yemeklerle birlikte alınabilir. Dozaj 25-100 mg arasında değişir.", "sideEffects": ["Yorgunluk", "Soğuk el ve ayaklar", "Nabız düşüklüğü", "Baş dönmesi"], "interactions": ["Kalsiyum kanal blokerleri ile birlikte dikkatli", "İnsülin ile hipoglisemi maskeleyebilir"], "synonyms": ["Tenormin", "Atenolol", "Aten"]},
        {"latinName": "Furosemide", "turkishName": "Furosemid", "definition": "Loop diüretik. Ödem, yüksek tansiyon ve kalp yetmezliği tedavisinde kullanılır.", "components": ["Furosemid"], "usage": "Günde 1-2 kez, sabah ve öğleden sonra alınmalıdır. Dozaj 20-160 mg arasında değişir.", "sideEffects": ["Dehidratasyon", "Elektrolit dengesizliği", "İşitme kaybı (yüksek dozda)", "Gut atağı"], "interactions": ["Digoksin toksisitesi riski", "Aminoglikozidler ile işitme kaybı riski", "Lityum toksisitesi"], "synonyms": ["Lasix", "Furosemid", "Furix"]},
        {"latinName": "Hydrochlorothiazide", "turkishName": "Hidroklorotiyazid", "definition": "Tiazid diüretik. Yüksek tansiyon ve ödem tedavisinde kullanılır.", "components": ["Hidroklorotiyazid"], "usage": "Günde 1 kez, sabah alınmalıdır. Dozaj 12.5-50 mg arasında değişir.", "sideEffects": ["Elektrolit dengesizliği", "Gut atağı", "Fotosensitivite", "Baş dönmesi"], "interactions": ["Lityum toksisitesi", "Digoksin toksisitesi riski", "NSAID'ler ile etkisizlik"], "synonyms": ["HCTZ", "Hydrochlorothiazide", "Esidrex"]},
        {"latinName": "Warfarin", "turkishName": "Varfarin", "definition": "Oral antikoagülan. Kan pıhtılaşmasını önleyerek tromboembolik olayları önler.", "components": ["Varfarin sodyum"], "usage": "Günde 1 kez, aynı saatte alınmalıdır. Dozaj INR değerine göre ayarlanır (genellikle 2-10 mg).", "sideEffects": ["Kanama riski", "Cilt nekrozu (nadir)", "Purpura", "Saç dökülmesi"], "interactions": ["Birçok ilaç ve besinle etkileşim", "K vitamini içeren besinler etkisini azaltır", "Aspirin ile kanama riski artar"], "synonyms": ["Coumadin", "Warfarin", "Marevan"]},
        {"latinName": "Digoxin", "turkishName": "Digoksin", "definition": "Kardiyak glikozit. Kalp yetmezliği ve atriyal fibrilasyon tedavisinde kullanılır.", "components": ["Digoksin"], "usage": "Günde 1 kez, aynı saatte alınmalıdır. Dozaj 0.125-0.5 mg arasında değişir.", "sideEffects": ["Bulantı", "Kusma", "Görme bozukluğu", "Kalp ritim bozuklukları (toksisitede)"], "interactions": ["Amiodaron ile toksisite riski", "Diüretikler ile hipokalemi riski", "Kinolon antibiyotikler ile toksisite"], "synonyms": ["Lanoxin", "Digoksin", "Cardoxin"]},
        {"latinName": "Clopidogrel", "turkishName": "Klopidogrel", "definition": "Trombosit agregasyon inhibitörü. Kardiyovasküler olayları önlemek için kullanılır.", "components": ["Klopidogrel bisülfat"], "usage": "Günde 1 kez, yemeklerle birlikte veya aç karnına alınabilir. Standart doz 75 mg'dır.", "sideEffects": ["Kanama riski", "Purpura", "Trombositopeni (nadir)", "Gastrointestinal yan etkiler"], "interactions": ["Warfarin ile kanama riski", "Proton pompa inhibitörleri etkinliği azaltabilir", "Aspirin ile birlikte kullanılır"], "synonyms": ["Plavix", "Clopidogrel", "Clopilet"]},
    ]
    
    # Daha fazla ilaç ekle (100'e tamamla)
    additional_drugs = [
        {"latinName": "Ramipril", "turkishName": "Ramipril", "definition": "ACE inhibitörü. Yüksek tansiyon ve kardiyovasküler koruma için kullanılır.", "components": ["Ramipril"], "usage": "Günde 1-2 kez, dozaj 2.5-10 mg.", "sideEffects": ["Öksürük", "Baş dönmesi", "Hiperkalemi"], "interactions": ["Potasyum tutucu diüretikler"], "synonyms": ["Altace", "Ramipril"]},
        {"latinName": "Enalapril", "turkishName": "Enalapril", "definition": "ACE inhibitörü. Yüksek tansiyon ve kalp yetmezliği tedavisinde kullanılır.", "components": ["Enalapril maleat"], "usage": "Günde 1-2 kez, dozaj 5-40 mg.", "sideEffects": ["Öksürük", "Baş dönmesi"], "interactions": ["Potasyum tutucu diüretikler"], "synonyms": ["Vasotec", "Enalapril"]},
        {"latinName": "Captopril", "turkishName": "Kaptopril", "definition": "ACE inhibitörü. Yüksek tansiyon ve kalp yetmezliği tedavisinde kullanılır.", "components": ["Kaptopril"], "usage": "Günde 2-3 kez, aç karnına alınmalıdır. Dozaj 12.5-150 mg.", "sideEffects": ["Öksürük", "Döküntü", "Tat bozukluğu"], "interactions": ["Potasyum tutucu diüretikler"], "synonyms": ["Capoten", "Kaptopril"]},
        {"latinName": "Valsartan", "turkishName": "Valsartan", "definition": "Anjiyotensin II reseptör blokeri. Yüksek tansiyon ve kalp yetmezliği tedavisinde kullanılır.", "components": ["Valsartan"], "usage": "Günde 1-2 kez, dozaj 40-320 mg.", "sideEffects": ["Baş dönmesi", "Yorgunluk"], "interactions": ["Potasyum tutucu diüretikler"], "synonyms": ["Diovan", "Valsartan"]},
        {"latinName": "Telmisartan", "turkishName": "Telmisartan", "definition": "Anjiyotensin II reseptör blokeri. Yüksek tansiyon tedavisinde kullanılır.", "components": ["Telmisartan"], "usage": "Günde 1 kez, dozaj 20-80 mg.", "sideEffects": ["Baş dönmesi", "Yorgunluk"], "interactions": ["Potasyum tutucu diüretikler"], "synonyms": ["Micardis", "Telmisartan"]},
        {"latinName": "Olmesartan", "turkishName": "Olmesartan", "definition": "Anjiyotensin II reseptör blokeri. Yüksek tansiyon tedavisinde kullanılır.", "components": ["Olmesartan medoksomil"], "usage": "Günde 1 kez, dozaj 10-40 mg.", "sideEffects": ["Baş dönmesi", "Yorgunluk"], "interactions": ["Potasyum tutucu diüretikler"], "synonyms": ["Benicar", "Olmesartan"]},
        {"latinName": "Carvedilol", "turkishName": "Karvedilol", "definition": "Alfa ve beta bloker. Yüksek tansiyon ve kalp yetmezliği tedavisinde kullanılır.", "components": ["Karvedilol"], "usage": "Günde 2 kez, yemeklerle birlikte alınmalıdır. Dozaj 6.25-50 mg.", "sideEffects": ["Yorgunluk", "Baş dönmesi", "Nabız düşüklüğü"], "interactions": ["Kalsiyum kanal blokerleri"], "synonyms": ["Coreg", "Carvedilol"]},
        {"latinName": "Bisoprolol", "turkishName": "Bisoprolol", "definition": "Seçici beta-1 bloker. Yüksek tansiyon ve kalp yetmezliği tedavisinde kullanılır.", "components": ["Bisoprolol fumarat"], "usage": "Günde 1 kez, dozaj 2.5-10 mg.", "sideEffects": ["Yorgunluk", "Nabız düşüklüğü"], "interactions": ["Kalsiyum kanal blokerleri"], "synonyms": ["Zebeta", "Bisoprolol"]},
        {"latinName": "Nebivolol", "turkishName": "Nebivolol", "definition": "Seçici beta-1 bloker. Yüksek tansiyon tedavisinde kullanılır.", "components": ["Nebivolol hidroklorür"], "usage": "Günde 1 kez, dozaj 2.5-10 mg.", "sideEffects": ["Yorgunluk", "Nabız düşüklüğü"], "interactions": ["Kalsiyum kanal blokerleri"], "synonyms": ["Bystolic", "Nebivolol"]},
        {"latinName": "Propranolol", "turkishName": "Propranolol", "definition": "Non-selektif beta bloker. Yüksek tansiyon, migren ve anksiyete tedavisinde kullanılır.", "components": ["Propranolol hidroklorür"], "usage": "Günde 2-3 kez, dozaj 40-320 mg.", "sideEffects": ["Yorgunluk", "Soğuk el ve ayaklar"], "interactions": ["Kalsiyum kanal blokerleri"], "synonyms": ["Inderal", "Propranolol"]},
    ]
    
    # Mevcut 12 ilaç + 10 ek ilaç = 22, 78 daha ekle
    all_drugs = drugs + additional_drugs
    
    # 100'e tamamlamak için daha fazla ilaç ekle
    more_drugs = [
        {"latinName": "Amlodipine", "turkishName": "Amlodipin", "definition": "Kalsiyum kanal blokeri. Yüksek tansiyon ve koroner arter hastalığı tedavisinde kullanılır.", "components": ["Amlodipin besilat"], "usage": "Günde 1 kez, dozaj 5-10 mg.", "sideEffects": ["Ayak bileği ödemi", "Baş dönmesi"], "interactions": ["Greyfurt suyu"], "synonyms": ["Norvasc", "Amlodipin"]},
        {"latinName": "Diltiazem", "turkishName": "Diltiazem", "definition": "Kalsiyum kanal blokeri. Yüksek tansiyon ve kalp ritim bozuklukları tedavisinde kullanılır.", "components": ["Diltiazem hidroklorür"], "usage": "Günde 1-3 kez, dozaj 60-360 mg.", "sideEffects": ["Baş dönmesi", "Yüz kızarması"], "interactions": ["Beta blokerler"], "synonyms": ["Cardizem", "Diltiazem"]},
        {"latinName": "Verapamil", "turkishName": "Verapamil", "definition": "Kalsiyum kanal blokeri. Yüksek tansiyon ve kalp ritim bozuklukları tedavisinde kullanılır.", "components": ["Verapamil hidroklorür"], "usage": "Günde 2-3 kez, dozaj 80-480 mg.", "sideEffects": ["Kabızlık", "Baş dönmesi"], "interactions": ["Beta blokerler", "Digoksin"], "synonyms": ["Calan", "Verapamil"]},
        {"latinName": "Nifedipine", "turkishName": "Nifedipin", "definition": "Kalsiyum kanal blokeri. Yüksek tansiyon ve anjina tedavisinde kullanılır.", "components": ["Nifedipin"], "usage": "Günde 1-3 kez, dozaj 10-60 mg.", "sideEffects": ["Yüz kızarması", "Baş ağrısı"], "interactions": ["Greyfurt suyu"], "synonyms": ["Adalat", "Nifedipin"]},
        {"latinName": "Felodipine", "turkishName": "Felodipin", "definition": "Kalsiyum kanal blokeri. Yüksek tansiyon tedavisinde kullanılır.", "components": ["Felodipin"], "usage": "Günde 1 kez, dozaj 2.5-10 mg.", "sideEffects": ["Ayak bileği ödemi", "Baş ağrısı"], "interactions": ["Greyfurt suyu"], "synonyms": ["Plendil", "Felodipin"]},
    ]
    
    all_drugs.extend(more_drugs)
    
    # Antibiyotikler
    antibiotics = [
        {"latinName": "Azithromycin", "turkishName": "Azitromisin", "definition": "Makrolid antibiyotik. Solunum yolu ve cilt enfeksiyonlarında kullanılır.", "components": ["Azitromisin dihidrat"], "usage": "Günde 1 kez, yemeklerden 1 saat önce veya 2 saat sonra. Dozaj 250-500 mg.", "sideEffects": ["Mide bulantısı", "İshal", "Karın ağrısı"], "interactions": ["Warfarin", "Digoksin"], "synonyms": ["Zithromax", "Azitromisin"]},
        {"latinName": "Clarithromycin", "turkishName": "Klaritromisin", "definition": "Makrolid antibiyotik. Solunum yolu enfeksiyonlarında kullanılır.", "components": ["Klaritromisin"], "usage": "Günde 2 kez, yemeklerle birlikte. Dozaj 250-500 mg.", "sideEffects": ["Mide bulantısı", "İshal", "Tat bozukluğu"], "interactions": ["Warfarin", "Statınler"], "synonyms": ["Biaxin", "Klaritromisin"]},
        {"latinName": "Erythromycin", "turkishName": "Eritromisin", "definition": "Makrolid antibiyotik. Solunum yolu ve cilt enfeksiyonlarında kullanılır.", "components": ["Eritromisin"], "usage": "Günde 2-4 kez, yemeklerden önce. Dozaj 250-500 mg.", "sideEffects": ["Mide bulantısı", "İshal", "Karın ağrısı"], "interactions": ["Warfarin", "Statınler"], "synonyms": ["Erythrocin", "Eritromisin"]},
        {"latinName": "Doxycycline", "turkishName": "Doksasiklin", "definition": "Tetrasiklin antibiyotik. Geniş spektrumlu antibakteriyel etki gösterir.", "components": ["Doksasiklin hiklatt"], "usage": "Günde 1-2 kez, yemeklerle birlikte. Dozaj 100-200 mg.", "sideEffects": ["Fototoksisite", "Mide bulantısı", "Diş renklenmesi (çocuklarda)"], "interactions": ["Antasitler", "Demir preparatları"], "synonyms": ["Vibramycin", "Doksasiklin"]},
        {"latinName": "Tetracycline", "turkishName": "Tetrasiklin", "definition": "Tetrasiklin antibiyotik. Geniş spektrumlu antibakteriyel etki gösterir.", "components": ["Tetrasiklin hidroklorür"], "usage": "Günde 2-4 kez, aç karnına. Dozaj 250-500 mg.", "sideEffects": ["Fototoksisite", "Mide bulantısı", "Diş renklenmesi"], "interactions": ["Antasitler", "Demir preparatları"], "synonyms": ["Tetrasiklin", "Achromycin"]},
        {"latinName": "Cephalexin", "turkishName": "Sefaleksin", "definition": "Sefalosporin antibiyotik. Bakteriyel enfeksiyonların tedavisinde kullanılır.", "components": ["Sefaleksin monohidrat"], "usage": "Günde 2-4 kez, yemeklerle birlikte. Dozaj 250-1000 mg.", "sideEffects": ["İshal", "Mide bulantısı", "Alerjik reaksiyonlar"], "interactions": ["Probenesid"], "synonyms": ["Keflex", "Sefaleksin"]},
        {"latinName": "Cefuroxime", "turkishName": "Sefuroksim", "definition": "Sefalosporin antibiyotik. Solunum yolu enfeksiyonlarında kullanılır.", "components": ["Sefuroksim aksetil"], "usage": "Günde 2 kez, yemeklerle birlikte. Dozaj 250-500 mg.", "sideEffects": ["İshal", "Mide bulantısı"], "interactions": ["Probenesid"], "synonyms": ["Ceftin", "Sefuroksim"]},
        {"latinName": "Ceftriaxone", "turkishName": "Seftriakson", "definition": "Sefalosporin antibiyotik. Ciddi enfeksiyonların tedavisinde IV/IM kullanılır.", "components": ["Seftriakson sodyum"], "usage": "Günde 1-2 kez, IV/IM. Dozaj 1-2 g.", "sideEffects": ["İshal", "Alerjik reaksiyonlar", "Safra çamuru"], "interactions": ["Warfarin"], "synonyms": ["Rocephin", "Seftriakson"]},
        {"latinName": "Levofloxacin", "turkishName": "Levofloksasin", "definition": "Florokinolon antibiyotik. Geniş spektrumlu antibakteriyel etki gösterir.", "components": ["Levofloksasin"], "usage": "Günde 1 kez, aç karnına. Dozaj 250-750 mg.", "sideEffects": ["Tendon hasarı", "Fototoksisite", "Mide bulantısı"], "interactions": ["Antasitler", "Teofilin"], "synonyms": ["Levaquin", "Levofloksasin"]},
        {"latinName": "Moxifloxacin", "turkishName": "Moksifloksasin", "definition": "Florokinolon antibiyotik. Solunum yolu enfeksiyonlarında kullanılır.", "components": ["Moksifloksasin hidroklorür"], "usage": "Günde 1 kez, yemeklerle birlikte. Dozaj 400 mg.", "sideEffects": ["Tendon hasarı", "Fototoksisite", "QT uzaması"], "interactions": ["Antasitler"], "synonyms": ["Avelox", "Moksifloksasin"]},
    ]
    
    all_drugs.extend(antibiotics)
    
    # Antidepresanlar
    antidepressants = [
        {"latinName": "Fluoxetine", "turkishName": "Fluoksetin", "definition": "SSRI antidepresan. Depresyon, anksiyete ve obsesif-kompulsif bozukluk tedavisinde kullanılır.", "components": ["Fluoksetin hidroklorür"], "usage": "Günde 1 kez, sabah. Dozaj 20-80 mg.", "sideEffects": ["Mide bulantısı", "Uykusuzluk", "Cinsel işlev bozukluğu"], "interactions": ["MAO inhibitörleri", "Warfarin"], "synonyms": ["Prozac", "Fluoksetin"]},
        {"latinName": "Paroxetine", "turkishName": "Paroksetin", "definition": "SSRI antidepresan. Depresyon ve anksiyete tedavisinde kullanılır.", "components": ["Paroksetin hidroklorür"], "usage": "Günde 1 kez, sabah. Dozaj 20-50 mg.", "sideEffects": ["Mide bulantısı", "Uykusuzluk", "Cinsel işlev bozukluğu"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Paxil", "Paroksetin"]},
        {"latinName": "Citalopram", "turkishName": "Sitalopram", "definition": "SSRI antidepresan. Depresyon tedavisinde kullanılır.", "components": ["Sitalopram hidrobromür"], "usage": "Günde 1 kez, sabah veya akşam. Dozaj 20-40 mg.", "sideEffects": ["Mide bulantısı", "Uykusuzluk"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Celexa", "Sitalopram"]},
        {"latinName": "Escitalopram", "turkishName": "Essitalopram", "definition": "SSRI antidepresan. Depresyon ve anksiyete tedavisinde kullanılır.", "components": ["Essitalopram oksalat"], "usage": "Günde 1 kez, sabah veya akşam. Dozaj 10-20 mg.", "sideEffects": ["Mide bulantısı", "Uykusuzluk"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Lexapro", "Essitalopram"]},
        {"latinName": "Venlafaxine", "turkishName": "Venlafaksin", "definition": "SNRI antidepresan. Depresyon ve anksiyete tedavisinde kullanılır.", "components": ["Venlafaksin hidroklorür"], "usage": "Günde 1-2 kez, yemeklerle birlikte. Dozaj 37.5-225 mg.", "sideEffects": ["Mide bulantısı", "Uykusuzluk", "Yüksek tansiyon"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Effexor", "Venlafaksin"]},
        {"latinName": "Duloxetine", "turkishName": "Duloksetin", "definition": "SNRI antidepresan. Depresyon, anksiyete ve nöropatik ağrı tedavisinde kullanılır.", "components": ["Duloksetin hidroklorür"], "usage": "Günde 1-2 kez, yemeklerle birlikte. Dozaj 30-120 mg.", "sideEffects": ["Mide bulantısı", "Uykusuzluk", "Karaciğer hasarı"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Cymbalta", "Duloksetin"]},
        {"latinName": "Amitriptyline", "turkishName": "Amitriptilin", "definition": "Trisiklik antidepresan. Depresyon ve nöropatik ağrı tedavisinde kullanılır.", "components": ["Amitriptilin hidroklorür"], "usage": "Günde 1 kez, akşam. Dozaj 25-150 mg.", "sideEffects": ["Uyku hali", "Ağız kuruluğu", "Kabızlık"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Elavil", "Amitriptilin"]},
        {"latinName": "Nortriptyline", "turkishName": "Nortriptilin", "definition": "Trisiklik antidepresan. Depresyon tedavisinde kullanılır.", "components": ["Nortriptilin hidroklorür"], "usage": "Günde 1-3 kez. Dozaj 25-150 mg.", "sideEffects": ["Uyku hali", "Ağız kuruluğu"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Pamelor", "Nortriptilin"]},
        {"latinName": "Bupropion", "turkishName": "Bupropion", "definition": "Atipik antidepresan. Depresyon ve sigara bırakma tedavisinde kullanılır.", "components": ["Bupropion hidroklorür"], "usage": "Günde 1-2 kez. Dozaj 150-300 mg.", "sideEffects": ["Uykusuzluk", "Baş ağrısı", "Nöbet riski"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Wellbutrin", "Bupropion"]},
        {"latinName": "Mirtazapine", "turkishName": "Mirtazapin", "definition": "Atipik antidepresan. Depresyon tedavisinde kullanılır.", "components": ["Mirtazapin"], "usage": "Günde 1 kez, akşam. Dozaj 15-45 mg.", "sideEffects": ["Uyku hali", "İştah artışı", "Kilo alma"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Remeron", "Mirtazapin"]},
    ]
    
    all_drugs.extend(antidepressants)
    
    # Antikonvülzanlar
    anticonvulsants = [
        {"latinName": "Carbamazepine", "turkishName": "Karbamazepin", "definition": "Antikonvülzan ve duygudurum düzenleyici. Epilepsi ve bipolar bozukluk tedavisinde kullanılır.", "components": ["Karbamazepin"], "usage": "Günde 2-3 kez, yemeklerle birlikte. Dozaj 200-1200 mg.", "sideEffects": ["Baş dönmesi", "Uyku hali", "Cilt döküntüsü"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Tegretol", "Karbamazepin"]},
        {"latinName": "Phenytoin", "turkishName": "Fenitoin", "definition": "Antikonvülzan. Epilepsi tedavisinde kullanılır.", "components": ["Fenitoin sodyum"], "usage": "Günde 1-3 kez. Dozaj 100-400 mg.", "sideEffects": ["Diş eti büyümesi", "Hirsutizm", "Osteomalazi"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Dilantin", "Fenitoin"]},
        {"latinName": "Valproic Acid", "turkishName": "Valproik Asit", "definition": "Antikonvülzan ve duygudurum düzenleyici. Epilepsi ve bipolar bozukluk tedavisinde kullanılır.", "components": ["Valproik asit", "Valproat sodyum"], "usage": "Günde 2-3 kez, yemeklerle birlikte. Dozaj 500-2000 mg.", "sideEffects": ["Kilo alma", "Karaciğer hasarı", "Trombositopeni"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Depakote", "Valproik asit"]},
        {"latinName": "Lamotrigine", "turkishName": "Lamotrijin", "definition": "Antikonvülzan ve duygudurum düzenleyici. Epilepsi ve bipolar bozukluk tedavisinde kullanılır.", "components": ["Lamotrijin"], "usage": "Günde 1-2 kez. Dozaj 25-400 mg.", "sideEffects": ["Cilt döküntüsü", "Baş dönmesi"], "interactions": ["Valproat"], "synonyms": ["Lamictal", "Lamotrijin"]},
        {"latinName": "Levetiracetam", "turkishName": "Levetirasetam", "definition": "Antikonvülzan. Epilepsi tedavisinde kullanılır.", "components": ["Levetirasetam"], "usage": "Günde 2 kez. Dozaj 500-3000 mg.", "sideEffects": ["Yorgunluk", "Baş dönmesi", "Sinirlilik"], "interactions": ["Az"], "synonyms": ["Keppra", "Levetirasetam"]},
        {"latinName": "Topiramate", "turkishName": "Topiramat", "definition": "Antikonvülzan. Epilepsi ve migren tedavisinde kullanılır.", "components": ["Topiramat"], "usage": "Günde 2 kez. Dozaj 50-400 mg.", "sideEffects": ["Bilişsel yan etkiler", "Kilo kaybı", "Böbrek taşı"], "interactions": ["Oral kontraseptifler"], "synonyms": ["Topamax", "Topiramat"]},
        {"latinName": "Gabapentin", "turkishName": "Gabapentin", "definition": "Antikonvülzan ve nöropatik ağrı ilacı. Epilepsi ve nöropatik ağrı tedavisinde kullanılır.", "components": ["Gabapentin"], "usage": "Günde 3 kez. Dozaj 300-3600 mg.", "sideEffects": ["Yorgunluk", "Baş dönmesi", "Kilo alma"], "interactions": ["Antasitler"], "synonyms": ["Neurontin", "Gabapentin"]},
        {"latinName": "Pregabalin", "turkishName": "Pregabalin", "definition": "Antikonvülzan ve nöropatik ağrı ilacı. Nöropatik ağrı ve anksiyete tedavisinde kullanılır.", "components": ["Pregabalin"], "usage": "Günde 2-3 kez. Dozaj 75-600 mg.", "sideEffects": ["Yorgunluk", "Baş dönmesi", "Kilo alma"], "interactions": ["Az"], "synonyms": ["Lyrica", "Pregabalin"]},
        {"latinName": "Oxcarbazepine", "turkishName": "Okskarbazepin", "definition": "Antikonvülzan. Epilepsi tedavisinde kullanılır.", "components": ["Okskarbazepin"], "usage": "Günde 2 kez. Dozaj 300-2400 mg.", "sideEffects": ["Baş dönmesi", "Hiponatremi"], "interactions": ["Oral kontraseptifler"], "synonyms": ["Trileptal", "Okskarbazepin"]},
        {"latinName": "Zonisamide", "turkishName": "Zonisamid", "definition": "Antikonvülzan. Epilepsi tedavisinde kullanılır.", "components": ["Zonisamid"], "usage": "Günde 1-2 kez. Dozaj 100-600 mg.", "sideEffects": ["Bilişsel yan etkiler", "Böbrek taşı"], "interactions": ["Az"], "synonyms": ["Zonegran", "Zonisamid"]},
    ]
    
    all_drugs.extend(anticonvulsants)
    
    # Antipsikotikler
    antipsychotics = [
        {"latinName": "Risperidone", "turkishName": "Risperidon", "definition": "Atipik antipsikotik. Şizofreni ve bipolar bozukluk tedavisinde kullanılır.", "components": ["Risperidon"], "usage": "Günde 1-2 kez. Dozaj 1-6 mg.", "sideEffects": ["Kilo alma", "Prolaktin yükselmesi", "Ekstrapiramidal yan etkiler"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Risperdal", "Risperidon"]},
        {"latinName": "Olanzapine", "turkishName": "Olanzapin", "definition": "Atipik antipsikotik. Şizofreni ve bipolar bozukluk tedavisinde kullanılır.", "components": ["Olanzapin"], "usage": "Günde 1 kez, akşam. Dozaj 5-20 mg.", "sideEffects": ["Kilo alma", "Metabolik sendrom", "Uyku hali"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Zyprexa", "Olanzapin"]},
        {"latinName": "Quetiapine", "turkishName": "Ketiapin", "definition": "Atipik antipsikotik. Şizofreni, bipolar bozukluk ve depresyon tedavisinde kullanılır.", "components": ["Ketiapin fumarat"], "usage": "Günde 1-2 kez. Dozaj 25-800 mg.", "sideEffects": ["Uyku hali", "Kilo alma", "Baş dönmesi"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Seroquel", "Ketiapin"]},
        {"latinName": "Aripiprazole", "turkishName": "Aripiprazol", "definition": "Atipik antipsikotik. Şizofreni ve bipolar bozukluk tedavisinde kullanılır.", "components": ["Aripiprazol"], "usage": "Günde 1 kez. Dozaj 5-30 mg.", "sideEffects": ["Ajitasyon", "Baş ağrısı", "Uykusuzluk"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Abilify", "Aripiprazol"]},
        {"latinName": "Ziprasidone", "turkishName": "Ziprasidon", "definition": "Atipik antipsikotik. Şizofreni ve bipolar bozukluk tedavisinde kullanılır.", "components": ["Ziprasidon hidroklorür"], "usage": "Günde 2 kez, yemeklerle birlikte. Dozaj 40-160 mg.", "sideEffects": ["QT uzaması", "Baş dönmesi"], "interactions": ["QT uzatan ilaçlar"], "synonyms": ["Geodon", "Ziprasidon"]},
        {"latinName": "Haloperidol", "turkishName": "Haloperidol", "definition": "Tipik antipsikotik. Şizofreni ve akut psikoz tedavisinde kullanılır.", "components": ["Haloperidol"], "usage": "Günde 1-3 kez. Dozaj 1-20 mg.", "sideEffects": ["Ekstrapiramidal yan etkiler", "Prolaktin yükselmesi"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Haldol", "Haloperidol"]},
        {"latinName": "Chlorpromazine", "turkishName": "Klorpromazin", "definition": "Tipik antipsikotik. Şizofreni ve akut psikoz tedavisinde kullanılır.", "components": ["Klorpromazin hidroklorür"], "usage": "Günde 1-3 kez. Dozaj 25-800 mg.", "sideEffects": ["Uyku hali", "Ekstrapiramidal yan etkiler"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Thorazine", "Klorpromazin"]},
        {"latinName": "Clozapine", "turkishName": "Klozapin", "definition": "Atipik antipsikotik. Tedaviye dirençli şizofreni tedavisinde kullanılır.", "components": ["Klozapin"], "usage": "Günde 1-2 kez. Dozaj 25-900 mg.", "sideEffects": ["Agranülositoz", "Kardiyomiyopati", "Kilo alma"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Clozaril", "Klozapin"]},
        {"latinName": "Paliperidone", "turkishName": "Palipiridon", "definition": "Atipik antipsikotik. Şizofreni tedavisinde kullanılır.", "components": ["Palipiridon"], "usage": "Günde 1 kez. Dozaj 3-12 mg.", "sideEffects": ["Kilo alma", "Prolaktin yükselmesi"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Invega", "Palipiridon"]},
        {"latinName": "Lurasidone", "turkishName": "Lurasidon", "definition": "Atipik antipsikotik. Şizofreni ve bipolar bozukluk tedavisinde kullanılır.", "components": ["Lurasidon hidroklorür"], "usage": "Günde 1 kez, yemeklerle birlikte. Dozaj 20-160 mg.", "sideEffects": ["Uyku hali", "Mide bulantısı"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Latuda", "Lurasidon"]},
    ]
    
    all_drugs.extend(antipsychotics)
    
    # Şu anda ~82 ilaç var, 18 daha ekle
    remaining = 100 - len(all_drugs)
    
    # Diğer ilaç kategorileri
    other_drugs = [
        {"latinName": "Tramadol", "turkishName": "Tramadol", "definition": "Opioid analjezik. Orta-şiddetli ağrı tedavisinde kullanılır.", "components": ["Tramadol hidroklorür"], "usage": "Günde 2-4 kez. Dozaj 50-400 mg.", "sideEffects": ["Baş dönmesi", "Mide bulantısı", "Bağımlılık riski"], "interactions": ["SSRI'lar", "MAO inhibitörleri"], "synonyms": ["Ultram", "Tramadol"]},
        {"latinName": "Codeine", "turkishName": "Kodein", "definition": "Opioid analjezik ve öksürük kesici. Ağrı ve öksürük tedavisinde kullanılır.", "components": ["Kodein fosfat"], "usage": "Günde 3-4 kez. Dozaj 15-60 mg.", "sideEffects": ["Uyku hali", "Kabızlık", "Bağımlılık riski"], "interactions": ["Alkol", "Benzodiazepinler"], "synonyms": ["Kodein", "Codeine"]},
        {"latinName": "Morphine", "turkishName": "Morfin", "definition": "Güçlü opioid analjezik. Şiddetli ağrı tedavisinde kullanılır.", "components": ["Morfin sülfat"], "usage": "IV/IM/PO, dozaj ağrı şiddetine göre.", "sideEffects": ["Solunum depresyonu", "Uyku hali", "Bağımlılık riski"], "interactions": ["Alkol", "Benzodiazepinler"], "synonyms": ["Morfin", "Morphine"]},
        {"latinName": "Oxycodone", "turkishName": "Oksikodon", "definition": "Opioid analjezik. Orta-şiddetli ağrı tedavisinde kullanılır.", "components": ["Oksikodon hidroklorür"], "usage": "Günde 2-4 kez. Dozaj 5-80 mg.", "sideEffects": ["Uyku hali", "Kabızlık", "Bağımlılık riski"], "interactions": ["Alkol", "Benzodiazepinler"], "synonyms": ["OxyContin", "Oksikodon"]},
        {"latinName": "Fentanyl", "turkishName": "Fentanil", "definition": "Çok güçlü opioid analjezik. Şiddetli ağrı ve anestezi için kullanılır.", "components": ["Fentanil sitrat"], "usage": "IV/Transdermal/Patch, dozaj ağrı şiddetine göre.", "sideEffects": ["Solunum depresyonu", "Uyku hali", "Bağımlılık riski"], "interactions": ["Alkol", "Benzodiazepinler"], "synonyms": ["Duragesic", "Fentanil"]},
        {"latinName": "Hydrocodone", "turkishName": "Hidrokodon", "definition": "Opioid analjezik ve öksürük kesici. Ağrı ve öksürük tedavisinde kullanılır.", "components": ["Hidrokodon bitartrat"], "usage": "Günde 2-4 kez. Dozaj 5-30 mg.", "sideEffects": ["Uyku hali", "Kabızlık", "Bağımlılık riski"], "interactions": ["Alkol", "Benzodiazepinler"], "synonyms": ["Vicodin", "Hidrokodon"]},
        {"latinName": "Methadone", "turkishName": "Metadon", "definition": "Opioid analjezik ve bağımlılık tedavisi. Ağrı ve opioid bağımlılığı tedavisinde kullanılır.", "components": ["Metadon hidroklorür"], "usage": "Günde 1-2 kez. Dozaj 5-120 mg.", "sideEffects": ["Solunum depresyonu", "QT uzaması", "Bağımlılık riski"], "interactions": ["Birçok ilaçla etkileşim"], "synonyms": ["Dolophine", "Metadon"]},
        {"latinName": "Buprenorphine", "turkishName": "Buprenorfin", "definition": "Opioid analjezik ve bağımlılık tedavisi. Ağrı ve opioid bağımlılığı tedavisinde kullanılır.", "components": ["Buprenorfin hidroklorür"], "usage": "Sublingual/Transdermal, dozaj ağrı şiddetine göre.", "sideEffects": ["Solunum depresyonu", "Uyku hali"], "interactions": ["Benzodiazepinler"], "synonyms": ["Subutex", "Buprenorfin"]},
        {"latinName": "Naloxone", "turkishName": "Nalokson", "definition": "Opioid antagonist. Opioid aşırı doz tedavisinde kullanılır.", "components": ["Nalokson hidroklorür"], "usage": "IV/IM/IN, aşırı doz durumunda.", "sideEffects": ["Opioid yoksunluk sendromu", "Ajitasyon"], "interactions": ["Opioidler"], "synonyms": ["Narcan", "Nalokson"]},
        {"latinName": "Naltrexone", "turkishName": "Naltrekson", "definition": "Opioid antagonist. Opioid ve alkol bağımlılığı tedavisinde kullanılır.", "components": ["Naltrekson hidroklorür"], "usage": "Günde 1 kez. Dozaj 50 mg.", "sideEffects": ["Karaciğer hasarı", "Mide bulantısı"], "interactions": ["Opioidler"], "synonyms": ["ReVia", "Naltrekson"]},
        {"latinName": "Sumatriptan", "turkishName": "Sumatriptan", "definition": "Triptan. Migren atağı tedavisinde kullanılır.", "components": ["Sumatriptan süksinat"], "usage": "Atağın başında, PO/SC/IN. Dozaj 25-100 mg PO, 6 mg SC.", "sideEffects": ["Göğüs sıkışması", "Baş dönmesi", "Yorgunluk"], "interactions": ["MAO inhibitörleri", "SSRI'lar"], "synonyms": ["Imitrex", "Sumatriptan"]},
        {"latinName": "Rizatriptan", "turkishName": "Rizatriptan", "definition": "Triptan. Migren atağı tedavisinde kullanılır.", "components": ["Rizatriptan benzoilat"], "usage": "Atağın başında. Dozaj 5-10 mg.", "sideEffects": ["Göğüs sıkışması", "Baş dönmesi"], "interactions": ["MAO inhibitörleri", "Propranolol"], "synonyms": ["Maxalt", "Rizatriptan"]},
        {"latinName": "Zolmitriptan", "turkishName": "Zolmitriptan", "definition": "Triptan. Migren atağı tedavisinde kullanılır.", "components": ["Zolmitriptan"], "usage": "Atağın başında. Dozaj 2.5-5 mg.", "sideEffects": ["Göğüs sıkışması", "Baş dönmesi"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Zomig", "Zolmitriptan"]},
        {"latinName": "Eletriptan", "turkishName": "Eletriptan", "definition": "Triptan. Migren atağı tedavisinde kullanılır.", "components": ["Eletriptan hidrobromür"], "usage": "Atağın başında. Dozaj 20-40 mg.", "sideEffects": ["Göğüs sıkışması", "Baş dönmesi"], "interactions": ["MAO inhibitörleri", "Eritromisin"], "synonyms": ["Relpax", "Eletriptan"]},
        {"latinName": "Almotriptan", "turkishName": "Almotriptan", "definition": "Triptan. Migren atağı tedavisinde kullanılır.", "components": ["Almotriptan malat"], "usage": "Atağın başında. Dozaj 6.25-12.5 mg.", "sideEffects": ["Göğüs sıkışması", "Baş dönmesi"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Axert", "Almotriptan"]},
        {"latinName": "Frovatriptan", "turkishName": "Frovatriptan", "definition": "Triptan. Migren atağı tedavisinde kullanılır.", "components": ["Frovatriptan süksinat"], "usage": "Atağın başında. Dozaj 2.5 mg.", "sideEffects": ["Göğüs sıkışması", "Baş dönmesi"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Frova", "Frovatriptan"]},
        {"latinName": "Naratriptan", "turkishName": "Naratriptan", "definition": "Triptan. Migren atağı tedavisinde kullanılır.", "components": ["Naratriptan hidroklorür"], "usage": "Atağın başında. Dozaj 1-2.5 mg.", "sideEffects": ["Göğüs sıkışması", "Baş dönmesi"], "interactions": ["MAO inhibitörleri"], "synonyms": ["Amerge", "Naratriptan"]},
        {"latinName": "Ergotamine", "turkishName": "Ergotamin", "definition": "Ergot alkaloidi. Migren atağı tedavisinde kullanılır.", "components": ["Ergotamin tartarat"], "usage": "Atağın başında. Dozaj 1-2 mg.", "sideEffects": ["Mide bulantısı", "Periferik vazokonstriksiyon"], "interactions": ["MAO inhibitörleri", "Triptanlar"], "synonyms": ["Ergomar", "Ergotamin"]},
    ]
    
    all_drugs.extend(other_drugs[:remaining])
    
    # ID'leri ekle ve formatla
    result = []
    for i, drug in enumerate(all_drugs[:100], 1):
        result.append({
            "id": str(i),
            "latinName": drug["latinName"],
            "turkishName": drug["turkishName"],
            "category": "drug",
            "definition": drug["definition"],
            "components": drug["components"] if isinstance(drug["components"], list) else [drug["components"]],
            "usage": drug["usage"],
            "sideEffects": drug["sideEffects"] if isinstance(drug["sideEffects"], list) else [drug["sideEffects"]],
            "interactions": drug["interactions"] if isinstance(drug["interactions"], list) else [drug["interactions"]],
            "synonyms": drug["synonyms"] if isinstance(drug["synonyms"], list) else [drug["synonyms"]],
            "isBookmarked": False
        })
    
    return result

# Bu script çok uzun olacak, her kategori için ayrı fonksiyonlar yazacağım
# Şimdilik sadece ilaçlar için tam fonksiyonu yazdım
# Diğer kategoriler için de benzer şekilde devam edeceğim

if __name__ == "__main__":
    drugs = generate_drugs()
    print(f"Generated {len(drugs)} drugs")
    print(json.dumps(drugs[:5], indent=2, ensure_ascii=False))

